# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: perception/perception_frame_context.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common import geometry_pb2 as common_dot_geometry__pb2
from common.vehicle_state import vehicle_state_pb2 as common_dot_vehicle__state_dot_vehicle__state__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='perception/perception_frame_context.proto',
  package='deeproute.perception',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n)perception/perception_frame_context.proto\x12\x14\x64\x65\x65proute.perception\x1a\x15\x63ommon/geometry.proto\x1a(common/vehicle_state/vehicle_state.proto\"\xbd\x01\n\x14SensorInputDebugInfo\x12\x13\n\x0bsensor_name\x18\x01 \x01(\t\x12\x17\n\x0fmd5_hash_string\x18\x02 \x01(\t\x12\x17\n\x0ftimestamp_micro\x18\x03 \x01(\x03\x12+\n\x08position\x18\x04 \x01(\x0b\x32\x19.deeproute.common.Point3D\x12\x31\n\x0eroll_pitch_yaw\x18\x05 \x01(\x0b\x32\x19.deeproute.common.Point3D\"\xcc\x01\n\x0c\x46rameContext\x12\x10\n\x08\x66rame_id\x18\x01 \x01(\x04\x12\x38\n\x10input_car_states\x18\x02 \x03(\x0b\x32\x1e.deeproute.common.VehicleState\x12L\n\x18sensor_input_debug_infos\x18\x03 \x03(\x0b\x32*.deeproute.perception.SensorInputDebugInfo\x12\"\n\x1aline_manager_hidden_states\x18\x04 \x01(\x0c')
  ,
  dependencies=[common_dot_geometry__pb2.DESCRIPTOR,common_dot_vehicle__state_dot_vehicle__state__pb2.DESCRIPTOR,])




_SENSORINPUTDEBUGINFO = _descriptor.Descriptor(
  name='SensorInputDebugInfo',
  full_name='deeproute.perception.SensorInputDebugInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sensor_name', full_name='deeproute.perception.SensorInputDebugInfo.sensor_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='md5_hash_string', full_name='deeproute.perception.SensorInputDebugInfo.md5_hash_string', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp_micro', full_name='deeproute.perception.SensorInputDebugInfo.timestamp_micro', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='position', full_name='deeproute.perception.SensorInputDebugInfo.position', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='roll_pitch_yaw', full_name='deeproute.perception.SensorInputDebugInfo.roll_pitch_yaw', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=133,
  serialized_end=322,
)


_FRAMECONTEXT = _descriptor.Descriptor(
  name='FrameContext',
  full_name='deeproute.perception.FrameContext',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='frame_id', full_name='deeproute.perception.FrameContext.frame_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='input_car_states', full_name='deeproute.perception.FrameContext.input_car_states', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sensor_input_debug_infos', full_name='deeproute.perception.FrameContext.sensor_input_debug_infos', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='line_manager_hidden_states', full_name='deeproute.perception.FrameContext.line_manager_hidden_states', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=325,
  serialized_end=529,
)

_SENSORINPUTDEBUGINFO.fields_by_name['position'].message_type = common_dot_geometry__pb2._POINT3D
_SENSORINPUTDEBUGINFO.fields_by_name['roll_pitch_yaw'].message_type = common_dot_geometry__pb2._POINT3D
_FRAMECONTEXT.fields_by_name['input_car_states'].message_type = common_dot_vehicle__state_dot_vehicle__state__pb2._VEHICLESTATE
_FRAMECONTEXT.fields_by_name['sensor_input_debug_infos'].message_type = _SENSORINPUTDEBUGINFO
DESCRIPTOR.message_types_by_name['SensorInputDebugInfo'] = _SENSORINPUTDEBUGINFO
DESCRIPTOR.message_types_by_name['FrameContext'] = _FRAMECONTEXT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SensorInputDebugInfo = _reflection.GeneratedProtocolMessageType('SensorInputDebugInfo', (_message.Message,), dict(
  DESCRIPTOR = _SENSORINPUTDEBUGINFO,
  __module__ = 'perception.perception_frame_context_pb2'
  # @@protoc_insertion_point(class_scope:deeproute.perception.SensorInputDebugInfo)
  ))
_sym_db.RegisterMessage(SensorInputDebugInfo)

FrameContext = _reflection.GeneratedProtocolMessageType('FrameContext', (_message.Message,), dict(
  DESCRIPTOR = _FRAMECONTEXT,
  __module__ = 'perception.perception_frame_context_pb2'
  # @@protoc_insertion_point(class_scope:deeproute.perception.FrameContext)
  ))
_sym_db.RegisterMessage(FrameContext)


# @@protoc_insertion_point(module_scope)
