# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tls_key/tls_key_srv.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'tls_key/tls_key_srv.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19tls_key/tls_key_srv.proto\x12\x10\x64\x65\x65proute.tlskey\"7\n\x12KeyLearningRequest\x12\x0e\n\x06uds_id\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\"h\n\x13KeyLearningResponse\x12\x0e\n\x06uds_id\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12.\n\x06status\x18\x03 \x01(\x0e\x32\x1e.deeproute.tlskey.TlsKeyStatus*\xf1\x01\n\x0cTlsKeyStatus\x12\x0f\n\x0bTLS_UNKNOWN\x10\x00\x12\x13\n\x0fTLS_KEY_SUCCESS\x10\x01\x12\x1f\n\x1bTLS_PASSWORD_UPDATE_FAILURE\x10\x02\x12 \n\x1cTLS_KEY_STORAGE_READ_FAILURE\x10\x03\x12\x1c\n\x18TLS_KEY_GSOMEIP_PRF_HASH\x10\x04\x12\x19\n\x15TLS_KEY_MK_SIZE_ERROR\x10\x05\x12\x1e\n\x1aTLS_KEY_GENER_RANDOM_ERROR\x10\x06\x12\x1f\n\x1bTLS_KEY_COMPUTER_CMAC_ERROR\x10\x07\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tls_key.tls_key_srv_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TLSKEYSTATUS']._serialized_start=211
  _globals['_TLSKEYSTATUS']._serialized_end=452
  _globals['_KEYLEARNINGREQUEST']._serialized_start=47
  _globals['_KEYLEARNINGREQUEST']._serialized_end=102
  _globals['_KEYLEARNINGRESPONSE']._serialized_start=104
  _globals['_KEYLEARNINGRESPONSE']._serialized_end=208
# @@protoc_insertion_point(module_scope)
