# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: idl/routing_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'idl/routing_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from routing import routing_pb2 as routing_dot_routing__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19idl/routing_service.proto\x12\x1d\x64\x65\x65proute.idl.routing_service\x1a\x15routing/routing.proto\"L\n\x12RoutingProcRequest\x12\x36\n\x0frouting_request\x18\x01 \x01(\x0b\x32\x1d.deeproute.routing.RoutingCMD\"P\n\x13RoutingProcResponse\x12\x39\n\x10routing_response\x18\x01 \x01(\x0b\x32\x1f.deeproute.routing.RoutingCMDRP\"0\n\x12RoutingInitRequest\x12\x1a\n\x12semantic_lmdb_path\x18\x01 \x01(\t\"\x15\n\x13RoutingInitResponse2\xee\x01\n\x0eRoutingService\x12m\n\x04Init\x12\x31.deeproute.idl.routing_service.RoutingInitRequest\x1a\x32.deeproute.idl.routing_service.RoutingInitResponse\x12m\n\x04Proc\x12\x31.deeproute.idl.routing_service.RoutingProcRequest\x1a\x32.deeproute.idl.routing_service.RoutingProcResponse')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'idl.routing_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROUTINGPROCREQUEST']._serialized_start=83
  _globals['_ROUTINGPROCREQUEST']._serialized_end=159
  _globals['_ROUTINGPROCRESPONSE']._serialized_start=161
  _globals['_ROUTINGPROCRESPONSE']._serialized_end=241
  _globals['_ROUTINGINITREQUEST']._serialized_start=243
  _globals['_ROUTINGINITREQUEST']._serialized_end=291
  _globals['_ROUTINGINITRESPONSE']._serialized_start=293
  _globals['_ROUTINGINITRESPONSE']._serialized_end=314
  _globals['_ROUTINGSERVICE']._serialized_start=317
  _globals['_ROUTINGSERVICE']._serialized_end=555
# @@protoc_insertion_point(module_scope)
