// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: offboard/ras_map/map_engine_grpc_service.proto
#ifndef GRPC_offboard_2fras_5fmap_2fmap_5fengine_5fgrpc_5fservice_2eproto__INCLUDED
#define GRPC_offboard_2fras_5fmap_2fmap_5fengine_5fgrpc_5fservice_2eproto__INCLUDED

#include "offboard/ras_map/map_engine_grpc_service.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace deeproute {
namespace grpc {
namespace ras_map {

class MapEngineService final {
 public:
  static constexpr char const* service_full_name() {
    return "deeproute.grpc.ras_map.MapEngineService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status MapEngineServiceCall(::grpc::ClientContext* context, const ::deeproute::grpc::ras_map::MapEngineRequest& request, ::deeproute::grpc::ras_map::MapEngineResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::deeproute::grpc::ras_map::MapEngineResponse>> AsyncMapEngineServiceCall(::grpc::ClientContext* context, const ::deeproute::grpc::ras_map::MapEngineRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::deeproute::grpc::ras_map::MapEngineResponse>>(AsyncMapEngineServiceCallRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::deeproute::grpc::ras_map::MapEngineResponse>> PrepareAsyncMapEngineServiceCall(::grpc::ClientContext* context, const ::deeproute::grpc::ras_map::MapEngineRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::deeproute::grpc::ras_map::MapEngineResponse>>(PrepareAsyncMapEngineServiceCallRaw(context, request, cq));
    }
    virtual ::grpc::Status InitMapEngine(::grpc::ClientContext* context, const ::deeproute::grpc::ras_map::InitMapEngineRequest& request, ::deeproute::grpc::ras_map::InitMapEngineResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::deeproute::grpc::ras_map::InitMapEngineResponse>> AsyncInitMapEngine(::grpc::ClientContext* context, const ::deeproute::grpc::ras_map::InitMapEngineRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::deeproute::grpc::ras_map::InitMapEngineResponse>>(AsyncInitMapEngineRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::deeproute::grpc::ras_map::InitMapEngineResponse>> PrepareAsyncInitMapEngine(::grpc::ClientContext* context, const ::deeproute::grpc::ras_map::InitMapEngineRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::deeproute::grpc::ras_map::InitMapEngineResponse>>(PrepareAsyncInitMapEngineRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void MapEngineServiceCall(::grpc::ClientContext* context, const ::deeproute::grpc::ras_map::MapEngineRequest* request, ::deeproute::grpc::ras_map::MapEngineResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void MapEngineServiceCall(::grpc::ClientContext* context, const ::deeproute::grpc::ras_map::MapEngineRequest* request, ::deeproute::grpc::ras_map::MapEngineResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void MapEngineServiceCall(::grpc::ClientContext* context, const ::deeproute::grpc::ras_map::MapEngineRequest* request, ::deeproute::grpc::ras_map::MapEngineResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      virtual void InitMapEngine(::grpc::ClientContext* context, const ::deeproute::grpc::ras_map::InitMapEngineRequest* request, ::deeproute::grpc::ras_map::InitMapEngineResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void InitMapEngine(::grpc::ClientContext* context, const ::deeproute::grpc::ras_map::InitMapEngineRequest* request, ::deeproute::grpc::ras_map::InitMapEngineResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void InitMapEngine(::grpc::ClientContext* context, const ::deeproute::grpc::ras_map::InitMapEngineRequest* request, ::deeproute::grpc::ras_map::InitMapEngineResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::deeproute::grpc::ras_map::MapEngineResponse>* AsyncMapEngineServiceCallRaw(::grpc::ClientContext* context, const ::deeproute::grpc::ras_map::MapEngineRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::deeproute::grpc::ras_map::MapEngineResponse>* PrepareAsyncMapEngineServiceCallRaw(::grpc::ClientContext* context, const ::deeproute::grpc::ras_map::MapEngineRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::deeproute::grpc::ras_map::InitMapEngineResponse>* AsyncInitMapEngineRaw(::grpc::ClientContext* context, const ::deeproute::grpc::ras_map::InitMapEngineRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::deeproute::grpc::ras_map::InitMapEngineResponse>* PrepareAsyncInitMapEngineRaw(::grpc::ClientContext* context, const ::deeproute::grpc::ras_map::InitMapEngineRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status MapEngineServiceCall(::grpc::ClientContext* context, const ::deeproute::grpc::ras_map::MapEngineRequest& request, ::deeproute::grpc::ras_map::MapEngineResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::deeproute::grpc::ras_map::MapEngineResponse>> AsyncMapEngineServiceCall(::grpc::ClientContext* context, const ::deeproute::grpc::ras_map::MapEngineRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::deeproute::grpc::ras_map::MapEngineResponse>>(AsyncMapEngineServiceCallRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::deeproute::grpc::ras_map::MapEngineResponse>> PrepareAsyncMapEngineServiceCall(::grpc::ClientContext* context, const ::deeproute::grpc::ras_map::MapEngineRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::deeproute::grpc::ras_map::MapEngineResponse>>(PrepareAsyncMapEngineServiceCallRaw(context, request, cq));
    }
    ::grpc::Status InitMapEngine(::grpc::ClientContext* context, const ::deeproute::grpc::ras_map::InitMapEngineRequest& request, ::deeproute::grpc::ras_map::InitMapEngineResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::deeproute::grpc::ras_map::InitMapEngineResponse>> AsyncInitMapEngine(::grpc::ClientContext* context, const ::deeproute::grpc::ras_map::InitMapEngineRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::deeproute::grpc::ras_map::InitMapEngineResponse>>(AsyncInitMapEngineRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::deeproute::grpc::ras_map::InitMapEngineResponse>> PrepareAsyncInitMapEngine(::grpc::ClientContext* context, const ::deeproute::grpc::ras_map::InitMapEngineRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::deeproute::grpc::ras_map::InitMapEngineResponse>>(PrepareAsyncInitMapEngineRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void MapEngineServiceCall(::grpc::ClientContext* context, const ::deeproute::grpc::ras_map::MapEngineRequest* request, ::deeproute::grpc::ras_map::MapEngineResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void MapEngineServiceCall(::grpc::ClientContext* context, const ::deeproute::grpc::ras_map::MapEngineRequest* request, ::deeproute::grpc::ras_map::MapEngineResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void MapEngineServiceCall(::grpc::ClientContext* context, const ::deeproute::grpc::ras_map::MapEngineRequest* request, ::deeproute::grpc::ras_map::MapEngineResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void InitMapEngine(::grpc::ClientContext* context, const ::deeproute::grpc::ras_map::InitMapEngineRequest* request, ::deeproute::grpc::ras_map::InitMapEngineResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void InitMapEngine(::grpc::ClientContext* context, const ::deeproute::grpc::ras_map::InitMapEngineRequest* request, ::deeproute::grpc::ras_map::InitMapEngineResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void InitMapEngine(::grpc::ClientContext* context, const ::deeproute::grpc::ras_map::InitMapEngineRequest* request, ::deeproute::grpc::ras_map::InitMapEngineResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::deeproute::grpc::ras_map::MapEngineResponse>* AsyncMapEngineServiceCallRaw(::grpc::ClientContext* context, const ::deeproute::grpc::ras_map::MapEngineRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::deeproute::grpc::ras_map::MapEngineResponse>* PrepareAsyncMapEngineServiceCallRaw(::grpc::ClientContext* context, const ::deeproute::grpc::ras_map::MapEngineRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::deeproute::grpc::ras_map::InitMapEngineResponse>* AsyncInitMapEngineRaw(::grpc::ClientContext* context, const ::deeproute::grpc::ras_map::InitMapEngineRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::deeproute::grpc::ras_map::InitMapEngineResponse>* PrepareAsyncInitMapEngineRaw(::grpc::ClientContext* context, const ::deeproute::grpc::ras_map::InitMapEngineRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_MapEngineServiceCall_;
    const ::grpc::internal::RpcMethod rpcmethod_InitMapEngine_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status MapEngineServiceCall(::grpc::ServerContext* context, const ::deeproute::grpc::ras_map::MapEngineRequest* request, ::deeproute::grpc::ras_map::MapEngineResponse* response);
    virtual ::grpc::Status InitMapEngine(::grpc::ServerContext* context, const ::deeproute::grpc::ras_map::InitMapEngineRequest* request, ::deeproute::grpc::ras_map::InitMapEngineResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_MapEngineServiceCall : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_MapEngineServiceCall() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_MapEngineServiceCall() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status MapEngineServiceCall(::grpc::ServerContext* /*context*/, const ::deeproute::grpc::ras_map::MapEngineRequest* /*request*/, ::deeproute::grpc::ras_map::MapEngineResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestMapEngineServiceCall(::grpc::ServerContext* context, ::deeproute::grpc::ras_map::MapEngineRequest* request, ::grpc::ServerAsyncResponseWriter< ::deeproute::grpc::ras_map::MapEngineResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_InitMapEngine : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_InitMapEngine() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_InitMapEngine() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status InitMapEngine(::grpc::ServerContext* /*context*/, const ::deeproute::grpc::ras_map::InitMapEngineRequest* /*request*/, ::deeproute::grpc::ras_map::InitMapEngineResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestInitMapEngine(::grpc::ServerContext* context, ::deeproute::grpc::ras_map::InitMapEngineRequest* request, ::grpc::ServerAsyncResponseWriter< ::deeproute::grpc::ras_map::InitMapEngineResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_MapEngineServiceCall<WithAsyncMethod_InitMapEngine<Service > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_MapEngineServiceCall : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_MapEngineServiceCall() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::deeproute::grpc::ras_map::MapEngineRequest, ::deeproute::grpc::ras_map::MapEngineResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::deeproute::grpc::ras_map::MapEngineRequest* request, ::deeproute::grpc::ras_map::MapEngineResponse* response) { return this->MapEngineServiceCall(context, request, response); }));}
    void SetMessageAllocatorFor_MapEngineServiceCall(
        ::grpc::experimental::MessageAllocator< ::deeproute::grpc::ras_map::MapEngineRequest, ::deeproute::grpc::ras_map::MapEngineResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::deeproute::grpc::ras_map::MapEngineRequest, ::deeproute::grpc::ras_map::MapEngineResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_MapEngineServiceCall() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status MapEngineServiceCall(::grpc::ServerContext* /*context*/, const ::deeproute::grpc::ras_map::MapEngineRequest* /*request*/, ::deeproute::grpc::ras_map::MapEngineResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* MapEngineServiceCall(
      ::grpc::CallbackServerContext* /*context*/, const ::deeproute::grpc::ras_map::MapEngineRequest* /*request*/, ::deeproute::grpc::ras_map::MapEngineResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* MapEngineServiceCall(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::deeproute::grpc::ras_map::MapEngineRequest* /*request*/, ::deeproute::grpc::ras_map::MapEngineResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_InitMapEngine : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_InitMapEngine() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::deeproute::grpc::ras_map::InitMapEngineRequest, ::deeproute::grpc::ras_map::InitMapEngineResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::deeproute::grpc::ras_map::InitMapEngineRequest* request, ::deeproute::grpc::ras_map::InitMapEngineResponse* response) { return this->InitMapEngine(context, request, response); }));}
    void SetMessageAllocatorFor_InitMapEngine(
        ::grpc::experimental::MessageAllocator< ::deeproute::grpc::ras_map::InitMapEngineRequest, ::deeproute::grpc::ras_map::InitMapEngineResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(1);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::deeproute::grpc::ras_map::InitMapEngineRequest, ::deeproute::grpc::ras_map::InitMapEngineResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_InitMapEngine() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status InitMapEngine(::grpc::ServerContext* /*context*/, const ::deeproute::grpc::ras_map::InitMapEngineRequest* /*request*/, ::deeproute::grpc::ras_map::InitMapEngineResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* InitMapEngine(
      ::grpc::CallbackServerContext* /*context*/, const ::deeproute::grpc::ras_map::InitMapEngineRequest* /*request*/, ::deeproute::grpc::ras_map::InitMapEngineResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* InitMapEngine(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::deeproute::grpc::ras_map::InitMapEngineRequest* /*request*/, ::deeproute::grpc::ras_map::InitMapEngineResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_MapEngineServiceCall<ExperimentalWithCallbackMethod_InitMapEngine<Service > > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_MapEngineServiceCall<ExperimentalWithCallbackMethod_InitMapEngine<Service > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_MapEngineServiceCall : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_MapEngineServiceCall() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_MapEngineServiceCall() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status MapEngineServiceCall(::grpc::ServerContext* /*context*/, const ::deeproute::grpc::ras_map::MapEngineRequest* /*request*/, ::deeproute::grpc::ras_map::MapEngineResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_InitMapEngine : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_InitMapEngine() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_InitMapEngine() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status InitMapEngine(::grpc::ServerContext* /*context*/, const ::deeproute::grpc::ras_map::InitMapEngineRequest* /*request*/, ::deeproute::grpc::ras_map::InitMapEngineResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_MapEngineServiceCall : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_MapEngineServiceCall() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_MapEngineServiceCall() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status MapEngineServiceCall(::grpc::ServerContext* /*context*/, const ::deeproute::grpc::ras_map::MapEngineRequest* /*request*/, ::deeproute::grpc::ras_map::MapEngineResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestMapEngineServiceCall(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_InitMapEngine : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_InitMapEngine() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_InitMapEngine() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status InitMapEngine(::grpc::ServerContext* /*context*/, const ::deeproute::grpc::ras_map::InitMapEngineRequest* /*request*/, ::deeproute::grpc::ras_map::InitMapEngineResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestInitMapEngine(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_MapEngineServiceCall : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_MapEngineServiceCall() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->MapEngineServiceCall(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_MapEngineServiceCall() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status MapEngineServiceCall(::grpc::ServerContext* /*context*/, const ::deeproute::grpc::ras_map::MapEngineRequest* /*request*/, ::deeproute::grpc::ras_map::MapEngineResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* MapEngineServiceCall(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* MapEngineServiceCall(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_InitMapEngine : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_InitMapEngine() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->InitMapEngine(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_InitMapEngine() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status InitMapEngine(::grpc::ServerContext* /*context*/, const ::deeproute::grpc::ras_map::InitMapEngineRequest* /*request*/, ::deeproute::grpc::ras_map::InitMapEngineResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* InitMapEngine(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* InitMapEngine(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_MapEngineServiceCall : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_MapEngineServiceCall() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::deeproute::grpc::ras_map::MapEngineRequest, ::deeproute::grpc::ras_map::MapEngineResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::deeproute::grpc::ras_map::MapEngineRequest, ::deeproute::grpc::ras_map::MapEngineResponse>* streamer) {
                       return this->StreamedMapEngineServiceCall(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_MapEngineServiceCall() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status MapEngineServiceCall(::grpc::ServerContext* /*context*/, const ::deeproute::grpc::ras_map::MapEngineRequest* /*request*/, ::deeproute::grpc::ras_map::MapEngineResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedMapEngineServiceCall(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::deeproute::grpc::ras_map::MapEngineRequest,::deeproute::grpc::ras_map::MapEngineResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_InitMapEngine : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_InitMapEngine() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::deeproute::grpc::ras_map::InitMapEngineRequest, ::deeproute::grpc::ras_map::InitMapEngineResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::deeproute::grpc::ras_map::InitMapEngineRequest, ::deeproute::grpc::ras_map::InitMapEngineResponse>* streamer) {
                       return this->StreamedInitMapEngine(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_InitMapEngine() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status InitMapEngine(::grpc::ServerContext* /*context*/, const ::deeproute::grpc::ras_map::InitMapEngineRequest* /*request*/, ::deeproute::grpc::ras_map::InitMapEngineResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedInitMapEngine(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::deeproute::grpc::ras_map::InitMapEngineRequest,::deeproute::grpc::ras_map::InitMapEngineResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_MapEngineServiceCall<WithStreamedUnaryMethod_InitMapEngine<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_MapEngineServiceCall<WithStreamedUnaryMethod_InitMapEngine<Service > > StreamedService;
};

}  // namespace ras_map
}  // namespace grpc
}  // namespace deeproute


#endif  // GRPC_offboard_2fras_5fmap_2fmap_5fengine_5fgrpc_5fservice_2eproto__INCLUDED
