// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: offboard/planning/ilqr_solver_debug_info.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_offboard_2fplanning_2filqr_5fsolver_5fdebug_5finfo_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_offboard_2fplanning_2filqr_5fsolver_5fdebug_5finfo_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3013000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3013000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_offboard_2fplanning_2filqr_5fsolver_5fdebug_5finfo_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_offboard_2fplanning_2filqr_5fsolver_5fdebug_5finfo_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[4]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_offboard_2fplanning_2filqr_5fsolver_5fdebug_5finfo_2eproto;
namespace deeproute {
namespace planning {
class IlqrComfortHardCost;
class IlqrComfortHardCostDefaultTypeInternal;
extern IlqrComfortHardCostDefaultTypeInternal _IlqrComfortHardCost_default_instance_;
class IlqrComfortSoftCost;
class IlqrComfortSoftCostDefaultTypeInternal;
extern IlqrComfortSoftCostDefaultTypeInternal _IlqrComfortSoftCost_default_instance_;
class IlqrCostInfo;
class IlqrCostInfoDefaultTypeInternal;
extern IlqrCostInfoDefaultTypeInternal _IlqrCostInfo_default_instance_;
class IlqrSolverDebugInfo;
class IlqrSolverDebugInfoDefaultTypeInternal;
extern IlqrSolverDebugInfoDefaultTypeInternal _IlqrSolverDebugInfo_default_instance_;
}  // namespace planning
}  // namespace deeproute
PROTOBUF_NAMESPACE_OPEN
template<> ::deeproute::planning::IlqrComfortHardCost* Arena::CreateMaybeMessage<::deeproute::planning::IlqrComfortHardCost>(Arena*);
template<> ::deeproute::planning::IlqrComfortSoftCost* Arena::CreateMaybeMessage<::deeproute::planning::IlqrComfortSoftCost>(Arena*);
template<> ::deeproute::planning::IlqrCostInfo* Arena::CreateMaybeMessage<::deeproute::planning::IlqrCostInfo>(Arena*);
template<> ::deeproute::planning::IlqrSolverDebugInfo* Arena::CreateMaybeMessage<::deeproute::planning::IlqrSolverDebugInfo>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace deeproute {
namespace planning {

// ===================================================================

class IlqrSolverDebugInfo PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:deeproute.planning.IlqrSolverDebugInfo) */ {
 public:
  inline IlqrSolverDebugInfo() : IlqrSolverDebugInfo(nullptr) {}
  virtual ~IlqrSolverDebugInfo();

  IlqrSolverDebugInfo(const IlqrSolverDebugInfo& from);
  IlqrSolverDebugInfo(IlqrSolverDebugInfo&& from) noexcept
    : IlqrSolverDebugInfo() {
    *this = ::std::move(from);
  }

  inline IlqrSolverDebugInfo& operator=(const IlqrSolverDebugInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline IlqrSolverDebugInfo& operator=(IlqrSolverDebugInfo&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const IlqrSolverDebugInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const IlqrSolverDebugInfo* internal_default_instance() {
    return reinterpret_cast<const IlqrSolverDebugInfo*>(
               &_IlqrSolverDebugInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(IlqrSolverDebugInfo& a, IlqrSolverDebugInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(IlqrSolverDebugInfo* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(IlqrSolverDebugInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline IlqrSolverDebugInfo* New() const final {
    return CreateMaybeMessage<IlqrSolverDebugInfo>(nullptr);
  }

  IlqrSolverDebugInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<IlqrSolverDebugInfo>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const IlqrSolverDebugInfo& from);
  void MergeFrom(const IlqrSolverDebugInfo& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(IlqrSolverDebugInfo* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "deeproute.planning.IlqrSolverDebugInfo";
  }
  protected:
  explicit IlqrSolverDebugInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_offboard_2fplanning_2filqr_5fsolver_5fdebug_5finfo_2eproto);
    return ::descriptor_table_offboard_2fplanning_2filqr_5fsolver_5fdebug_5finfo_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kInitCostFieldNumber = 4,
    kFinalCostFieldNumber = 5,
    kRefLineIdFieldNumber = 1,
    kNumIterFieldNumber = 2,
    kSuccessFieldNumber = 3,
    kConvergedFieldNumber = 6,
  };
  // optional .deeproute.planning.IlqrCostInfo init_cost = 4;
  bool has_init_cost() const;
  private:
  bool _internal_has_init_cost() const;
  public:
  void clear_init_cost();
  const ::deeproute::planning::IlqrCostInfo& init_cost() const;
  ::deeproute::planning::IlqrCostInfo* release_init_cost();
  ::deeproute::planning::IlqrCostInfo* mutable_init_cost();
  void set_allocated_init_cost(::deeproute::planning::IlqrCostInfo* init_cost);
  private:
  const ::deeproute::planning::IlqrCostInfo& _internal_init_cost() const;
  ::deeproute::planning::IlqrCostInfo* _internal_mutable_init_cost();
  public:
  void unsafe_arena_set_allocated_init_cost(
      ::deeproute::planning::IlqrCostInfo* init_cost);
  ::deeproute::planning::IlqrCostInfo* unsafe_arena_release_init_cost();

  // optional .deeproute.planning.IlqrCostInfo final_cost = 5;
  bool has_final_cost() const;
  private:
  bool _internal_has_final_cost() const;
  public:
  void clear_final_cost();
  const ::deeproute::planning::IlqrCostInfo& final_cost() const;
  ::deeproute::planning::IlqrCostInfo* release_final_cost();
  ::deeproute::planning::IlqrCostInfo* mutable_final_cost();
  void set_allocated_final_cost(::deeproute::planning::IlqrCostInfo* final_cost);
  private:
  const ::deeproute::planning::IlqrCostInfo& _internal_final_cost() const;
  ::deeproute::planning::IlqrCostInfo* _internal_mutable_final_cost();
  public:
  void unsafe_arena_set_allocated_final_cost(
      ::deeproute::planning::IlqrCostInfo* final_cost);
  ::deeproute::planning::IlqrCostInfo* unsafe_arena_release_final_cost();

  // optional int32 ref_line_id = 1;
  bool has_ref_line_id() const;
  private:
  bool _internal_has_ref_line_id() const;
  public:
  void clear_ref_line_id();
  ::PROTOBUF_NAMESPACE_ID::int32 ref_line_id() const;
  void set_ref_line_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_ref_line_id() const;
  void _internal_set_ref_line_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // optional int32 num_iter = 2 [default = 0];
  bool has_num_iter() const;
  private:
  bool _internal_has_num_iter() const;
  public:
  void clear_num_iter();
  ::PROTOBUF_NAMESPACE_ID::int32 num_iter() const;
  void set_num_iter(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_num_iter() const;
  void _internal_set_num_iter(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // optional bool success = 3 [default = false];
  bool has_success() const;
  private:
  bool _internal_has_success() const;
  public:
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // optional bool converged = 6 [default = false];
  bool has_converged() const;
  private:
  bool _internal_has_converged() const;
  public:
  void clear_converged();
  bool converged() const;
  void set_converged(bool value);
  private:
  bool _internal_converged() const;
  void _internal_set_converged(bool value);
  public:

  // @@protoc_insertion_point(class_scope:deeproute.planning.IlqrSolverDebugInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::deeproute::planning::IlqrCostInfo* init_cost_;
  ::deeproute::planning::IlqrCostInfo* final_cost_;
  ::PROTOBUF_NAMESPACE_ID::int32 ref_line_id_;
  ::PROTOBUF_NAMESPACE_ID::int32 num_iter_;
  bool success_;
  bool converged_;
  friend struct ::TableStruct_offboard_2fplanning_2filqr_5fsolver_5fdebug_5finfo_2eproto;
};
// -------------------------------------------------------------------

class IlqrComfortSoftCost PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:deeproute.planning.IlqrComfortSoftCost) */ {
 public:
  inline IlqrComfortSoftCost() : IlqrComfortSoftCost(nullptr) {}
  virtual ~IlqrComfortSoftCost();

  IlqrComfortSoftCost(const IlqrComfortSoftCost& from);
  IlqrComfortSoftCost(IlqrComfortSoftCost&& from) noexcept
    : IlqrComfortSoftCost() {
    *this = ::std::move(from);
  }

  inline IlqrComfortSoftCost& operator=(const IlqrComfortSoftCost& from) {
    CopyFrom(from);
    return *this;
  }
  inline IlqrComfortSoftCost& operator=(IlqrComfortSoftCost&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const IlqrComfortSoftCost& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const IlqrComfortSoftCost* internal_default_instance() {
    return reinterpret_cast<const IlqrComfortSoftCost*>(
               &_IlqrComfortSoftCost_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(IlqrComfortSoftCost& a, IlqrComfortSoftCost& b) {
    a.Swap(&b);
  }
  inline void Swap(IlqrComfortSoftCost* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(IlqrComfortSoftCost* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline IlqrComfortSoftCost* New() const final {
    return CreateMaybeMessage<IlqrComfortSoftCost>(nullptr);
  }

  IlqrComfortSoftCost* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<IlqrComfortSoftCost>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const IlqrComfortSoftCost& from);
  void MergeFrom(const IlqrComfortSoftCost& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(IlqrComfortSoftCost* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "deeproute.planning.IlqrComfortSoftCost";
  }
  protected:
  explicit IlqrComfortSoftCost(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_offboard_2fplanning_2filqr_5fsolver_5fdebug_5finfo_2eproto);
    return ::descriptor_table_offboard_2fplanning_2filqr_5fsolver_5fdebug_5finfo_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAccelSoftCostFieldNumber = 1,
    kDecelSoftCostFieldNumber = 2,
    kJerkSoftCostFieldNumber = 3,
    kLatAccelSoftCostFieldNumber = 4,
    kLatJerkSoftCostFieldNumber = 5,
    kDdkappaSoftCostFieldNumber = 6,
    kDecelJerkSoftCostFieldNumber = 7,
  };
  // optional double accel_soft_cost = 1 [default = 0];
  bool has_accel_soft_cost() const;
  private:
  bool _internal_has_accel_soft_cost() const;
  public:
  void clear_accel_soft_cost();
  double accel_soft_cost() const;
  void set_accel_soft_cost(double value);
  private:
  double _internal_accel_soft_cost() const;
  void _internal_set_accel_soft_cost(double value);
  public:

  // optional double decel_soft_cost = 2 [default = 0];
  bool has_decel_soft_cost() const;
  private:
  bool _internal_has_decel_soft_cost() const;
  public:
  void clear_decel_soft_cost();
  double decel_soft_cost() const;
  void set_decel_soft_cost(double value);
  private:
  double _internal_decel_soft_cost() const;
  void _internal_set_decel_soft_cost(double value);
  public:

  // optional double jerk_soft_cost = 3 [default = 0];
  bool has_jerk_soft_cost() const;
  private:
  bool _internal_has_jerk_soft_cost() const;
  public:
  void clear_jerk_soft_cost();
  double jerk_soft_cost() const;
  void set_jerk_soft_cost(double value);
  private:
  double _internal_jerk_soft_cost() const;
  void _internal_set_jerk_soft_cost(double value);
  public:

  // optional double lat_accel_soft_cost = 4 [default = 0];
  bool has_lat_accel_soft_cost() const;
  private:
  bool _internal_has_lat_accel_soft_cost() const;
  public:
  void clear_lat_accel_soft_cost();
  double lat_accel_soft_cost() const;
  void set_lat_accel_soft_cost(double value);
  private:
  double _internal_lat_accel_soft_cost() const;
  void _internal_set_lat_accel_soft_cost(double value);
  public:

  // optional double lat_jerk_soft_cost = 5 [default = 0];
  bool has_lat_jerk_soft_cost() const;
  private:
  bool _internal_has_lat_jerk_soft_cost() const;
  public:
  void clear_lat_jerk_soft_cost();
  double lat_jerk_soft_cost() const;
  void set_lat_jerk_soft_cost(double value);
  private:
  double _internal_lat_jerk_soft_cost() const;
  void _internal_set_lat_jerk_soft_cost(double value);
  public:

  // optional double ddkappa_soft_cost = 6 [default = 0];
  bool has_ddkappa_soft_cost() const;
  private:
  bool _internal_has_ddkappa_soft_cost() const;
  public:
  void clear_ddkappa_soft_cost();
  double ddkappa_soft_cost() const;
  void set_ddkappa_soft_cost(double value);
  private:
  double _internal_ddkappa_soft_cost() const;
  void _internal_set_ddkappa_soft_cost(double value);
  public:

  // optional double decel_jerk_soft_cost = 7 [default = 0];
  bool has_decel_jerk_soft_cost() const;
  private:
  bool _internal_has_decel_jerk_soft_cost() const;
  public:
  void clear_decel_jerk_soft_cost();
  double decel_jerk_soft_cost() const;
  void set_decel_jerk_soft_cost(double value);
  private:
  double _internal_decel_jerk_soft_cost() const;
  void _internal_set_decel_jerk_soft_cost(double value);
  public:

  // @@protoc_insertion_point(class_scope:deeproute.planning.IlqrComfortSoftCost)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  double accel_soft_cost_;
  double decel_soft_cost_;
  double jerk_soft_cost_;
  double lat_accel_soft_cost_;
  double lat_jerk_soft_cost_;
  double ddkappa_soft_cost_;
  double decel_jerk_soft_cost_;
  friend struct ::TableStruct_offboard_2fplanning_2filqr_5fsolver_5fdebug_5finfo_2eproto;
};
// -------------------------------------------------------------------

class IlqrComfortHardCost PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:deeproute.planning.IlqrComfortHardCost) */ {
 public:
  inline IlqrComfortHardCost() : IlqrComfortHardCost(nullptr) {}
  virtual ~IlqrComfortHardCost();

  IlqrComfortHardCost(const IlqrComfortHardCost& from);
  IlqrComfortHardCost(IlqrComfortHardCost&& from) noexcept
    : IlqrComfortHardCost() {
    *this = ::std::move(from);
  }

  inline IlqrComfortHardCost& operator=(const IlqrComfortHardCost& from) {
    CopyFrom(from);
    return *this;
  }
  inline IlqrComfortHardCost& operator=(IlqrComfortHardCost&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const IlqrComfortHardCost& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const IlqrComfortHardCost* internal_default_instance() {
    return reinterpret_cast<const IlqrComfortHardCost*>(
               &_IlqrComfortHardCost_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(IlqrComfortHardCost& a, IlqrComfortHardCost& b) {
    a.Swap(&b);
  }
  inline void Swap(IlqrComfortHardCost* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(IlqrComfortHardCost* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline IlqrComfortHardCost* New() const final {
    return CreateMaybeMessage<IlqrComfortHardCost>(nullptr);
  }

  IlqrComfortHardCost* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<IlqrComfortHardCost>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const IlqrComfortHardCost& from);
  void MergeFrom(const IlqrComfortHardCost& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(IlqrComfortHardCost* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "deeproute.planning.IlqrComfortHardCost";
  }
  protected:
  explicit IlqrComfortHardCost(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_offboard_2fplanning_2filqr_5fsolver_5fdebug_5finfo_2eproto);
    return ::descriptor_table_offboard_2fplanning_2filqr_5fsolver_5fdebug_5finfo_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kVxHardCostFieldNumber = 1,
    kAxHardCostFieldNumber = 2,
    kAyHardCostFieldNumber = 3,
    kJxHardCostFieldNumber = 4,
    kJyHardCostFieldNumber = 5,
    kKappaHardCostFieldNumber = 6,
    kDkappaHardCostFieldNumber = 7,
    kDdkappaHardCostFieldNumber = 8,
  };
  // optional double vx_hard_cost = 1 [default = 0];
  bool has_vx_hard_cost() const;
  private:
  bool _internal_has_vx_hard_cost() const;
  public:
  void clear_vx_hard_cost();
  double vx_hard_cost() const;
  void set_vx_hard_cost(double value);
  private:
  double _internal_vx_hard_cost() const;
  void _internal_set_vx_hard_cost(double value);
  public:

  // optional double ax_hard_cost = 2 [default = 0];
  bool has_ax_hard_cost() const;
  private:
  bool _internal_has_ax_hard_cost() const;
  public:
  void clear_ax_hard_cost();
  double ax_hard_cost() const;
  void set_ax_hard_cost(double value);
  private:
  double _internal_ax_hard_cost() const;
  void _internal_set_ax_hard_cost(double value);
  public:

  // optional double ay_hard_cost = 3 [default = 0];
  bool has_ay_hard_cost() const;
  private:
  bool _internal_has_ay_hard_cost() const;
  public:
  void clear_ay_hard_cost();
  double ay_hard_cost() const;
  void set_ay_hard_cost(double value);
  private:
  double _internal_ay_hard_cost() const;
  void _internal_set_ay_hard_cost(double value);
  public:

  // optional double jx_hard_cost = 4 [default = 0];
  bool has_jx_hard_cost() const;
  private:
  bool _internal_has_jx_hard_cost() const;
  public:
  void clear_jx_hard_cost();
  double jx_hard_cost() const;
  void set_jx_hard_cost(double value);
  private:
  double _internal_jx_hard_cost() const;
  void _internal_set_jx_hard_cost(double value);
  public:

  // optional double jy_hard_cost = 5 [default = 0];
  bool has_jy_hard_cost() const;
  private:
  bool _internal_has_jy_hard_cost() const;
  public:
  void clear_jy_hard_cost();
  double jy_hard_cost() const;
  void set_jy_hard_cost(double value);
  private:
  double _internal_jy_hard_cost() const;
  void _internal_set_jy_hard_cost(double value);
  public:

  // optional double kappa_hard_cost = 6 [default = 0];
  bool has_kappa_hard_cost() const;
  private:
  bool _internal_has_kappa_hard_cost() const;
  public:
  void clear_kappa_hard_cost();
  double kappa_hard_cost() const;
  void set_kappa_hard_cost(double value);
  private:
  double _internal_kappa_hard_cost() const;
  void _internal_set_kappa_hard_cost(double value);
  public:

  // optional double dkappa_hard_cost = 7 [default = 0];
  bool has_dkappa_hard_cost() const;
  private:
  bool _internal_has_dkappa_hard_cost() const;
  public:
  void clear_dkappa_hard_cost();
  double dkappa_hard_cost() const;
  void set_dkappa_hard_cost(double value);
  private:
  double _internal_dkappa_hard_cost() const;
  void _internal_set_dkappa_hard_cost(double value);
  public:

  // optional double ddkappa_hard_cost = 8 [default = 0];
  bool has_ddkappa_hard_cost() const;
  private:
  bool _internal_has_ddkappa_hard_cost() const;
  public:
  void clear_ddkappa_hard_cost();
  double ddkappa_hard_cost() const;
  void set_ddkappa_hard_cost(double value);
  private:
  double _internal_ddkappa_hard_cost() const;
  void _internal_set_ddkappa_hard_cost(double value);
  public:

  // @@protoc_insertion_point(class_scope:deeproute.planning.IlqrComfortHardCost)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  double vx_hard_cost_;
  double ax_hard_cost_;
  double ay_hard_cost_;
  double jx_hard_cost_;
  double jy_hard_cost_;
  double kappa_hard_cost_;
  double dkappa_hard_cost_;
  double ddkappa_hard_cost_;
  friend struct ::TableStruct_offboard_2fplanning_2filqr_5fsolver_5fdebug_5finfo_2eproto;
};
// -------------------------------------------------------------------

class IlqrCostInfo PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:deeproute.planning.IlqrCostInfo) */ {
 public:
  inline IlqrCostInfo() : IlqrCostInfo(nullptr) {}
  virtual ~IlqrCostInfo();

  IlqrCostInfo(const IlqrCostInfo& from);
  IlqrCostInfo(IlqrCostInfo&& from) noexcept
    : IlqrCostInfo() {
    *this = ::std::move(from);
  }

  inline IlqrCostInfo& operator=(const IlqrCostInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline IlqrCostInfo& operator=(IlqrCostInfo&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const IlqrCostInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const IlqrCostInfo* internal_default_instance() {
    return reinterpret_cast<const IlqrCostInfo*>(
               &_IlqrCostInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(IlqrCostInfo& a, IlqrCostInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(IlqrCostInfo* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(IlqrCostInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline IlqrCostInfo* New() const final {
    return CreateMaybeMessage<IlqrCostInfo>(nullptr);
  }

  IlqrCostInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<IlqrCostInfo>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const IlqrCostInfo& from);
  void MergeFrom(const IlqrCostInfo& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(IlqrCostInfo* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "deeproute.planning.IlqrCostInfo";
  }
  protected:
  explicit IlqrCostInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_offboard_2fplanning_2filqr_5fsolver_5fdebug_5finfo_2eproto);
    return ::descriptor_table_offboard_2fplanning_2filqr_5fsolver_5fdebug_5finfo_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kComfortSoftCostFieldNumber = 1,
    kComfortHardCostFieldNumber = 6,
    kStaticObjectSoftCostFieldNumber = 2,
    kDynamicObjectSoftCostFieldNumber = 3,
    kTrafficRuleSoftCostFieldNumber = 4,
    kConsistencySoftCostFieldNumber = 5,
    kStaticObjectHardCostFieldNumber = 7,
    kDynamicObjectHardCostFieldNumber = 8,
    kTrafficRuleHardCostFieldNumber = 9,
  };
  // optional .deeproute.planning.IlqrComfortSoftCost comfort_soft_cost = 1;
  bool has_comfort_soft_cost() const;
  private:
  bool _internal_has_comfort_soft_cost() const;
  public:
  void clear_comfort_soft_cost();
  const ::deeproute::planning::IlqrComfortSoftCost& comfort_soft_cost() const;
  ::deeproute::planning::IlqrComfortSoftCost* release_comfort_soft_cost();
  ::deeproute::planning::IlqrComfortSoftCost* mutable_comfort_soft_cost();
  void set_allocated_comfort_soft_cost(::deeproute::planning::IlqrComfortSoftCost* comfort_soft_cost);
  private:
  const ::deeproute::planning::IlqrComfortSoftCost& _internal_comfort_soft_cost() const;
  ::deeproute::planning::IlqrComfortSoftCost* _internal_mutable_comfort_soft_cost();
  public:
  void unsafe_arena_set_allocated_comfort_soft_cost(
      ::deeproute::planning::IlqrComfortSoftCost* comfort_soft_cost);
  ::deeproute::planning::IlqrComfortSoftCost* unsafe_arena_release_comfort_soft_cost();

  // optional .deeproute.planning.IlqrComfortHardCost comfort_hard_cost = 6;
  bool has_comfort_hard_cost() const;
  private:
  bool _internal_has_comfort_hard_cost() const;
  public:
  void clear_comfort_hard_cost();
  const ::deeproute::planning::IlqrComfortHardCost& comfort_hard_cost() const;
  ::deeproute::planning::IlqrComfortHardCost* release_comfort_hard_cost();
  ::deeproute::planning::IlqrComfortHardCost* mutable_comfort_hard_cost();
  void set_allocated_comfort_hard_cost(::deeproute::planning::IlqrComfortHardCost* comfort_hard_cost);
  private:
  const ::deeproute::planning::IlqrComfortHardCost& _internal_comfort_hard_cost() const;
  ::deeproute::planning::IlqrComfortHardCost* _internal_mutable_comfort_hard_cost();
  public:
  void unsafe_arena_set_allocated_comfort_hard_cost(
      ::deeproute::planning::IlqrComfortHardCost* comfort_hard_cost);
  ::deeproute::planning::IlqrComfortHardCost* unsafe_arena_release_comfort_hard_cost();

  // optional double static_object_soft_cost = 2 [default = 0];
  bool has_static_object_soft_cost() const;
  private:
  bool _internal_has_static_object_soft_cost() const;
  public:
  void clear_static_object_soft_cost();
  double static_object_soft_cost() const;
  void set_static_object_soft_cost(double value);
  private:
  double _internal_static_object_soft_cost() const;
  void _internal_set_static_object_soft_cost(double value);
  public:

  // optional double dynamic_object_soft_cost = 3 [default = 0];
  bool has_dynamic_object_soft_cost() const;
  private:
  bool _internal_has_dynamic_object_soft_cost() const;
  public:
  void clear_dynamic_object_soft_cost();
  double dynamic_object_soft_cost() const;
  void set_dynamic_object_soft_cost(double value);
  private:
  double _internal_dynamic_object_soft_cost() const;
  void _internal_set_dynamic_object_soft_cost(double value);
  public:

  // optional double traffic_rule_soft_cost = 4 [default = 0];
  bool has_traffic_rule_soft_cost() const;
  private:
  bool _internal_has_traffic_rule_soft_cost() const;
  public:
  void clear_traffic_rule_soft_cost();
  double traffic_rule_soft_cost() const;
  void set_traffic_rule_soft_cost(double value);
  private:
  double _internal_traffic_rule_soft_cost() const;
  void _internal_set_traffic_rule_soft_cost(double value);
  public:

  // optional double consistency_soft_cost = 5 [default = 0];
  bool has_consistency_soft_cost() const;
  private:
  bool _internal_has_consistency_soft_cost() const;
  public:
  void clear_consistency_soft_cost();
  double consistency_soft_cost() const;
  void set_consistency_soft_cost(double value);
  private:
  double _internal_consistency_soft_cost() const;
  void _internal_set_consistency_soft_cost(double value);
  public:

  // optional double static_object_hard_cost = 7 [default = 0];
  bool has_static_object_hard_cost() const;
  private:
  bool _internal_has_static_object_hard_cost() const;
  public:
  void clear_static_object_hard_cost();
  double static_object_hard_cost() const;
  void set_static_object_hard_cost(double value);
  private:
  double _internal_static_object_hard_cost() const;
  void _internal_set_static_object_hard_cost(double value);
  public:

  // optional double dynamic_object_hard_cost = 8 [default = 0];
  bool has_dynamic_object_hard_cost() const;
  private:
  bool _internal_has_dynamic_object_hard_cost() const;
  public:
  void clear_dynamic_object_hard_cost();
  double dynamic_object_hard_cost() const;
  void set_dynamic_object_hard_cost(double value);
  private:
  double _internal_dynamic_object_hard_cost() const;
  void _internal_set_dynamic_object_hard_cost(double value);
  public:

  // optional double traffic_rule_hard_cost = 9 [default = 0];
  bool has_traffic_rule_hard_cost() const;
  private:
  bool _internal_has_traffic_rule_hard_cost() const;
  public:
  void clear_traffic_rule_hard_cost();
  double traffic_rule_hard_cost() const;
  void set_traffic_rule_hard_cost(double value);
  private:
  double _internal_traffic_rule_hard_cost() const;
  void _internal_set_traffic_rule_hard_cost(double value);
  public:

  // @@protoc_insertion_point(class_scope:deeproute.planning.IlqrCostInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::deeproute::planning::IlqrComfortSoftCost* comfort_soft_cost_;
  ::deeproute::planning::IlqrComfortHardCost* comfort_hard_cost_;
  double static_object_soft_cost_;
  double dynamic_object_soft_cost_;
  double traffic_rule_soft_cost_;
  double consistency_soft_cost_;
  double static_object_hard_cost_;
  double dynamic_object_hard_cost_;
  double traffic_rule_hard_cost_;
  friend struct ::TableStruct_offboard_2fplanning_2filqr_5fsolver_5fdebug_5finfo_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// IlqrSolverDebugInfo

// optional int32 ref_line_id = 1;
inline bool IlqrSolverDebugInfo::_internal_has_ref_line_id() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool IlqrSolverDebugInfo::has_ref_line_id() const {
  return _internal_has_ref_line_id();
}
inline void IlqrSolverDebugInfo::clear_ref_line_id() {
  ref_line_id_ = 0;
  _has_bits_[0] &= ~0x00000004u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 IlqrSolverDebugInfo::_internal_ref_line_id() const {
  return ref_line_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 IlqrSolverDebugInfo::ref_line_id() const {
  // @@protoc_insertion_point(field_get:deeproute.planning.IlqrSolverDebugInfo.ref_line_id)
  return _internal_ref_line_id();
}
inline void IlqrSolverDebugInfo::_internal_set_ref_line_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000004u;
  ref_line_id_ = value;
}
inline void IlqrSolverDebugInfo::set_ref_line_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_ref_line_id(value);
  // @@protoc_insertion_point(field_set:deeproute.planning.IlqrSolverDebugInfo.ref_line_id)
}

// optional int32 num_iter = 2 [default = 0];
inline bool IlqrSolverDebugInfo::_internal_has_num_iter() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool IlqrSolverDebugInfo::has_num_iter() const {
  return _internal_has_num_iter();
}
inline void IlqrSolverDebugInfo::clear_num_iter() {
  num_iter_ = 0;
  _has_bits_[0] &= ~0x00000008u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 IlqrSolverDebugInfo::_internal_num_iter() const {
  return num_iter_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 IlqrSolverDebugInfo::num_iter() const {
  // @@protoc_insertion_point(field_get:deeproute.planning.IlqrSolverDebugInfo.num_iter)
  return _internal_num_iter();
}
inline void IlqrSolverDebugInfo::_internal_set_num_iter(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000008u;
  num_iter_ = value;
}
inline void IlqrSolverDebugInfo::set_num_iter(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_num_iter(value);
  // @@protoc_insertion_point(field_set:deeproute.planning.IlqrSolverDebugInfo.num_iter)
}

// optional bool success = 3 [default = false];
inline bool IlqrSolverDebugInfo::_internal_has_success() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool IlqrSolverDebugInfo::has_success() const {
  return _internal_has_success();
}
inline void IlqrSolverDebugInfo::clear_success() {
  success_ = false;
  _has_bits_[0] &= ~0x00000010u;
}
inline bool IlqrSolverDebugInfo::_internal_success() const {
  return success_;
}
inline bool IlqrSolverDebugInfo::success() const {
  // @@protoc_insertion_point(field_get:deeproute.planning.IlqrSolverDebugInfo.success)
  return _internal_success();
}
inline void IlqrSolverDebugInfo::_internal_set_success(bool value) {
  _has_bits_[0] |= 0x00000010u;
  success_ = value;
}
inline void IlqrSolverDebugInfo::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:deeproute.planning.IlqrSolverDebugInfo.success)
}

// optional .deeproute.planning.IlqrCostInfo init_cost = 4;
inline bool IlqrSolverDebugInfo::_internal_has_init_cost() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || init_cost_ != nullptr);
  return value;
}
inline bool IlqrSolverDebugInfo::has_init_cost() const {
  return _internal_has_init_cost();
}
inline void IlqrSolverDebugInfo::clear_init_cost() {
  if (init_cost_ != nullptr) init_cost_->Clear();
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::deeproute::planning::IlqrCostInfo& IlqrSolverDebugInfo::_internal_init_cost() const {
  const ::deeproute::planning::IlqrCostInfo* p = init_cost_;
  return p != nullptr ? *p : *reinterpret_cast<const ::deeproute::planning::IlqrCostInfo*>(
      &::deeproute::planning::_IlqrCostInfo_default_instance_);
}
inline const ::deeproute::planning::IlqrCostInfo& IlqrSolverDebugInfo::init_cost() const {
  // @@protoc_insertion_point(field_get:deeproute.planning.IlqrSolverDebugInfo.init_cost)
  return _internal_init_cost();
}
inline void IlqrSolverDebugInfo::unsafe_arena_set_allocated_init_cost(
    ::deeproute::planning::IlqrCostInfo* init_cost) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(init_cost_);
  }
  init_cost_ = init_cost;
  if (init_cost) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:deeproute.planning.IlqrSolverDebugInfo.init_cost)
}
inline ::deeproute::planning::IlqrCostInfo* IlqrSolverDebugInfo::release_init_cost() {
  _has_bits_[0] &= ~0x00000001u;
  ::deeproute::planning::IlqrCostInfo* temp = init_cost_;
  init_cost_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::deeproute::planning::IlqrCostInfo* IlqrSolverDebugInfo::unsafe_arena_release_init_cost() {
  // @@protoc_insertion_point(field_release:deeproute.planning.IlqrSolverDebugInfo.init_cost)
  _has_bits_[0] &= ~0x00000001u;
  ::deeproute::planning::IlqrCostInfo* temp = init_cost_;
  init_cost_ = nullptr;
  return temp;
}
inline ::deeproute::planning::IlqrCostInfo* IlqrSolverDebugInfo::_internal_mutable_init_cost() {
  _has_bits_[0] |= 0x00000001u;
  if (init_cost_ == nullptr) {
    auto* p = CreateMaybeMessage<::deeproute::planning::IlqrCostInfo>(GetArena());
    init_cost_ = p;
  }
  return init_cost_;
}
inline ::deeproute::planning::IlqrCostInfo* IlqrSolverDebugInfo::mutable_init_cost() {
  // @@protoc_insertion_point(field_mutable:deeproute.planning.IlqrSolverDebugInfo.init_cost)
  return _internal_mutable_init_cost();
}
inline void IlqrSolverDebugInfo::set_allocated_init_cost(::deeproute::planning::IlqrCostInfo* init_cost) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete init_cost_;
  }
  if (init_cost) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(init_cost);
    if (message_arena != submessage_arena) {
      init_cost = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, init_cost, submessage_arena);
    }
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  init_cost_ = init_cost;
  // @@protoc_insertion_point(field_set_allocated:deeproute.planning.IlqrSolverDebugInfo.init_cost)
}

// optional .deeproute.planning.IlqrCostInfo final_cost = 5;
inline bool IlqrSolverDebugInfo::_internal_has_final_cost() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || final_cost_ != nullptr);
  return value;
}
inline bool IlqrSolverDebugInfo::has_final_cost() const {
  return _internal_has_final_cost();
}
inline void IlqrSolverDebugInfo::clear_final_cost() {
  if (final_cost_ != nullptr) final_cost_->Clear();
  _has_bits_[0] &= ~0x00000002u;
}
inline const ::deeproute::planning::IlqrCostInfo& IlqrSolverDebugInfo::_internal_final_cost() const {
  const ::deeproute::planning::IlqrCostInfo* p = final_cost_;
  return p != nullptr ? *p : *reinterpret_cast<const ::deeproute::planning::IlqrCostInfo*>(
      &::deeproute::planning::_IlqrCostInfo_default_instance_);
}
inline const ::deeproute::planning::IlqrCostInfo& IlqrSolverDebugInfo::final_cost() const {
  // @@protoc_insertion_point(field_get:deeproute.planning.IlqrSolverDebugInfo.final_cost)
  return _internal_final_cost();
}
inline void IlqrSolverDebugInfo::unsafe_arena_set_allocated_final_cost(
    ::deeproute::planning::IlqrCostInfo* final_cost) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(final_cost_);
  }
  final_cost_ = final_cost;
  if (final_cost) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:deeproute.planning.IlqrSolverDebugInfo.final_cost)
}
inline ::deeproute::planning::IlqrCostInfo* IlqrSolverDebugInfo::release_final_cost() {
  _has_bits_[0] &= ~0x00000002u;
  ::deeproute::planning::IlqrCostInfo* temp = final_cost_;
  final_cost_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::deeproute::planning::IlqrCostInfo* IlqrSolverDebugInfo::unsafe_arena_release_final_cost() {
  // @@protoc_insertion_point(field_release:deeproute.planning.IlqrSolverDebugInfo.final_cost)
  _has_bits_[0] &= ~0x00000002u;
  ::deeproute::planning::IlqrCostInfo* temp = final_cost_;
  final_cost_ = nullptr;
  return temp;
}
inline ::deeproute::planning::IlqrCostInfo* IlqrSolverDebugInfo::_internal_mutable_final_cost() {
  _has_bits_[0] |= 0x00000002u;
  if (final_cost_ == nullptr) {
    auto* p = CreateMaybeMessage<::deeproute::planning::IlqrCostInfo>(GetArena());
    final_cost_ = p;
  }
  return final_cost_;
}
inline ::deeproute::planning::IlqrCostInfo* IlqrSolverDebugInfo::mutable_final_cost() {
  // @@protoc_insertion_point(field_mutable:deeproute.planning.IlqrSolverDebugInfo.final_cost)
  return _internal_mutable_final_cost();
}
inline void IlqrSolverDebugInfo::set_allocated_final_cost(::deeproute::planning::IlqrCostInfo* final_cost) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete final_cost_;
  }
  if (final_cost) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(final_cost);
    if (message_arena != submessage_arena) {
      final_cost = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, final_cost, submessage_arena);
    }
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  final_cost_ = final_cost;
  // @@protoc_insertion_point(field_set_allocated:deeproute.planning.IlqrSolverDebugInfo.final_cost)
}

// optional bool converged = 6 [default = false];
inline bool IlqrSolverDebugInfo::_internal_has_converged() const {
  bool value = (_has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline bool IlqrSolverDebugInfo::has_converged() const {
  return _internal_has_converged();
}
inline void IlqrSolverDebugInfo::clear_converged() {
  converged_ = false;
  _has_bits_[0] &= ~0x00000020u;
}
inline bool IlqrSolverDebugInfo::_internal_converged() const {
  return converged_;
}
inline bool IlqrSolverDebugInfo::converged() const {
  // @@protoc_insertion_point(field_get:deeproute.planning.IlqrSolverDebugInfo.converged)
  return _internal_converged();
}
inline void IlqrSolverDebugInfo::_internal_set_converged(bool value) {
  _has_bits_[0] |= 0x00000020u;
  converged_ = value;
}
inline void IlqrSolverDebugInfo::set_converged(bool value) {
  _internal_set_converged(value);
  // @@protoc_insertion_point(field_set:deeproute.planning.IlqrSolverDebugInfo.converged)
}

// -------------------------------------------------------------------

// IlqrComfortSoftCost

// optional double accel_soft_cost = 1 [default = 0];
inline bool IlqrComfortSoftCost::_internal_has_accel_soft_cost() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool IlqrComfortSoftCost::has_accel_soft_cost() const {
  return _internal_has_accel_soft_cost();
}
inline void IlqrComfortSoftCost::clear_accel_soft_cost() {
  accel_soft_cost_ = 0;
  _has_bits_[0] &= ~0x00000001u;
}
inline double IlqrComfortSoftCost::_internal_accel_soft_cost() const {
  return accel_soft_cost_;
}
inline double IlqrComfortSoftCost::accel_soft_cost() const {
  // @@protoc_insertion_point(field_get:deeproute.planning.IlqrComfortSoftCost.accel_soft_cost)
  return _internal_accel_soft_cost();
}
inline void IlqrComfortSoftCost::_internal_set_accel_soft_cost(double value) {
  _has_bits_[0] |= 0x00000001u;
  accel_soft_cost_ = value;
}
inline void IlqrComfortSoftCost::set_accel_soft_cost(double value) {
  _internal_set_accel_soft_cost(value);
  // @@protoc_insertion_point(field_set:deeproute.planning.IlqrComfortSoftCost.accel_soft_cost)
}

// optional double decel_soft_cost = 2 [default = 0];
inline bool IlqrComfortSoftCost::_internal_has_decel_soft_cost() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool IlqrComfortSoftCost::has_decel_soft_cost() const {
  return _internal_has_decel_soft_cost();
}
inline void IlqrComfortSoftCost::clear_decel_soft_cost() {
  decel_soft_cost_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline double IlqrComfortSoftCost::_internal_decel_soft_cost() const {
  return decel_soft_cost_;
}
inline double IlqrComfortSoftCost::decel_soft_cost() const {
  // @@protoc_insertion_point(field_get:deeproute.planning.IlqrComfortSoftCost.decel_soft_cost)
  return _internal_decel_soft_cost();
}
inline void IlqrComfortSoftCost::_internal_set_decel_soft_cost(double value) {
  _has_bits_[0] |= 0x00000002u;
  decel_soft_cost_ = value;
}
inline void IlqrComfortSoftCost::set_decel_soft_cost(double value) {
  _internal_set_decel_soft_cost(value);
  // @@protoc_insertion_point(field_set:deeproute.planning.IlqrComfortSoftCost.decel_soft_cost)
}

// optional double jerk_soft_cost = 3 [default = 0];
inline bool IlqrComfortSoftCost::_internal_has_jerk_soft_cost() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool IlqrComfortSoftCost::has_jerk_soft_cost() const {
  return _internal_has_jerk_soft_cost();
}
inline void IlqrComfortSoftCost::clear_jerk_soft_cost() {
  jerk_soft_cost_ = 0;
  _has_bits_[0] &= ~0x00000004u;
}
inline double IlqrComfortSoftCost::_internal_jerk_soft_cost() const {
  return jerk_soft_cost_;
}
inline double IlqrComfortSoftCost::jerk_soft_cost() const {
  // @@protoc_insertion_point(field_get:deeproute.planning.IlqrComfortSoftCost.jerk_soft_cost)
  return _internal_jerk_soft_cost();
}
inline void IlqrComfortSoftCost::_internal_set_jerk_soft_cost(double value) {
  _has_bits_[0] |= 0x00000004u;
  jerk_soft_cost_ = value;
}
inline void IlqrComfortSoftCost::set_jerk_soft_cost(double value) {
  _internal_set_jerk_soft_cost(value);
  // @@protoc_insertion_point(field_set:deeproute.planning.IlqrComfortSoftCost.jerk_soft_cost)
}

// optional double lat_accel_soft_cost = 4 [default = 0];
inline bool IlqrComfortSoftCost::_internal_has_lat_accel_soft_cost() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool IlqrComfortSoftCost::has_lat_accel_soft_cost() const {
  return _internal_has_lat_accel_soft_cost();
}
inline void IlqrComfortSoftCost::clear_lat_accel_soft_cost() {
  lat_accel_soft_cost_ = 0;
  _has_bits_[0] &= ~0x00000008u;
}
inline double IlqrComfortSoftCost::_internal_lat_accel_soft_cost() const {
  return lat_accel_soft_cost_;
}
inline double IlqrComfortSoftCost::lat_accel_soft_cost() const {
  // @@protoc_insertion_point(field_get:deeproute.planning.IlqrComfortSoftCost.lat_accel_soft_cost)
  return _internal_lat_accel_soft_cost();
}
inline void IlqrComfortSoftCost::_internal_set_lat_accel_soft_cost(double value) {
  _has_bits_[0] |= 0x00000008u;
  lat_accel_soft_cost_ = value;
}
inline void IlqrComfortSoftCost::set_lat_accel_soft_cost(double value) {
  _internal_set_lat_accel_soft_cost(value);
  // @@protoc_insertion_point(field_set:deeproute.planning.IlqrComfortSoftCost.lat_accel_soft_cost)
}

// optional double lat_jerk_soft_cost = 5 [default = 0];
inline bool IlqrComfortSoftCost::_internal_has_lat_jerk_soft_cost() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool IlqrComfortSoftCost::has_lat_jerk_soft_cost() const {
  return _internal_has_lat_jerk_soft_cost();
}
inline void IlqrComfortSoftCost::clear_lat_jerk_soft_cost() {
  lat_jerk_soft_cost_ = 0;
  _has_bits_[0] &= ~0x00000010u;
}
inline double IlqrComfortSoftCost::_internal_lat_jerk_soft_cost() const {
  return lat_jerk_soft_cost_;
}
inline double IlqrComfortSoftCost::lat_jerk_soft_cost() const {
  // @@protoc_insertion_point(field_get:deeproute.planning.IlqrComfortSoftCost.lat_jerk_soft_cost)
  return _internal_lat_jerk_soft_cost();
}
inline void IlqrComfortSoftCost::_internal_set_lat_jerk_soft_cost(double value) {
  _has_bits_[0] |= 0x00000010u;
  lat_jerk_soft_cost_ = value;
}
inline void IlqrComfortSoftCost::set_lat_jerk_soft_cost(double value) {
  _internal_set_lat_jerk_soft_cost(value);
  // @@protoc_insertion_point(field_set:deeproute.planning.IlqrComfortSoftCost.lat_jerk_soft_cost)
}

// optional double ddkappa_soft_cost = 6 [default = 0];
inline bool IlqrComfortSoftCost::_internal_has_ddkappa_soft_cost() const {
  bool value = (_has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline bool IlqrComfortSoftCost::has_ddkappa_soft_cost() const {
  return _internal_has_ddkappa_soft_cost();
}
inline void IlqrComfortSoftCost::clear_ddkappa_soft_cost() {
  ddkappa_soft_cost_ = 0;
  _has_bits_[0] &= ~0x00000020u;
}
inline double IlqrComfortSoftCost::_internal_ddkappa_soft_cost() const {
  return ddkappa_soft_cost_;
}
inline double IlqrComfortSoftCost::ddkappa_soft_cost() const {
  // @@protoc_insertion_point(field_get:deeproute.planning.IlqrComfortSoftCost.ddkappa_soft_cost)
  return _internal_ddkappa_soft_cost();
}
inline void IlqrComfortSoftCost::_internal_set_ddkappa_soft_cost(double value) {
  _has_bits_[0] |= 0x00000020u;
  ddkappa_soft_cost_ = value;
}
inline void IlqrComfortSoftCost::set_ddkappa_soft_cost(double value) {
  _internal_set_ddkappa_soft_cost(value);
  // @@protoc_insertion_point(field_set:deeproute.planning.IlqrComfortSoftCost.ddkappa_soft_cost)
}

// optional double decel_jerk_soft_cost = 7 [default = 0];
inline bool IlqrComfortSoftCost::_internal_has_decel_jerk_soft_cost() const {
  bool value = (_has_bits_[0] & 0x00000040u) != 0;
  return value;
}
inline bool IlqrComfortSoftCost::has_decel_jerk_soft_cost() const {
  return _internal_has_decel_jerk_soft_cost();
}
inline void IlqrComfortSoftCost::clear_decel_jerk_soft_cost() {
  decel_jerk_soft_cost_ = 0;
  _has_bits_[0] &= ~0x00000040u;
}
inline double IlqrComfortSoftCost::_internal_decel_jerk_soft_cost() const {
  return decel_jerk_soft_cost_;
}
inline double IlqrComfortSoftCost::decel_jerk_soft_cost() const {
  // @@protoc_insertion_point(field_get:deeproute.planning.IlqrComfortSoftCost.decel_jerk_soft_cost)
  return _internal_decel_jerk_soft_cost();
}
inline void IlqrComfortSoftCost::_internal_set_decel_jerk_soft_cost(double value) {
  _has_bits_[0] |= 0x00000040u;
  decel_jerk_soft_cost_ = value;
}
inline void IlqrComfortSoftCost::set_decel_jerk_soft_cost(double value) {
  _internal_set_decel_jerk_soft_cost(value);
  // @@protoc_insertion_point(field_set:deeproute.planning.IlqrComfortSoftCost.decel_jerk_soft_cost)
}

// -------------------------------------------------------------------

// IlqrComfortHardCost

// optional double vx_hard_cost = 1 [default = 0];
inline bool IlqrComfortHardCost::_internal_has_vx_hard_cost() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool IlqrComfortHardCost::has_vx_hard_cost() const {
  return _internal_has_vx_hard_cost();
}
inline void IlqrComfortHardCost::clear_vx_hard_cost() {
  vx_hard_cost_ = 0;
  _has_bits_[0] &= ~0x00000001u;
}
inline double IlqrComfortHardCost::_internal_vx_hard_cost() const {
  return vx_hard_cost_;
}
inline double IlqrComfortHardCost::vx_hard_cost() const {
  // @@protoc_insertion_point(field_get:deeproute.planning.IlqrComfortHardCost.vx_hard_cost)
  return _internal_vx_hard_cost();
}
inline void IlqrComfortHardCost::_internal_set_vx_hard_cost(double value) {
  _has_bits_[0] |= 0x00000001u;
  vx_hard_cost_ = value;
}
inline void IlqrComfortHardCost::set_vx_hard_cost(double value) {
  _internal_set_vx_hard_cost(value);
  // @@protoc_insertion_point(field_set:deeproute.planning.IlqrComfortHardCost.vx_hard_cost)
}

// optional double ax_hard_cost = 2 [default = 0];
inline bool IlqrComfortHardCost::_internal_has_ax_hard_cost() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool IlqrComfortHardCost::has_ax_hard_cost() const {
  return _internal_has_ax_hard_cost();
}
inline void IlqrComfortHardCost::clear_ax_hard_cost() {
  ax_hard_cost_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline double IlqrComfortHardCost::_internal_ax_hard_cost() const {
  return ax_hard_cost_;
}
inline double IlqrComfortHardCost::ax_hard_cost() const {
  // @@protoc_insertion_point(field_get:deeproute.planning.IlqrComfortHardCost.ax_hard_cost)
  return _internal_ax_hard_cost();
}
inline void IlqrComfortHardCost::_internal_set_ax_hard_cost(double value) {
  _has_bits_[0] |= 0x00000002u;
  ax_hard_cost_ = value;
}
inline void IlqrComfortHardCost::set_ax_hard_cost(double value) {
  _internal_set_ax_hard_cost(value);
  // @@protoc_insertion_point(field_set:deeproute.planning.IlqrComfortHardCost.ax_hard_cost)
}

// optional double ay_hard_cost = 3 [default = 0];
inline bool IlqrComfortHardCost::_internal_has_ay_hard_cost() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool IlqrComfortHardCost::has_ay_hard_cost() const {
  return _internal_has_ay_hard_cost();
}
inline void IlqrComfortHardCost::clear_ay_hard_cost() {
  ay_hard_cost_ = 0;
  _has_bits_[0] &= ~0x00000004u;
}
inline double IlqrComfortHardCost::_internal_ay_hard_cost() const {
  return ay_hard_cost_;
}
inline double IlqrComfortHardCost::ay_hard_cost() const {
  // @@protoc_insertion_point(field_get:deeproute.planning.IlqrComfortHardCost.ay_hard_cost)
  return _internal_ay_hard_cost();
}
inline void IlqrComfortHardCost::_internal_set_ay_hard_cost(double value) {
  _has_bits_[0] |= 0x00000004u;
  ay_hard_cost_ = value;
}
inline void IlqrComfortHardCost::set_ay_hard_cost(double value) {
  _internal_set_ay_hard_cost(value);
  // @@protoc_insertion_point(field_set:deeproute.planning.IlqrComfortHardCost.ay_hard_cost)
}

// optional double jx_hard_cost = 4 [default = 0];
inline bool IlqrComfortHardCost::_internal_has_jx_hard_cost() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool IlqrComfortHardCost::has_jx_hard_cost() const {
  return _internal_has_jx_hard_cost();
}
inline void IlqrComfortHardCost::clear_jx_hard_cost() {
  jx_hard_cost_ = 0;
  _has_bits_[0] &= ~0x00000008u;
}
inline double IlqrComfortHardCost::_internal_jx_hard_cost() const {
  return jx_hard_cost_;
}
inline double IlqrComfortHardCost::jx_hard_cost() const {
  // @@protoc_insertion_point(field_get:deeproute.planning.IlqrComfortHardCost.jx_hard_cost)
  return _internal_jx_hard_cost();
}
inline void IlqrComfortHardCost::_internal_set_jx_hard_cost(double value) {
  _has_bits_[0] |= 0x00000008u;
  jx_hard_cost_ = value;
}
inline void IlqrComfortHardCost::set_jx_hard_cost(double value) {
  _internal_set_jx_hard_cost(value);
  // @@protoc_insertion_point(field_set:deeproute.planning.IlqrComfortHardCost.jx_hard_cost)
}

// optional double jy_hard_cost = 5 [default = 0];
inline bool IlqrComfortHardCost::_internal_has_jy_hard_cost() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool IlqrComfortHardCost::has_jy_hard_cost() const {
  return _internal_has_jy_hard_cost();
}
inline void IlqrComfortHardCost::clear_jy_hard_cost() {
  jy_hard_cost_ = 0;
  _has_bits_[0] &= ~0x00000010u;
}
inline double IlqrComfortHardCost::_internal_jy_hard_cost() const {
  return jy_hard_cost_;
}
inline double IlqrComfortHardCost::jy_hard_cost() const {
  // @@protoc_insertion_point(field_get:deeproute.planning.IlqrComfortHardCost.jy_hard_cost)
  return _internal_jy_hard_cost();
}
inline void IlqrComfortHardCost::_internal_set_jy_hard_cost(double value) {
  _has_bits_[0] |= 0x00000010u;
  jy_hard_cost_ = value;
}
inline void IlqrComfortHardCost::set_jy_hard_cost(double value) {
  _internal_set_jy_hard_cost(value);
  // @@protoc_insertion_point(field_set:deeproute.planning.IlqrComfortHardCost.jy_hard_cost)
}

// optional double kappa_hard_cost = 6 [default = 0];
inline bool IlqrComfortHardCost::_internal_has_kappa_hard_cost() const {
  bool value = (_has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline bool IlqrComfortHardCost::has_kappa_hard_cost() const {
  return _internal_has_kappa_hard_cost();
}
inline void IlqrComfortHardCost::clear_kappa_hard_cost() {
  kappa_hard_cost_ = 0;
  _has_bits_[0] &= ~0x00000020u;
}
inline double IlqrComfortHardCost::_internal_kappa_hard_cost() const {
  return kappa_hard_cost_;
}
inline double IlqrComfortHardCost::kappa_hard_cost() const {
  // @@protoc_insertion_point(field_get:deeproute.planning.IlqrComfortHardCost.kappa_hard_cost)
  return _internal_kappa_hard_cost();
}
inline void IlqrComfortHardCost::_internal_set_kappa_hard_cost(double value) {
  _has_bits_[0] |= 0x00000020u;
  kappa_hard_cost_ = value;
}
inline void IlqrComfortHardCost::set_kappa_hard_cost(double value) {
  _internal_set_kappa_hard_cost(value);
  // @@protoc_insertion_point(field_set:deeproute.planning.IlqrComfortHardCost.kappa_hard_cost)
}

// optional double dkappa_hard_cost = 7 [default = 0];
inline bool IlqrComfortHardCost::_internal_has_dkappa_hard_cost() const {
  bool value = (_has_bits_[0] & 0x00000040u) != 0;
  return value;
}
inline bool IlqrComfortHardCost::has_dkappa_hard_cost() const {
  return _internal_has_dkappa_hard_cost();
}
inline void IlqrComfortHardCost::clear_dkappa_hard_cost() {
  dkappa_hard_cost_ = 0;
  _has_bits_[0] &= ~0x00000040u;
}
inline double IlqrComfortHardCost::_internal_dkappa_hard_cost() const {
  return dkappa_hard_cost_;
}
inline double IlqrComfortHardCost::dkappa_hard_cost() const {
  // @@protoc_insertion_point(field_get:deeproute.planning.IlqrComfortHardCost.dkappa_hard_cost)
  return _internal_dkappa_hard_cost();
}
inline void IlqrComfortHardCost::_internal_set_dkappa_hard_cost(double value) {
  _has_bits_[0] |= 0x00000040u;
  dkappa_hard_cost_ = value;
}
inline void IlqrComfortHardCost::set_dkappa_hard_cost(double value) {
  _internal_set_dkappa_hard_cost(value);
  // @@protoc_insertion_point(field_set:deeproute.planning.IlqrComfortHardCost.dkappa_hard_cost)
}

// optional double ddkappa_hard_cost = 8 [default = 0];
inline bool IlqrComfortHardCost::_internal_has_ddkappa_hard_cost() const {
  bool value = (_has_bits_[0] & 0x00000080u) != 0;
  return value;
}
inline bool IlqrComfortHardCost::has_ddkappa_hard_cost() const {
  return _internal_has_ddkappa_hard_cost();
}
inline void IlqrComfortHardCost::clear_ddkappa_hard_cost() {
  ddkappa_hard_cost_ = 0;
  _has_bits_[0] &= ~0x00000080u;
}
inline double IlqrComfortHardCost::_internal_ddkappa_hard_cost() const {
  return ddkappa_hard_cost_;
}
inline double IlqrComfortHardCost::ddkappa_hard_cost() const {
  // @@protoc_insertion_point(field_get:deeproute.planning.IlqrComfortHardCost.ddkappa_hard_cost)
  return _internal_ddkappa_hard_cost();
}
inline void IlqrComfortHardCost::_internal_set_ddkappa_hard_cost(double value) {
  _has_bits_[0] |= 0x00000080u;
  ddkappa_hard_cost_ = value;
}
inline void IlqrComfortHardCost::set_ddkappa_hard_cost(double value) {
  _internal_set_ddkappa_hard_cost(value);
  // @@protoc_insertion_point(field_set:deeproute.planning.IlqrComfortHardCost.ddkappa_hard_cost)
}

// -------------------------------------------------------------------

// IlqrCostInfo

// optional .deeproute.planning.IlqrComfortSoftCost comfort_soft_cost = 1;
inline bool IlqrCostInfo::_internal_has_comfort_soft_cost() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || comfort_soft_cost_ != nullptr);
  return value;
}
inline bool IlqrCostInfo::has_comfort_soft_cost() const {
  return _internal_has_comfort_soft_cost();
}
inline void IlqrCostInfo::clear_comfort_soft_cost() {
  if (comfort_soft_cost_ != nullptr) comfort_soft_cost_->Clear();
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::deeproute::planning::IlqrComfortSoftCost& IlqrCostInfo::_internal_comfort_soft_cost() const {
  const ::deeproute::planning::IlqrComfortSoftCost* p = comfort_soft_cost_;
  return p != nullptr ? *p : *reinterpret_cast<const ::deeproute::planning::IlqrComfortSoftCost*>(
      &::deeproute::planning::_IlqrComfortSoftCost_default_instance_);
}
inline const ::deeproute::planning::IlqrComfortSoftCost& IlqrCostInfo::comfort_soft_cost() const {
  // @@protoc_insertion_point(field_get:deeproute.planning.IlqrCostInfo.comfort_soft_cost)
  return _internal_comfort_soft_cost();
}
inline void IlqrCostInfo::unsafe_arena_set_allocated_comfort_soft_cost(
    ::deeproute::planning::IlqrComfortSoftCost* comfort_soft_cost) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(comfort_soft_cost_);
  }
  comfort_soft_cost_ = comfort_soft_cost;
  if (comfort_soft_cost) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:deeproute.planning.IlqrCostInfo.comfort_soft_cost)
}
inline ::deeproute::planning::IlqrComfortSoftCost* IlqrCostInfo::release_comfort_soft_cost() {
  _has_bits_[0] &= ~0x00000001u;
  ::deeproute::planning::IlqrComfortSoftCost* temp = comfort_soft_cost_;
  comfort_soft_cost_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::deeproute::planning::IlqrComfortSoftCost* IlqrCostInfo::unsafe_arena_release_comfort_soft_cost() {
  // @@protoc_insertion_point(field_release:deeproute.planning.IlqrCostInfo.comfort_soft_cost)
  _has_bits_[0] &= ~0x00000001u;
  ::deeproute::planning::IlqrComfortSoftCost* temp = comfort_soft_cost_;
  comfort_soft_cost_ = nullptr;
  return temp;
}
inline ::deeproute::planning::IlqrComfortSoftCost* IlqrCostInfo::_internal_mutable_comfort_soft_cost() {
  _has_bits_[0] |= 0x00000001u;
  if (comfort_soft_cost_ == nullptr) {
    auto* p = CreateMaybeMessage<::deeproute::planning::IlqrComfortSoftCost>(GetArena());
    comfort_soft_cost_ = p;
  }
  return comfort_soft_cost_;
}
inline ::deeproute::planning::IlqrComfortSoftCost* IlqrCostInfo::mutable_comfort_soft_cost() {
  // @@protoc_insertion_point(field_mutable:deeproute.planning.IlqrCostInfo.comfort_soft_cost)
  return _internal_mutable_comfort_soft_cost();
}
inline void IlqrCostInfo::set_allocated_comfort_soft_cost(::deeproute::planning::IlqrComfortSoftCost* comfort_soft_cost) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete comfort_soft_cost_;
  }
  if (comfort_soft_cost) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(comfort_soft_cost);
    if (message_arena != submessage_arena) {
      comfort_soft_cost = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, comfort_soft_cost, submessage_arena);
    }
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  comfort_soft_cost_ = comfort_soft_cost;
  // @@protoc_insertion_point(field_set_allocated:deeproute.planning.IlqrCostInfo.comfort_soft_cost)
}

// optional double static_object_soft_cost = 2 [default = 0];
inline bool IlqrCostInfo::_internal_has_static_object_soft_cost() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool IlqrCostInfo::has_static_object_soft_cost() const {
  return _internal_has_static_object_soft_cost();
}
inline void IlqrCostInfo::clear_static_object_soft_cost() {
  static_object_soft_cost_ = 0;
  _has_bits_[0] &= ~0x00000004u;
}
inline double IlqrCostInfo::_internal_static_object_soft_cost() const {
  return static_object_soft_cost_;
}
inline double IlqrCostInfo::static_object_soft_cost() const {
  // @@protoc_insertion_point(field_get:deeproute.planning.IlqrCostInfo.static_object_soft_cost)
  return _internal_static_object_soft_cost();
}
inline void IlqrCostInfo::_internal_set_static_object_soft_cost(double value) {
  _has_bits_[0] |= 0x00000004u;
  static_object_soft_cost_ = value;
}
inline void IlqrCostInfo::set_static_object_soft_cost(double value) {
  _internal_set_static_object_soft_cost(value);
  // @@protoc_insertion_point(field_set:deeproute.planning.IlqrCostInfo.static_object_soft_cost)
}

// optional double dynamic_object_soft_cost = 3 [default = 0];
inline bool IlqrCostInfo::_internal_has_dynamic_object_soft_cost() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool IlqrCostInfo::has_dynamic_object_soft_cost() const {
  return _internal_has_dynamic_object_soft_cost();
}
inline void IlqrCostInfo::clear_dynamic_object_soft_cost() {
  dynamic_object_soft_cost_ = 0;
  _has_bits_[0] &= ~0x00000008u;
}
inline double IlqrCostInfo::_internal_dynamic_object_soft_cost() const {
  return dynamic_object_soft_cost_;
}
inline double IlqrCostInfo::dynamic_object_soft_cost() const {
  // @@protoc_insertion_point(field_get:deeproute.planning.IlqrCostInfo.dynamic_object_soft_cost)
  return _internal_dynamic_object_soft_cost();
}
inline void IlqrCostInfo::_internal_set_dynamic_object_soft_cost(double value) {
  _has_bits_[0] |= 0x00000008u;
  dynamic_object_soft_cost_ = value;
}
inline void IlqrCostInfo::set_dynamic_object_soft_cost(double value) {
  _internal_set_dynamic_object_soft_cost(value);
  // @@protoc_insertion_point(field_set:deeproute.planning.IlqrCostInfo.dynamic_object_soft_cost)
}

// optional double traffic_rule_soft_cost = 4 [default = 0];
inline bool IlqrCostInfo::_internal_has_traffic_rule_soft_cost() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool IlqrCostInfo::has_traffic_rule_soft_cost() const {
  return _internal_has_traffic_rule_soft_cost();
}
inline void IlqrCostInfo::clear_traffic_rule_soft_cost() {
  traffic_rule_soft_cost_ = 0;
  _has_bits_[0] &= ~0x00000010u;
}
inline double IlqrCostInfo::_internal_traffic_rule_soft_cost() const {
  return traffic_rule_soft_cost_;
}
inline double IlqrCostInfo::traffic_rule_soft_cost() const {
  // @@protoc_insertion_point(field_get:deeproute.planning.IlqrCostInfo.traffic_rule_soft_cost)
  return _internal_traffic_rule_soft_cost();
}
inline void IlqrCostInfo::_internal_set_traffic_rule_soft_cost(double value) {
  _has_bits_[0] |= 0x00000010u;
  traffic_rule_soft_cost_ = value;
}
inline void IlqrCostInfo::set_traffic_rule_soft_cost(double value) {
  _internal_set_traffic_rule_soft_cost(value);
  // @@protoc_insertion_point(field_set:deeproute.planning.IlqrCostInfo.traffic_rule_soft_cost)
}

// optional double consistency_soft_cost = 5 [default = 0];
inline bool IlqrCostInfo::_internal_has_consistency_soft_cost() const {
  bool value = (_has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline bool IlqrCostInfo::has_consistency_soft_cost() const {
  return _internal_has_consistency_soft_cost();
}
inline void IlqrCostInfo::clear_consistency_soft_cost() {
  consistency_soft_cost_ = 0;
  _has_bits_[0] &= ~0x00000020u;
}
inline double IlqrCostInfo::_internal_consistency_soft_cost() const {
  return consistency_soft_cost_;
}
inline double IlqrCostInfo::consistency_soft_cost() const {
  // @@protoc_insertion_point(field_get:deeproute.planning.IlqrCostInfo.consistency_soft_cost)
  return _internal_consistency_soft_cost();
}
inline void IlqrCostInfo::_internal_set_consistency_soft_cost(double value) {
  _has_bits_[0] |= 0x00000020u;
  consistency_soft_cost_ = value;
}
inline void IlqrCostInfo::set_consistency_soft_cost(double value) {
  _internal_set_consistency_soft_cost(value);
  // @@protoc_insertion_point(field_set:deeproute.planning.IlqrCostInfo.consistency_soft_cost)
}

// optional .deeproute.planning.IlqrComfortHardCost comfort_hard_cost = 6;
inline bool IlqrCostInfo::_internal_has_comfort_hard_cost() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || comfort_hard_cost_ != nullptr);
  return value;
}
inline bool IlqrCostInfo::has_comfort_hard_cost() const {
  return _internal_has_comfort_hard_cost();
}
inline void IlqrCostInfo::clear_comfort_hard_cost() {
  if (comfort_hard_cost_ != nullptr) comfort_hard_cost_->Clear();
  _has_bits_[0] &= ~0x00000002u;
}
inline const ::deeproute::planning::IlqrComfortHardCost& IlqrCostInfo::_internal_comfort_hard_cost() const {
  const ::deeproute::planning::IlqrComfortHardCost* p = comfort_hard_cost_;
  return p != nullptr ? *p : *reinterpret_cast<const ::deeproute::planning::IlqrComfortHardCost*>(
      &::deeproute::planning::_IlqrComfortHardCost_default_instance_);
}
inline const ::deeproute::planning::IlqrComfortHardCost& IlqrCostInfo::comfort_hard_cost() const {
  // @@protoc_insertion_point(field_get:deeproute.planning.IlqrCostInfo.comfort_hard_cost)
  return _internal_comfort_hard_cost();
}
inline void IlqrCostInfo::unsafe_arena_set_allocated_comfort_hard_cost(
    ::deeproute::planning::IlqrComfortHardCost* comfort_hard_cost) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(comfort_hard_cost_);
  }
  comfort_hard_cost_ = comfort_hard_cost;
  if (comfort_hard_cost) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:deeproute.planning.IlqrCostInfo.comfort_hard_cost)
}
inline ::deeproute::planning::IlqrComfortHardCost* IlqrCostInfo::release_comfort_hard_cost() {
  _has_bits_[0] &= ~0x00000002u;
  ::deeproute::planning::IlqrComfortHardCost* temp = comfort_hard_cost_;
  comfort_hard_cost_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::deeproute::planning::IlqrComfortHardCost* IlqrCostInfo::unsafe_arena_release_comfort_hard_cost() {
  // @@protoc_insertion_point(field_release:deeproute.planning.IlqrCostInfo.comfort_hard_cost)
  _has_bits_[0] &= ~0x00000002u;
  ::deeproute::planning::IlqrComfortHardCost* temp = comfort_hard_cost_;
  comfort_hard_cost_ = nullptr;
  return temp;
}
inline ::deeproute::planning::IlqrComfortHardCost* IlqrCostInfo::_internal_mutable_comfort_hard_cost() {
  _has_bits_[0] |= 0x00000002u;
  if (comfort_hard_cost_ == nullptr) {
    auto* p = CreateMaybeMessage<::deeproute::planning::IlqrComfortHardCost>(GetArena());
    comfort_hard_cost_ = p;
  }
  return comfort_hard_cost_;
}
inline ::deeproute::planning::IlqrComfortHardCost* IlqrCostInfo::mutable_comfort_hard_cost() {
  // @@protoc_insertion_point(field_mutable:deeproute.planning.IlqrCostInfo.comfort_hard_cost)
  return _internal_mutable_comfort_hard_cost();
}
inline void IlqrCostInfo::set_allocated_comfort_hard_cost(::deeproute::planning::IlqrComfortHardCost* comfort_hard_cost) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete comfort_hard_cost_;
  }
  if (comfort_hard_cost) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(comfort_hard_cost);
    if (message_arena != submessage_arena) {
      comfort_hard_cost = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, comfort_hard_cost, submessage_arena);
    }
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  comfort_hard_cost_ = comfort_hard_cost;
  // @@protoc_insertion_point(field_set_allocated:deeproute.planning.IlqrCostInfo.comfort_hard_cost)
}

// optional double static_object_hard_cost = 7 [default = 0];
inline bool IlqrCostInfo::_internal_has_static_object_hard_cost() const {
  bool value = (_has_bits_[0] & 0x00000040u) != 0;
  return value;
}
inline bool IlqrCostInfo::has_static_object_hard_cost() const {
  return _internal_has_static_object_hard_cost();
}
inline void IlqrCostInfo::clear_static_object_hard_cost() {
  static_object_hard_cost_ = 0;
  _has_bits_[0] &= ~0x00000040u;
}
inline double IlqrCostInfo::_internal_static_object_hard_cost() const {
  return static_object_hard_cost_;
}
inline double IlqrCostInfo::static_object_hard_cost() const {
  // @@protoc_insertion_point(field_get:deeproute.planning.IlqrCostInfo.static_object_hard_cost)
  return _internal_static_object_hard_cost();
}
inline void IlqrCostInfo::_internal_set_static_object_hard_cost(double value) {
  _has_bits_[0] |= 0x00000040u;
  static_object_hard_cost_ = value;
}
inline void IlqrCostInfo::set_static_object_hard_cost(double value) {
  _internal_set_static_object_hard_cost(value);
  // @@protoc_insertion_point(field_set:deeproute.planning.IlqrCostInfo.static_object_hard_cost)
}

// optional double dynamic_object_hard_cost = 8 [default = 0];
inline bool IlqrCostInfo::_internal_has_dynamic_object_hard_cost() const {
  bool value = (_has_bits_[0] & 0x00000080u) != 0;
  return value;
}
inline bool IlqrCostInfo::has_dynamic_object_hard_cost() const {
  return _internal_has_dynamic_object_hard_cost();
}
inline void IlqrCostInfo::clear_dynamic_object_hard_cost() {
  dynamic_object_hard_cost_ = 0;
  _has_bits_[0] &= ~0x00000080u;
}
inline double IlqrCostInfo::_internal_dynamic_object_hard_cost() const {
  return dynamic_object_hard_cost_;
}
inline double IlqrCostInfo::dynamic_object_hard_cost() const {
  // @@protoc_insertion_point(field_get:deeproute.planning.IlqrCostInfo.dynamic_object_hard_cost)
  return _internal_dynamic_object_hard_cost();
}
inline void IlqrCostInfo::_internal_set_dynamic_object_hard_cost(double value) {
  _has_bits_[0] |= 0x00000080u;
  dynamic_object_hard_cost_ = value;
}
inline void IlqrCostInfo::set_dynamic_object_hard_cost(double value) {
  _internal_set_dynamic_object_hard_cost(value);
  // @@protoc_insertion_point(field_set:deeproute.planning.IlqrCostInfo.dynamic_object_hard_cost)
}

// optional double traffic_rule_hard_cost = 9 [default = 0];
inline bool IlqrCostInfo::_internal_has_traffic_rule_hard_cost() const {
  bool value = (_has_bits_[0] & 0x00000100u) != 0;
  return value;
}
inline bool IlqrCostInfo::has_traffic_rule_hard_cost() const {
  return _internal_has_traffic_rule_hard_cost();
}
inline void IlqrCostInfo::clear_traffic_rule_hard_cost() {
  traffic_rule_hard_cost_ = 0;
  _has_bits_[0] &= ~0x00000100u;
}
inline double IlqrCostInfo::_internal_traffic_rule_hard_cost() const {
  return traffic_rule_hard_cost_;
}
inline double IlqrCostInfo::traffic_rule_hard_cost() const {
  // @@protoc_insertion_point(field_get:deeproute.planning.IlqrCostInfo.traffic_rule_hard_cost)
  return _internal_traffic_rule_hard_cost();
}
inline void IlqrCostInfo::_internal_set_traffic_rule_hard_cost(double value) {
  _has_bits_[0] |= 0x00000100u;
  traffic_rule_hard_cost_ = value;
}
inline void IlqrCostInfo::set_traffic_rule_hard_cost(double value) {
  _internal_set_traffic_rule_hard_cost(value);
  // @@protoc_insertion_point(field_set:deeproute.planning.IlqrCostInfo.traffic_rule_hard_cost)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace planning
}  // namespace deeproute

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_offboard_2fplanning_2filqr_5fsolver_5fdebug_5finfo_2eproto
