# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: drivers/mcu_log.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'drivers/mcu_log.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x64rivers/mcu_log.proto\x12\x11\x64\x65\x65proute.drivers\"e\n\x06McuLog\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12\'\n\x05level\x18\x02 \x01(\x0e\x32\x18.deeproute.drivers.Level\x12\x0e\n\x06length\x18\x03 \x01(\r\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\x0c*&\n\x05Level\x12\x08\n\x04INFO\x10\x00\x12\x08\n\x04WARN\x10\x01\x12\t\n\x05\x45RROR\x10\x02')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'drivers.mcu_log_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LEVEL']._serialized_start=147
  _globals['_LEVEL']._serialized_end=185
  _globals['_MCULOG']._serialized_start=44
  _globals['_MCULOG']._serialized_end=145
# @@protoc_insertion_point(module_scope)
