# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: remote_takeover/emergency_stop.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'remote_takeover/emergency_stop.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$remote_takeover/emergency_stop.proto\x12\x19\x64\x65\x65proute.remote_takeover\"\xbb\x01\n\rEmergencyStop\x12?\n\x06status\x18\x01 \x01(\x0e\x32/.deeproute.remote_takeover.EmergencyStop.Status\"i\n\x06Status\x12\x15\n\x11\x45MERGENCY_INVALID\x10\x00\x12\x18\n\x14\x45MERGENCY_STOP_FORCE\x10\x01\x12\x12\n\x0e\x45MERGENCY_STOP\x10\x02\x12\x1a\n\x16\x45MERGENCY_STOP_RELEASE\x10\x03')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'remote_takeover.emergency_stop_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMERGENCYSTOP']._serialized_start=68
  _globals['_EMERGENCYSTOP']._serialized_end=255
  _globals['_EMERGENCYSTOP_STATUS']._serialized_start=150
  _globals['_EMERGENCYSTOP_STATUS']._serialized_end=255
# @@protoc_insertion_point(module_scope)
