# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vhr/event_extra_info.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='vhr/event_extra_info.proto',
  package='dr.vhr',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x1avhr/event_extra_info.proto\x12\x06\x64r.vhr\"H\n\x0e\x45ventExtraInfo\x12\x0f\n\x07\x61\x64_code\x18\x01 \x01(\x04\x12\x12\n\nroad_class\x18\x02 \x01(\x05\x12\x11\n\troad_type\x18\x03 \x01(\x05')
)




_EVENTEXTRAINFO = _descriptor.Descriptor(
  name='EventExtraInfo',
  full_name='dr.vhr.EventExtraInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ad_code', full_name='dr.vhr.EventExtraInfo.ad_code', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='road_class', full_name='dr.vhr.EventExtraInfo.road_class', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='road_type', full_name='dr.vhr.EventExtraInfo.road_type', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=110,
)

DESCRIPTOR.message_types_by_name['EventExtraInfo'] = _EVENTEXTRAINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EventExtraInfo = _reflection.GeneratedProtocolMessageType('EventExtraInfo', (_message.Message,), dict(
  DESCRIPTOR = _EVENTEXTRAINFO,
  __module__ = 'vhr.event_extra_info_pb2'
  # @@protoc_insertion_point(class_scope:dr.vhr.EventExtraInfo)
  ))
_sym_db.RegisterMessage(EventExtraInfo)


# @@protoc_insertion_point(module_scope)
