// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dta/dta_onboard.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_dta_2fdta_5fonboard_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_dta_2fdta_5fonboard_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3013000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3013000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_dta_2fdta_5fonboard_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_dta_2fdta_5fonboard_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[6]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_dta_2fdta_5fonboard_2eproto;
namespace dr {
namespace dta {
namespace onboard {
class DrivingTrajectory;
class DrivingTrajectoryDefaultTypeInternal;
extern DrivingTrajectoryDefaultTypeInternal _DrivingTrajectory_default_instance_;
class DtaOnboard;
class DtaOnboardDefaultTypeInternal;
extern DtaOnboardDefaultTypeInternal _DtaOnboard_default_instance_;
class GradingInfo;
class GradingInfoDefaultTypeInternal;
extern GradingInfoDefaultTypeInternal _GradingInfo_default_instance_;
class PerformanceMetrics;
class PerformanceMetricsDefaultTypeInternal;
extern PerformanceMetricsDefaultTypeInternal _PerformanceMetrics_default_instance_;
class Point;
class PointDefaultTypeInternal;
extern PointDefaultTypeInternal _Point_default_instance_;
class SingleTripDriving;
class SingleTripDrivingDefaultTypeInternal;
extern SingleTripDrivingDefaultTypeInternal _SingleTripDriving_default_instance_;
}  // namespace onboard
}  // namespace dta
}  // namespace dr
PROTOBUF_NAMESPACE_OPEN
template<> ::dr::dta::onboard::DrivingTrajectory* Arena::CreateMaybeMessage<::dr::dta::onboard::DrivingTrajectory>(Arena*);
template<> ::dr::dta::onboard::DtaOnboard* Arena::CreateMaybeMessage<::dr::dta::onboard::DtaOnboard>(Arena*);
template<> ::dr::dta::onboard::GradingInfo* Arena::CreateMaybeMessage<::dr::dta::onboard::GradingInfo>(Arena*);
template<> ::dr::dta::onboard::PerformanceMetrics* Arena::CreateMaybeMessage<::dr::dta::onboard::PerformanceMetrics>(Arena*);
template<> ::dr::dta::onboard::Point* Arena::CreateMaybeMessage<::dr::dta::onboard::Point>(Arena*);
template<> ::dr::dta::onboard::SingleTripDriving* Arena::CreateMaybeMessage<::dr::dta::onboard::SingleTripDriving>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace dr {
namespace dta {
namespace onboard {

enum GradingInfo_GradingEvent : int {
  GradingInfo_GradingEvent_UNKNOWN = 0,
  GradingInfo_GradingEvent_PASS_JUNCTION_SUCCESS = 1,
  GradingInfo_GradingEvent_PASS_JUNCTION_FAIL = 2,
  GradingInfo_GradingEvent_LANE_CHANGE_SUCCESS = 3,
  GradingInfo_GradingEvent_LANE_CHANGE_FAIL = 4,
  GradingInfo_GradingEvent_INBOUND_OR_OUTBOUND_RAMP_SUCCESS = 5,
  GradingInfo_GradingEvent_INBOUND_OR_OUTBOUND_RAMP_FAIL = 6,
  GradingInfo_GradingEvent_DETOUR_SUCCESS = 7,
  GradingInfo_GradingEvent_DETOUR_FAIL = 8,
  GradingInfo_GradingEvent_YIELD_VRU_SUCCESS = 9,
  GradingInfo_GradingEvent_YIELD_VRU_FAIL = 10,
  GradingInfo_GradingEvent_CUT_IN_SUCCESS = 11,
  GradingInfo_GradingEvent_CUT_IN_FAIL = 12,
  GradingInfo_GradingEvent_PASS_ROUNDABOUT_SUCCESS = 13,
  GradingInfo_GradingEvent_PASS_ROUNDABOUT_FAIL = 14,
  GradingInfo_GradingEvent_PASS_U_TURN_SUCCESS = 15,
  GradingInfo_GradingEvent_PASS_U_TURN_FAIL = 16,
  GradingInfo_GradingEvent_GradingInfo_GradingEvent_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  GradingInfo_GradingEvent_GradingInfo_GradingEvent_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool GradingInfo_GradingEvent_IsValid(int value);
constexpr GradingInfo_GradingEvent GradingInfo_GradingEvent_GradingEvent_MIN = GradingInfo_GradingEvent_UNKNOWN;
constexpr GradingInfo_GradingEvent GradingInfo_GradingEvent_GradingEvent_MAX = GradingInfo_GradingEvent_PASS_U_TURN_FAIL;
constexpr int GradingInfo_GradingEvent_GradingEvent_ARRAYSIZE = GradingInfo_GradingEvent_GradingEvent_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* GradingInfo_GradingEvent_descriptor();
template<typename T>
inline const std::string& GradingInfo_GradingEvent_Name(T enum_t_value) {
  static_assert(::std::is_same<T, GradingInfo_GradingEvent>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function GradingInfo_GradingEvent_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    GradingInfo_GradingEvent_descriptor(), enum_t_value);
}
inline bool GradingInfo_GradingEvent_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, GradingInfo_GradingEvent* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<GradingInfo_GradingEvent>(
    GradingInfo_GradingEvent_descriptor(), name, value);
}
// ===================================================================

class DtaOnboard PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:dr.dta.onboard.DtaOnboard) */ {
 public:
  inline DtaOnboard() : DtaOnboard(nullptr) {}
  virtual ~DtaOnboard();

  DtaOnboard(const DtaOnboard& from);
  DtaOnboard(DtaOnboard&& from) noexcept
    : DtaOnboard() {
    *this = ::std::move(from);
  }

  inline DtaOnboard& operator=(const DtaOnboard& from) {
    CopyFrom(from);
    return *this;
  }
  inline DtaOnboard& operator=(DtaOnboard&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const DtaOnboard& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DtaOnboard* internal_default_instance() {
    return reinterpret_cast<const DtaOnboard*>(
               &_DtaOnboard_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(DtaOnboard& a, DtaOnboard& b) {
    a.Swap(&b);
  }
  inline void Swap(DtaOnboard* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DtaOnboard* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline DtaOnboard* New() const final {
    return CreateMaybeMessage<DtaOnboard>(nullptr);
  }

  DtaOnboard* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<DtaOnboard>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const DtaOnboard& from);
  void MergeFrom(const DtaOnboard& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DtaOnboard* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "dr.dta.onboard.DtaOnboard";
  }
  protected:
  explicit DtaOnboard(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_dta_2fdta_5fonboard_2eproto);
    return ::descriptor_table_dta_2fdta_5fonboard_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSingleTripDrivingFieldNumber = 1,
  };
  // .dr.dta.onboard.SingleTripDriving single_trip_driving = 1;
  bool has_single_trip_driving() const;
  private:
  bool _internal_has_single_trip_driving() const;
  public:
  void clear_single_trip_driving();
  const ::dr::dta::onboard::SingleTripDriving& single_trip_driving() const;
  ::dr::dta::onboard::SingleTripDriving* release_single_trip_driving();
  ::dr::dta::onboard::SingleTripDriving* mutable_single_trip_driving();
  void set_allocated_single_trip_driving(::dr::dta::onboard::SingleTripDriving* single_trip_driving);
  private:
  const ::dr::dta::onboard::SingleTripDriving& _internal_single_trip_driving() const;
  ::dr::dta::onboard::SingleTripDriving* _internal_mutable_single_trip_driving();
  public:
  void unsafe_arena_set_allocated_single_trip_driving(
      ::dr::dta::onboard::SingleTripDriving* single_trip_driving);
  ::dr::dta::onboard::SingleTripDriving* unsafe_arena_release_single_trip_driving();

  // @@protoc_insertion_point(class_scope:dr.dta.onboard.DtaOnboard)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::dr::dta::onboard::SingleTripDriving* single_trip_driving_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_dta_2fdta_5fonboard_2eproto;
};
// -------------------------------------------------------------------

class SingleTripDriving PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:dr.dta.onboard.SingleTripDriving) */ {
 public:
  inline SingleTripDriving() : SingleTripDriving(nullptr) {}
  virtual ~SingleTripDriving();

  SingleTripDriving(const SingleTripDriving& from);
  SingleTripDriving(SingleTripDriving&& from) noexcept
    : SingleTripDriving() {
    *this = ::std::move(from);
  }

  inline SingleTripDriving& operator=(const SingleTripDriving& from) {
    CopyFrom(from);
    return *this;
  }
  inline SingleTripDriving& operator=(SingleTripDriving&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const SingleTripDriving& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SingleTripDriving* internal_default_instance() {
    return reinterpret_cast<const SingleTripDriving*>(
               &_SingleTripDriving_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(SingleTripDriving& a, SingleTripDriving& b) {
    a.Swap(&b);
  }
  inline void Swap(SingleTripDriving* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SingleTripDriving* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline SingleTripDriving* New() const final {
    return CreateMaybeMessage<SingleTripDriving>(nullptr);
  }

  SingleTripDriving* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<SingleTripDriving>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const SingleTripDriving& from);
  void MergeFrom(const SingleTripDriving& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SingleTripDriving* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "dr.dta.onboard.SingleTripDriving";
  }
  protected:
  explicit SingleTripDriving(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_dta_2fdta_5fonboard_2eproto);
    return ::descriptor_table_dta_2fdta_5fonboard_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNavIdFieldNumber = 1,
    kPerformanceMetricsFieldNumber = 10,
    kDrivingTrajectoryFieldNumber = 11,
    kTotalDistanceFieldNumber = 2,
    kNoaDistanceFieldNumber = 3,
    kLccDistanceFieldNumber = 4,
    kAccDistanceFieldNumber = 5,
    kTotalTimeFieldNumber = 6,
    kNoaTimeFieldNumber = 7,
    kLccTimeFieldNumber = 8,
    kAccTimeFieldNumber = 9,
  };
  // string nav_id = 1;
  void clear_nav_id();
  const std::string& nav_id() const;
  void set_nav_id(const std::string& value);
  void set_nav_id(std::string&& value);
  void set_nav_id(const char* value);
  void set_nav_id(const char* value, size_t size);
  std::string* mutable_nav_id();
  std::string* release_nav_id();
  void set_allocated_nav_id(std::string* nav_id);
  private:
  const std::string& _internal_nav_id() const;
  void _internal_set_nav_id(const std::string& value);
  std::string* _internal_mutable_nav_id();
  public:

  // .dr.dta.onboard.PerformanceMetrics performance_metrics = 10;
  bool has_performance_metrics() const;
  private:
  bool _internal_has_performance_metrics() const;
  public:
  void clear_performance_metrics();
  const ::dr::dta::onboard::PerformanceMetrics& performance_metrics() const;
  ::dr::dta::onboard::PerformanceMetrics* release_performance_metrics();
  ::dr::dta::onboard::PerformanceMetrics* mutable_performance_metrics();
  void set_allocated_performance_metrics(::dr::dta::onboard::PerformanceMetrics* performance_metrics);
  private:
  const ::dr::dta::onboard::PerformanceMetrics& _internal_performance_metrics() const;
  ::dr::dta::onboard::PerformanceMetrics* _internal_mutable_performance_metrics();
  public:
  void unsafe_arena_set_allocated_performance_metrics(
      ::dr::dta::onboard::PerformanceMetrics* performance_metrics);
  ::dr::dta::onboard::PerformanceMetrics* unsafe_arena_release_performance_metrics();

  // .dr.dta.onboard.DrivingTrajectory driving_trajectory = 11;
  bool has_driving_trajectory() const;
  private:
  bool _internal_has_driving_trajectory() const;
  public:
  void clear_driving_trajectory();
  const ::dr::dta::onboard::DrivingTrajectory& driving_trajectory() const;
  ::dr::dta::onboard::DrivingTrajectory* release_driving_trajectory();
  ::dr::dta::onboard::DrivingTrajectory* mutable_driving_trajectory();
  void set_allocated_driving_trajectory(::dr::dta::onboard::DrivingTrajectory* driving_trajectory);
  private:
  const ::dr::dta::onboard::DrivingTrajectory& _internal_driving_trajectory() const;
  ::dr::dta::onboard::DrivingTrajectory* _internal_mutable_driving_trajectory();
  public:
  void unsafe_arena_set_allocated_driving_trajectory(
      ::dr::dta::onboard::DrivingTrajectory* driving_trajectory);
  ::dr::dta::onboard::DrivingTrajectory* unsafe_arena_release_driving_trajectory();

  // double total_distance = 2;
  void clear_total_distance();
  double total_distance() const;
  void set_total_distance(double value);
  private:
  double _internal_total_distance() const;
  void _internal_set_total_distance(double value);
  public:

  // double noa_distance = 3;
  void clear_noa_distance();
  double noa_distance() const;
  void set_noa_distance(double value);
  private:
  double _internal_noa_distance() const;
  void _internal_set_noa_distance(double value);
  public:

  // double lcc_distance = 4;
  void clear_lcc_distance();
  double lcc_distance() const;
  void set_lcc_distance(double value);
  private:
  double _internal_lcc_distance() const;
  void _internal_set_lcc_distance(double value);
  public:

  // double acc_distance = 5;
  void clear_acc_distance();
  double acc_distance() const;
  void set_acc_distance(double value);
  private:
  double _internal_acc_distance() const;
  void _internal_set_acc_distance(double value);
  public:

  // uint64 total_time = 6;
  void clear_total_time();
  ::PROTOBUF_NAMESPACE_ID::uint64 total_time() const;
  void set_total_time(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_total_time() const;
  void _internal_set_total_time(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint64 noa_time = 7;
  void clear_noa_time();
  ::PROTOBUF_NAMESPACE_ID::uint64 noa_time() const;
  void set_noa_time(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_noa_time() const;
  void _internal_set_noa_time(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint64 lcc_time = 8;
  void clear_lcc_time();
  ::PROTOBUF_NAMESPACE_ID::uint64 lcc_time() const;
  void set_lcc_time(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_lcc_time() const;
  void _internal_set_lcc_time(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint64 acc_time = 9;
  void clear_acc_time();
  ::PROTOBUF_NAMESPACE_ID::uint64 acc_time() const;
  void set_acc_time(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_acc_time() const;
  void _internal_set_acc_time(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // @@protoc_insertion_point(class_scope:dr.dta.onboard.SingleTripDriving)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr nav_id_;
  ::dr::dta::onboard::PerformanceMetrics* performance_metrics_;
  ::dr::dta::onboard::DrivingTrajectory* driving_trajectory_;
  double total_distance_;
  double noa_distance_;
  double lcc_distance_;
  double acc_distance_;
  ::PROTOBUF_NAMESPACE_ID::uint64 total_time_;
  ::PROTOBUF_NAMESPACE_ID::uint64 noa_time_;
  ::PROTOBUF_NAMESPACE_ID::uint64 lcc_time_;
  ::PROTOBUF_NAMESPACE_ID::uint64 acc_time_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_dta_2fdta_5fonboard_2eproto;
};
// -------------------------------------------------------------------

class PerformanceMetrics PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:dr.dta.onboard.PerformanceMetrics) */ {
 public:
  inline PerformanceMetrics() : PerformanceMetrics(nullptr) {}
  virtual ~PerformanceMetrics();

  PerformanceMetrics(const PerformanceMetrics& from);
  PerformanceMetrics(PerformanceMetrics&& from) noexcept
    : PerformanceMetrics() {
    *this = ::std::move(from);
  }

  inline PerformanceMetrics& operator=(const PerformanceMetrics& from) {
    CopyFrom(from);
    return *this;
  }
  inline PerformanceMetrics& operator=(PerformanceMetrics&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const PerformanceMetrics& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PerformanceMetrics* internal_default_instance() {
    return reinterpret_cast<const PerformanceMetrics*>(
               &_PerformanceMetrics_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(PerformanceMetrics& a, PerformanceMetrics& b) {
    a.Swap(&b);
  }
  inline void Swap(PerformanceMetrics* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PerformanceMetrics* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PerformanceMetrics* New() const final {
    return CreateMaybeMessage<PerformanceMetrics>(nullptr);
  }

  PerformanceMetrics* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PerformanceMetrics>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const PerformanceMetrics& from);
  void MergeFrom(const PerformanceMetrics& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PerformanceMetrics* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "dr.dta.onboard.PerformanceMetrics";
  }
  protected:
  explicit PerformanceMetrics(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_dta_2fdta_5fonboard_2eproto);
    return ::descriptor_table_dta_2fdta_5fonboard_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kGradingInfoFieldNumber = 1,
  };
  // repeated .dr.dta.onboard.GradingInfo grading_info = 1;
  int grading_info_size() const;
  private:
  int _internal_grading_info_size() const;
  public:
  void clear_grading_info();
  ::dr::dta::onboard::GradingInfo* mutable_grading_info(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::dr::dta::onboard::GradingInfo >*
      mutable_grading_info();
  private:
  const ::dr::dta::onboard::GradingInfo& _internal_grading_info(int index) const;
  ::dr::dta::onboard::GradingInfo* _internal_add_grading_info();
  public:
  const ::dr::dta::onboard::GradingInfo& grading_info(int index) const;
  ::dr::dta::onboard::GradingInfo* add_grading_info();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::dr::dta::onboard::GradingInfo >&
      grading_info() const;

  // @@protoc_insertion_point(class_scope:dr.dta.onboard.PerformanceMetrics)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::dr::dta::onboard::GradingInfo > grading_info_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_dta_2fdta_5fonboard_2eproto;
};
// -------------------------------------------------------------------

class GradingInfo PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:dr.dta.onboard.GradingInfo) */ {
 public:
  inline GradingInfo() : GradingInfo(nullptr) {}
  virtual ~GradingInfo();

  GradingInfo(const GradingInfo& from);
  GradingInfo(GradingInfo&& from) noexcept
    : GradingInfo() {
    *this = ::std::move(from);
  }

  inline GradingInfo& operator=(const GradingInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline GradingInfo& operator=(GradingInfo&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const GradingInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GradingInfo* internal_default_instance() {
    return reinterpret_cast<const GradingInfo*>(
               &_GradingInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(GradingInfo& a, GradingInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(GradingInfo* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GradingInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline GradingInfo* New() const final {
    return CreateMaybeMessage<GradingInfo>(nullptr);
  }

  GradingInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<GradingInfo>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const GradingInfo& from);
  void MergeFrom(const GradingInfo& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GradingInfo* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "dr.dta.onboard.GradingInfo";
  }
  protected:
  explicit GradingInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_dta_2fdta_5fonboard_2eproto);
    return ::descriptor_table_dta_2fdta_5fonboard_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef GradingInfo_GradingEvent GradingEvent;
  static constexpr GradingEvent UNKNOWN =
    GradingInfo_GradingEvent_UNKNOWN;
  static constexpr GradingEvent PASS_JUNCTION_SUCCESS =
    GradingInfo_GradingEvent_PASS_JUNCTION_SUCCESS;
  static constexpr GradingEvent PASS_JUNCTION_FAIL =
    GradingInfo_GradingEvent_PASS_JUNCTION_FAIL;
  static constexpr GradingEvent LANE_CHANGE_SUCCESS =
    GradingInfo_GradingEvent_LANE_CHANGE_SUCCESS;
  static constexpr GradingEvent LANE_CHANGE_FAIL =
    GradingInfo_GradingEvent_LANE_CHANGE_FAIL;
  static constexpr GradingEvent INBOUND_OR_OUTBOUND_RAMP_SUCCESS =
    GradingInfo_GradingEvent_INBOUND_OR_OUTBOUND_RAMP_SUCCESS;
  static constexpr GradingEvent INBOUND_OR_OUTBOUND_RAMP_FAIL =
    GradingInfo_GradingEvent_INBOUND_OR_OUTBOUND_RAMP_FAIL;
  static constexpr GradingEvent DETOUR_SUCCESS =
    GradingInfo_GradingEvent_DETOUR_SUCCESS;
  static constexpr GradingEvent DETOUR_FAIL =
    GradingInfo_GradingEvent_DETOUR_FAIL;
  static constexpr GradingEvent YIELD_VRU_SUCCESS =
    GradingInfo_GradingEvent_YIELD_VRU_SUCCESS;
  static constexpr GradingEvent YIELD_VRU_FAIL =
    GradingInfo_GradingEvent_YIELD_VRU_FAIL;
  static constexpr GradingEvent CUT_IN_SUCCESS =
    GradingInfo_GradingEvent_CUT_IN_SUCCESS;
  static constexpr GradingEvent CUT_IN_FAIL =
    GradingInfo_GradingEvent_CUT_IN_FAIL;
  static constexpr GradingEvent PASS_ROUNDABOUT_SUCCESS =
    GradingInfo_GradingEvent_PASS_ROUNDABOUT_SUCCESS;
  static constexpr GradingEvent PASS_ROUNDABOUT_FAIL =
    GradingInfo_GradingEvent_PASS_ROUNDABOUT_FAIL;
  static constexpr GradingEvent PASS_U_TURN_SUCCESS =
    GradingInfo_GradingEvent_PASS_U_TURN_SUCCESS;
  static constexpr GradingEvent PASS_U_TURN_FAIL =
    GradingInfo_GradingEvent_PASS_U_TURN_FAIL;
  static inline bool GradingEvent_IsValid(int value) {
    return GradingInfo_GradingEvent_IsValid(value);
  }
  static constexpr GradingEvent GradingEvent_MIN =
    GradingInfo_GradingEvent_GradingEvent_MIN;
  static constexpr GradingEvent GradingEvent_MAX =
    GradingInfo_GradingEvent_GradingEvent_MAX;
  static constexpr int GradingEvent_ARRAYSIZE =
    GradingInfo_GradingEvent_GradingEvent_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  GradingEvent_descriptor() {
    return GradingInfo_GradingEvent_descriptor();
  }
  template<typename T>
  static inline const std::string& GradingEvent_Name(T enum_t_value) {
    static_assert(::std::is_same<T, GradingEvent>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function GradingEvent_Name.");
    return GradingInfo_GradingEvent_Name(enum_t_value);
  }
  static inline bool GradingEvent_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      GradingEvent* value) {
    return GradingInfo_GradingEvent_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kGradingEventFieldNumber = 1,
    kTimesFieldNumber = 2,
  };
  // .dr.dta.onboard.GradingInfo.GradingEvent grading_event = 1;
  void clear_grading_event();
  ::dr::dta::onboard::GradingInfo_GradingEvent grading_event() const;
  void set_grading_event(::dr::dta::onboard::GradingInfo_GradingEvent value);
  private:
  ::dr::dta::onboard::GradingInfo_GradingEvent _internal_grading_event() const;
  void _internal_set_grading_event(::dr::dta::onboard::GradingInfo_GradingEvent value);
  public:

  // uint32 times = 2;
  void clear_times();
  ::PROTOBUF_NAMESPACE_ID::uint32 times() const;
  void set_times(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_times() const;
  void _internal_set_times(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:dr.dta.onboard.GradingInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  int grading_event_;
  ::PROTOBUF_NAMESPACE_ID::uint32 times_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_dta_2fdta_5fonboard_2eproto;
};
// -------------------------------------------------------------------

class DrivingTrajectory PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:dr.dta.onboard.DrivingTrajectory) */ {
 public:
  inline DrivingTrajectory() : DrivingTrajectory(nullptr) {}
  virtual ~DrivingTrajectory();

  DrivingTrajectory(const DrivingTrajectory& from);
  DrivingTrajectory(DrivingTrajectory&& from) noexcept
    : DrivingTrajectory() {
    *this = ::std::move(from);
  }

  inline DrivingTrajectory& operator=(const DrivingTrajectory& from) {
    CopyFrom(from);
    return *this;
  }
  inline DrivingTrajectory& operator=(DrivingTrajectory&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const DrivingTrajectory& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DrivingTrajectory* internal_default_instance() {
    return reinterpret_cast<const DrivingTrajectory*>(
               &_DrivingTrajectory_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(DrivingTrajectory& a, DrivingTrajectory& b) {
    a.Swap(&b);
  }
  inline void Swap(DrivingTrajectory* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DrivingTrajectory* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline DrivingTrajectory* New() const final {
    return CreateMaybeMessage<DrivingTrajectory>(nullptr);
  }

  DrivingTrajectory* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<DrivingTrajectory>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const DrivingTrajectory& from);
  void MergeFrom(const DrivingTrajectory& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DrivingTrajectory* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "dr.dta.onboard.DrivingTrajectory";
  }
  protected:
  explicit DrivingTrajectory(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_dta_2fdta_5fonboard_2eproto);
    return ::descriptor_table_dta_2fdta_5fonboard_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPointFieldNumber = 1,
  };
  // repeated .dr.dta.onboard.Point point = 1;
  int point_size() const;
  private:
  int _internal_point_size() const;
  public:
  void clear_point();
  ::dr::dta::onboard::Point* mutable_point(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::dr::dta::onboard::Point >*
      mutable_point();
  private:
  const ::dr::dta::onboard::Point& _internal_point(int index) const;
  ::dr::dta::onboard::Point* _internal_add_point();
  public:
  const ::dr::dta::onboard::Point& point(int index) const;
  ::dr::dta::onboard::Point* add_point();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::dr::dta::onboard::Point >&
      point() const;

  // @@protoc_insertion_point(class_scope:dr.dta.onboard.DrivingTrajectory)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::dr::dta::onboard::Point > point_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_dta_2fdta_5fonboard_2eproto;
};
// -------------------------------------------------------------------

class Point PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:dr.dta.onboard.Point) */ {
 public:
  inline Point() : Point(nullptr) {}
  virtual ~Point();

  Point(const Point& from);
  Point(Point&& from) noexcept
    : Point() {
    *this = ::std::move(from);
  }

  inline Point& operator=(const Point& from) {
    CopyFrom(from);
    return *this;
  }
  inline Point& operator=(Point&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Point& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Point* internal_default_instance() {
    return reinterpret_cast<const Point*>(
               &_Point_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(Point& a, Point& b) {
    a.Swap(&b);
  }
  inline void Swap(Point* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Point* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Point* New() const final {
    return CreateMaybeMessage<Point>(nullptr);
  }

  Point* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Point>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Point& from);
  void MergeFrom(const Point& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Point* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "dr.dta.onboard.Point";
  }
  protected:
  explicit Point(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_dta_2fdta_5fonboard_2eproto);
    return ::descriptor_table_dta_2fdta_5fonboard_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kZFieldNumber = 3,
  };
  // double x = 1;
  void clear_x();
  double x() const;
  void set_x(double value);
  private:
  double _internal_x() const;
  void _internal_set_x(double value);
  public:

  // double y = 2;
  void clear_y();
  double y() const;
  void set_y(double value);
  private:
  double _internal_y() const;
  void _internal_set_y(double value);
  public:

  // double z = 3;
  void clear_z();
  double z() const;
  void set_z(double value);
  private:
  double _internal_z() const;
  void _internal_set_z(double value);
  public:

  // @@protoc_insertion_point(class_scope:dr.dta.onboard.Point)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  double x_;
  double y_;
  double z_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_dta_2fdta_5fonboard_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// DtaOnboard

// .dr.dta.onboard.SingleTripDriving single_trip_driving = 1;
inline bool DtaOnboard::_internal_has_single_trip_driving() const {
  return this != internal_default_instance() && single_trip_driving_ != nullptr;
}
inline bool DtaOnboard::has_single_trip_driving() const {
  return _internal_has_single_trip_driving();
}
inline void DtaOnboard::clear_single_trip_driving() {
  if (GetArena() == nullptr && single_trip_driving_ != nullptr) {
    delete single_trip_driving_;
  }
  single_trip_driving_ = nullptr;
}
inline const ::dr::dta::onboard::SingleTripDriving& DtaOnboard::_internal_single_trip_driving() const {
  const ::dr::dta::onboard::SingleTripDriving* p = single_trip_driving_;
  return p != nullptr ? *p : *reinterpret_cast<const ::dr::dta::onboard::SingleTripDriving*>(
      &::dr::dta::onboard::_SingleTripDriving_default_instance_);
}
inline const ::dr::dta::onboard::SingleTripDriving& DtaOnboard::single_trip_driving() const {
  // @@protoc_insertion_point(field_get:dr.dta.onboard.DtaOnboard.single_trip_driving)
  return _internal_single_trip_driving();
}
inline void DtaOnboard::unsafe_arena_set_allocated_single_trip_driving(
    ::dr::dta::onboard::SingleTripDriving* single_trip_driving) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(single_trip_driving_);
  }
  single_trip_driving_ = single_trip_driving;
  if (single_trip_driving) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:dr.dta.onboard.DtaOnboard.single_trip_driving)
}
inline ::dr::dta::onboard::SingleTripDriving* DtaOnboard::release_single_trip_driving() {
  
  ::dr::dta::onboard::SingleTripDriving* temp = single_trip_driving_;
  single_trip_driving_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::dr::dta::onboard::SingleTripDriving* DtaOnboard::unsafe_arena_release_single_trip_driving() {
  // @@protoc_insertion_point(field_release:dr.dta.onboard.DtaOnboard.single_trip_driving)
  
  ::dr::dta::onboard::SingleTripDriving* temp = single_trip_driving_;
  single_trip_driving_ = nullptr;
  return temp;
}
inline ::dr::dta::onboard::SingleTripDriving* DtaOnboard::_internal_mutable_single_trip_driving() {
  
  if (single_trip_driving_ == nullptr) {
    auto* p = CreateMaybeMessage<::dr::dta::onboard::SingleTripDriving>(GetArena());
    single_trip_driving_ = p;
  }
  return single_trip_driving_;
}
inline ::dr::dta::onboard::SingleTripDriving* DtaOnboard::mutable_single_trip_driving() {
  // @@protoc_insertion_point(field_mutable:dr.dta.onboard.DtaOnboard.single_trip_driving)
  return _internal_mutable_single_trip_driving();
}
inline void DtaOnboard::set_allocated_single_trip_driving(::dr::dta::onboard::SingleTripDriving* single_trip_driving) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete single_trip_driving_;
  }
  if (single_trip_driving) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(single_trip_driving);
    if (message_arena != submessage_arena) {
      single_trip_driving = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, single_trip_driving, submessage_arena);
    }
    
  } else {
    
  }
  single_trip_driving_ = single_trip_driving;
  // @@protoc_insertion_point(field_set_allocated:dr.dta.onboard.DtaOnboard.single_trip_driving)
}

// -------------------------------------------------------------------

// SingleTripDriving

// string nav_id = 1;
inline void SingleTripDriving::clear_nav_id() {
  nav_id_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& SingleTripDriving::nav_id() const {
  // @@protoc_insertion_point(field_get:dr.dta.onboard.SingleTripDriving.nav_id)
  return _internal_nav_id();
}
inline void SingleTripDriving::set_nav_id(const std::string& value) {
  _internal_set_nav_id(value);
  // @@protoc_insertion_point(field_set:dr.dta.onboard.SingleTripDriving.nav_id)
}
inline std::string* SingleTripDriving::mutable_nav_id() {
  // @@protoc_insertion_point(field_mutable:dr.dta.onboard.SingleTripDriving.nav_id)
  return _internal_mutable_nav_id();
}
inline const std::string& SingleTripDriving::_internal_nav_id() const {
  return nav_id_.Get();
}
inline void SingleTripDriving::_internal_set_nav_id(const std::string& value) {
  
  nav_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void SingleTripDriving::set_nav_id(std::string&& value) {
  
  nav_id_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:dr.dta.onboard.SingleTripDriving.nav_id)
}
inline void SingleTripDriving::set_nav_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  nav_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:dr.dta.onboard.SingleTripDriving.nav_id)
}
inline void SingleTripDriving::set_nav_id(const char* value,
    size_t size) {
  
  nav_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:dr.dta.onboard.SingleTripDriving.nav_id)
}
inline std::string* SingleTripDriving::_internal_mutable_nav_id() {
  
  return nav_id_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* SingleTripDriving::release_nav_id() {
  // @@protoc_insertion_point(field_release:dr.dta.onboard.SingleTripDriving.nav_id)
  return nav_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void SingleTripDriving::set_allocated_nav_id(std::string* nav_id) {
  if (nav_id != nullptr) {
    
  } else {
    
  }
  nav_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), nav_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:dr.dta.onboard.SingleTripDriving.nav_id)
}

// double total_distance = 2;
inline void SingleTripDriving::clear_total_distance() {
  total_distance_ = 0;
}
inline double SingleTripDriving::_internal_total_distance() const {
  return total_distance_;
}
inline double SingleTripDriving::total_distance() const {
  // @@protoc_insertion_point(field_get:dr.dta.onboard.SingleTripDriving.total_distance)
  return _internal_total_distance();
}
inline void SingleTripDriving::_internal_set_total_distance(double value) {
  
  total_distance_ = value;
}
inline void SingleTripDriving::set_total_distance(double value) {
  _internal_set_total_distance(value);
  // @@protoc_insertion_point(field_set:dr.dta.onboard.SingleTripDriving.total_distance)
}

// double noa_distance = 3;
inline void SingleTripDriving::clear_noa_distance() {
  noa_distance_ = 0;
}
inline double SingleTripDriving::_internal_noa_distance() const {
  return noa_distance_;
}
inline double SingleTripDriving::noa_distance() const {
  // @@protoc_insertion_point(field_get:dr.dta.onboard.SingleTripDriving.noa_distance)
  return _internal_noa_distance();
}
inline void SingleTripDriving::_internal_set_noa_distance(double value) {
  
  noa_distance_ = value;
}
inline void SingleTripDriving::set_noa_distance(double value) {
  _internal_set_noa_distance(value);
  // @@protoc_insertion_point(field_set:dr.dta.onboard.SingleTripDriving.noa_distance)
}

// double lcc_distance = 4;
inline void SingleTripDriving::clear_lcc_distance() {
  lcc_distance_ = 0;
}
inline double SingleTripDriving::_internal_lcc_distance() const {
  return lcc_distance_;
}
inline double SingleTripDriving::lcc_distance() const {
  // @@protoc_insertion_point(field_get:dr.dta.onboard.SingleTripDriving.lcc_distance)
  return _internal_lcc_distance();
}
inline void SingleTripDriving::_internal_set_lcc_distance(double value) {
  
  lcc_distance_ = value;
}
inline void SingleTripDriving::set_lcc_distance(double value) {
  _internal_set_lcc_distance(value);
  // @@protoc_insertion_point(field_set:dr.dta.onboard.SingleTripDriving.lcc_distance)
}

// double acc_distance = 5;
inline void SingleTripDriving::clear_acc_distance() {
  acc_distance_ = 0;
}
inline double SingleTripDriving::_internal_acc_distance() const {
  return acc_distance_;
}
inline double SingleTripDriving::acc_distance() const {
  // @@protoc_insertion_point(field_get:dr.dta.onboard.SingleTripDriving.acc_distance)
  return _internal_acc_distance();
}
inline void SingleTripDriving::_internal_set_acc_distance(double value) {
  
  acc_distance_ = value;
}
inline void SingleTripDriving::set_acc_distance(double value) {
  _internal_set_acc_distance(value);
  // @@protoc_insertion_point(field_set:dr.dta.onboard.SingleTripDriving.acc_distance)
}

// uint64 total_time = 6;
inline void SingleTripDriving::clear_total_time() {
  total_time_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 SingleTripDriving::_internal_total_time() const {
  return total_time_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 SingleTripDriving::total_time() const {
  // @@protoc_insertion_point(field_get:dr.dta.onboard.SingleTripDriving.total_time)
  return _internal_total_time();
}
inline void SingleTripDriving::_internal_set_total_time(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  total_time_ = value;
}
inline void SingleTripDriving::set_total_time(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_total_time(value);
  // @@protoc_insertion_point(field_set:dr.dta.onboard.SingleTripDriving.total_time)
}

// uint64 noa_time = 7;
inline void SingleTripDriving::clear_noa_time() {
  noa_time_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 SingleTripDriving::_internal_noa_time() const {
  return noa_time_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 SingleTripDriving::noa_time() const {
  // @@protoc_insertion_point(field_get:dr.dta.onboard.SingleTripDriving.noa_time)
  return _internal_noa_time();
}
inline void SingleTripDriving::_internal_set_noa_time(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  noa_time_ = value;
}
inline void SingleTripDriving::set_noa_time(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_noa_time(value);
  // @@protoc_insertion_point(field_set:dr.dta.onboard.SingleTripDriving.noa_time)
}

// uint64 lcc_time = 8;
inline void SingleTripDriving::clear_lcc_time() {
  lcc_time_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 SingleTripDriving::_internal_lcc_time() const {
  return lcc_time_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 SingleTripDriving::lcc_time() const {
  // @@protoc_insertion_point(field_get:dr.dta.onboard.SingleTripDriving.lcc_time)
  return _internal_lcc_time();
}
inline void SingleTripDriving::_internal_set_lcc_time(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  lcc_time_ = value;
}
inline void SingleTripDriving::set_lcc_time(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_lcc_time(value);
  // @@protoc_insertion_point(field_set:dr.dta.onboard.SingleTripDriving.lcc_time)
}

// uint64 acc_time = 9;
inline void SingleTripDriving::clear_acc_time() {
  acc_time_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 SingleTripDriving::_internal_acc_time() const {
  return acc_time_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 SingleTripDriving::acc_time() const {
  // @@protoc_insertion_point(field_get:dr.dta.onboard.SingleTripDriving.acc_time)
  return _internal_acc_time();
}
inline void SingleTripDriving::_internal_set_acc_time(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  acc_time_ = value;
}
inline void SingleTripDriving::set_acc_time(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_acc_time(value);
  // @@protoc_insertion_point(field_set:dr.dta.onboard.SingleTripDriving.acc_time)
}

// .dr.dta.onboard.PerformanceMetrics performance_metrics = 10;
inline bool SingleTripDriving::_internal_has_performance_metrics() const {
  return this != internal_default_instance() && performance_metrics_ != nullptr;
}
inline bool SingleTripDriving::has_performance_metrics() const {
  return _internal_has_performance_metrics();
}
inline void SingleTripDriving::clear_performance_metrics() {
  if (GetArena() == nullptr && performance_metrics_ != nullptr) {
    delete performance_metrics_;
  }
  performance_metrics_ = nullptr;
}
inline const ::dr::dta::onboard::PerformanceMetrics& SingleTripDriving::_internal_performance_metrics() const {
  const ::dr::dta::onboard::PerformanceMetrics* p = performance_metrics_;
  return p != nullptr ? *p : *reinterpret_cast<const ::dr::dta::onboard::PerformanceMetrics*>(
      &::dr::dta::onboard::_PerformanceMetrics_default_instance_);
}
inline const ::dr::dta::onboard::PerformanceMetrics& SingleTripDriving::performance_metrics() const {
  // @@protoc_insertion_point(field_get:dr.dta.onboard.SingleTripDriving.performance_metrics)
  return _internal_performance_metrics();
}
inline void SingleTripDriving::unsafe_arena_set_allocated_performance_metrics(
    ::dr::dta::onboard::PerformanceMetrics* performance_metrics) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(performance_metrics_);
  }
  performance_metrics_ = performance_metrics;
  if (performance_metrics) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:dr.dta.onboard.SingleTripDriving.performance_metrics)
}
inline ::dr::dta::onboard::PerformanceMetrics* SingleTripDriving::release_performance_metrics() {
  
  ::dr::dta::onboard::PerformanceMetrics* temp = performance_metrics_;
  performance_metrics_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::dr::dta::onboard::PerformanceMetrics* SingleTripDriving::unsafe_arena_release_performance_metrics() {
  // @@protoc_insertion_point(field_release:dr.dta.onboard.SingleTripDriving.performance_metrics)
  
  ::dr::dta::onboard::PerformanceMetrics* temp = performance_metrics_;
  performance_metrics_ = nullptr;
  return temp;
}
inline ::dr::dta::onboard::PerformanceMetrics* SingleTripDriving::_internal_mutable_performance_metrics() {
  
  if (performance_metrics_ == nullptr) {
    auto* p = CreateMaybeMessage<::dr::dta::onboard::PerformanceMetrics>(GetArena());
    performance_metrics_ = p;
  }
  return performance_metrics_;
}
inline ::dr::dta::onboard::PerformanceMetrics* SingleTripDriving::mutable_performance_metrics() {
  // @@protoc_insertion_point(field_mutable:dr.dta.onboard.SingleTripDriving.performance_metrics)
  return _internal_mutable_performance_metrics();
}
inline void SingleTripDriving::set_allocated_performance_metrics(::dr::dta::onboard::PerformanceMetrics* performance_metrics) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete performance_metrics_;
  }
  if (performance_metrics) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(performance_metrics);
    if (message_arena != submessage_arena) {
      performance_metrics = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, performance_metrics, submessage_arena);
    }
    
  } else {
    
  }
  performance_metrics_ = performance_metrics;
  // @@protoc_insertion_point(field_set_allocated:dr.dta.onboard.SingleTripDriving.performance_metrics)
}

// .dr.dta.onboard.DrivingTrajectory driving_trajectory = 11;
inline bool SingleTripDriving::_internal_has_driving_trajectory() const {
  return this != internal_default_instance() && driving_trajectory_ != nullptr;
}
inline bool SingleTripDriving::has_driving_trajectory() const {
  return _internal_has_driving_trajectory();
}
inline void SingleTripDriving::clear_driving_trajectory() {
  if (GetArena() == nullptr && driving_trajectory_ != nullptr) {
    delete driving_trajectory_;
  }
  driving_trajectory_ = nullptr;
}
inline const ::dr::dta::onboard::DrivingTrajectory& SingleTripDriving::_internal_driving_trajectory() const {
  const ::dr::dta::onboard::DrivingTrajectory* p = driving_trajectory_;
  return p != nullptr ? *p : *reinterpret_cast<const ::dr::dta::onboard::DrivingTrajectory*>(
      &::dr::dta::onboard::_DrivingTrajectory_default_instance_);
}
inline const ::dr::dta::onboard::DrivingTrajectory& SingleTripDriving::driving_trajectory() const {
  // @@protoc_insertion_point(field_get:dr.dta.onboard.SingleTripDriving.driving_trajectory)
  return _internal_driving_trajectory();
}
inline void SingleTripDriving::unsafe_arena_set_allocated_driving_trajectory(
    ::dr::dta::onboard::DrivingTrajectory* driving_trajectory) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(driving_trajectory_);
  }
  driving_trajectory_ = driving_trajectory;
  if (driving_trajectory) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:dr.dta.onboard.SingleTripDriving.driving_trajectory)
}
inline ::dr::dta::onboard::DrivingTrajectory* SingleTripDriving::release_driving_trajectory() {
  
  ::dr::dta::onboard::DrivingTrajectory* temp = driving_trajectory_;
  driving_trajectory_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::dr::dta::onboard::DrivingTrajectory* SingleTripDriving::unsafe_arena_release_driving_trajectory() {
  // @@protoc_insertion_point(field_release:dr.dta.onboard.SingleTripDriving.driving_trajectory)
  
  ::dr::dta::onboard::DrivingTrajectory* temp = driving_trajectory_;
  driving_trajectory_ = nullptr;
  return temp;
}
inline ::dr::dta::onboard::DrivingTrajectory* SingleTripDriving::_internal_mutable_driving_trajectory() {
  
  if (driving_trajectory_ == nullptr) {
    auto* p = CreateMaybeMessage<::dr::dta::onboard::DrivingTrajectory>(GetArena());
    driving_trajectory_ = p;
  }
  return driving_trajectory_;
}
inline ::dr::dta::onboard::DrivingTrajectory* SingleTripDriving::mutable_driving_trajectory() {
  // @@protoc_insertion_point(field_mutable:dr.dta.onboard.SingleTripDriving.driving_trajectory)
  return _internal_mutable_driving_trajectory();
}
inline void SingleTripDriving::set_allocated_driving_trajectory(::dr::dta::onboard::DrivingTrajectory* driving_trajectory) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete driving_trajectory_;
  }
  if (driving_trajectory) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(driving_trajectory);
    if (message_arena != submessage_arena) {
      driving_trajectory = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, driving_trajectory, submessage_arena);
    }
    
  } else {
    
  }
  driving_trajectory_ = driving_trajectory;
  // @@protoc_insertion_point(field_set_allocated:dr.dta.onboard.SingleTripDriving.driving_trajectory)
}

// -------------------------------------------------------------------

// PerformanceMetrics

// repeated .dr.dta.onboard.GradingInfo grading_info = 1;
inline int PerformanceMetrics::_internal_grading_info_size() const {
  return grading_info_.size();
}
inline int PerformanceMetrics::grading_info_size() const {
  return _internal_grading_info_size();
}
inline void PerformanceMetrics::clear_grading_info() {
  grading_info_.Clear();
}
inline ::dr::dta::onboard::GradingInfo* PerformanceMetrics::mutable_grading_info(int index) {
  // @@protoc_insertion_point(field_mutable:dr.dta.onboard.PerformanceMetrics.grading_info)
  return grading_info_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::dr::dta::onboard::GradingInfo >*
PerformanceMetrics::mutable_grading_info() {
  // @@protoc_insertion_point(field_mutable_list:dr.dta.onboard.PerformanceMetrics.grading_info)
  return &grading_info_;
}
inline const ::dr::dta::onboard::GradingInfo& PerformanceMetrics::_internal_grading_info(int index) const {
  return grading_info_.Get(index);
}
inline const ::dr::dta::onboard::GradingInfo& PerformanceMetrics::grading_info(int index) const {
  // @@protoc_insertion_point(field_get:dr.dta.onboard.PerformanceMetrics.grading_info)
  return _internal_grading_info(index);
}
inline ::dr::dta::onboard::GradingInfo* PerformanceMetrics::_internal_add_grading_info() {
  return grading_info_.Add();
}
inline ::dr::dta::onboard::GradingInfo* PerformanceMetrics::add_grading_info() {
  // @@protoc_insertion_point(field_add:dr.dta.onboard.PerformanceMetrics.grading_info)
  return _internal_add_grading_info();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::dr::dta::onboard::GradingInfo >&
PerformanceMetrics::grading_info() const {
  // @@protoc_insertion_point(field_list:dr.dta.onboard.PerformanceMetrics.grading_info)
  return grading_info_;
}

// -------------------------------------------------------------------

// GradingInfo

// .dr.dta.onboard.GradingInfo.GradingEvent grading_event = 1;
inline void GradingInfo::clear_grading_event() {
  grading_event_ = 0;
}
inline ::dr::dta::onboard::GradingInfo_GradingEvent GradingInfo::_internal_grading_event() const {
  return static_cast< ::dr::dta::onboard::GradingInfo_GradingEvent >(grading_event_);
}
inline ::dr::dta::onboard::GradingInfo_GradingEvent GradingInfo::grading_event() const {
  // @@protoc_insertion_point(field_get:dr.dta.onboard.GradingInfo.grading_event)
  return _internal_grading_event();
}
inline void GradingInfo::_internal_set_grading_event(::dr::dta::onboard::GradingInfo_GradingEvent value) {
  
  grading_event_ = value;
}
inline void GradingInfo::set_grading_event(::dr::dta::onboard::GradingInfo_GradingEvent value) {
  _internal_set_grading_event(value);
  // @@protoc_insertion_point(field_set:dr.dta.onboard.GradingInfo.grading_event)
}

// uint32 times = 2;
inline void GradingInfo::clear_times() {
  times_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 GradingInfo::_internal_times() const {
  return times_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 GradingInfo::times() const {
  // @@protoc_insertion_point(field_get:dr.dta.onboard.GradingInfo.times)
  return _internal_times();
}
inline void GradingInfo::_internal_set_times(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  times_ = value;
}
inline void GradingInfo::set_times(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_times(value);
  // @@protoc_insertion_point(field_set:dr.dta.onboard.GradingInfo.times)
}

// -------------------------------------------------------------------

// DrivingTrajectory

// repeated .dr.dta.onboard.Point point = 1;
inline int DrivingTrajectory::_internal_point_size() const {
  return point_.size();
}
inline int DrivingTrajectory::point_size() const {
  return _internal_point_size();
}
inline void DrivingTrajectory::clear_point() {
  point_.Clear();
}
inline ::dr::dta::onboard::Point* DrivingTrajectory::mutable_point(int index) {
  // @@protoc_insertion_point(field_mutable:dr.dta.onboard.DrivingTrajectory.point)
  return point_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::dr::dta::onboard::Point >*
DrivingTrajectory::mutable_point() {
  // @@protoc_insertion_point(field_mutable_list:dr.dta.onboard.DrivingTrajectory.point)
  return &point_;
}
inline const ::dr::dta::onboard::Point& DrivingTrajectory::_internal_point(int index) const {
  return point_.Get(index);
}
inline const ::dr::dta::onboard::Point& DrivingTrajectory::point(int index) const {
  // @@protoc_insertion_point(field_get:dr.dta.onboard.DrivingTrajectory.point)
  return _internal_point(index);
}
inline ::dr::dta::onboard::Point* DrivingTrajectory::_internal_add_point() {
  return point_.Add();
}
inline ::dr::dta::onboard::Point* DrivingTrajectory::add_point() {
  // @@protoc_insertion_point(field_add:dr.dta.onboard.DrivingTrajectory.point)
  return _internal_add_point();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::dr::dta::onboard::Point >&
DrivingTrajectory::point() const {
  // @@protoc_insertion_point(field_list:dr.dta.onboard.DrivingTrajectory.point)
  return point_;
}

// -------------------------------------------------------------------

// Point

// double x = 1;
inline void Point::clear_x() {
  x_ = 0;
}
inline double Point::_internal_x() const {
  return x_;
}
inline double Point::x() const {
  // @@protoc_insertion_point(field_get:dr.dta.onboard.Point.x)
  return _internal_x();
}
inline void Point::_internal_set_x(double value) {
  
  x_ = value;
}
inline void Point::set_x(double value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:dr.dta.onboard.Point.x)
}

// double y = 2;
inline void Point::clear_y() {
  y_ = 0;
}
inline double Point::_internal_y() const {
  return y_;
}
inline double Point::y() const {
  // @@protoc_insertion_point(field_get:dr.dta.onboard.Point.y)
  return _internal_y();
}
inline void Point::_internal_set_y(double value) {
  
  y_ = value;
}
inline void Point::set_y(double value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:dr.dta.onboard.Point.y)
}

// double z = 3;
inline void Point::clear_z() {
  z_ = 0;
}
inline double Point::_internal_z() const {
  return z_;
}
inline double Point::z() const {
  // @@protoc_insertion_point(field_get:dr.dta.onboard.Point.z)
  return _internal_z();
}
inline void Point::_internal_set_z(double value) {
  
  z_ = value;
}
inline void Point::set_z(double value) {
  _internal_set_z(value);
  // @@protoc_insertion_point(field_set:dr.dta.onboard.Point.z)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace onboard
}  // namespace dta
}  // namespace dr

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::dr::dta::onboard::GradingInfo_GradingEvent> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::dr::dta::onboard::GradingInfo_GradingEvent>() {
  return ::dr::dta::onboard::GradingInfo_GradingEvent_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_dta_2fdta_5fonboard_2eproto
