# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: canbus/chassis_control_interface_type.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'canbus/chassis_control_interface_type.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+canbus/chassis_control_interface_type.proto\x12\x10\x64\x65\x65proute.canbus\"u\n\nEpbRequest\x12\x35\n\x07request\x18\x01 \x01(\x0e\x32$.deeproute.canbus.EpbRequest.Request\"0\n\x07Request\x12\x0e\n\nNO_REQUEST\x10\x00\x12\x08\n\x04PARK\x10\x01\x12\x0b\n\x07RELEASE\x10\x02')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'canbus.chassis_control_interface_type_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EPBREQUEST']._serialized_start=65
  _globals['_EPBREQUEST']._serialized_end=182
  _globals['_EPBREQUEST_REQUEST']._serialized_start=134
  _globals['_EPBREQUEST_REQUEST']._serialized_end=182
# @@protoc_insertion_point(module_scope)
