# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: map/map_engine_setting_cmd.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'map/map_engine_setting_cmd.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n map/map_engine_setting_cmd.proto\x12\rdeeproute.map\"r\n\x1eMapEngineSettingCommandRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12<\n\x14variable_lane_switch\x18\x02 \x01(\x0e\x32\x1e.deeproute.map.MapEngineSwitch\"\xc9\x01\n\x1fMapEngineSettingCommandResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x45\n\x06status\x18\x02 \x01(\x0b\x32\x35.deeproute.map.MapEngineSettingCommandResponse.Status\x1aK\n\x06Status\x12\x30\n\x04\x63ode\x18\x01 \x01(\x0e\x32\".deeproute.map.MapEngineSwitchCode\x12\x0f\n\x07\x65rr_msg\x18\x02 \x01(\t*\x84\x01\n\x0fMapEngineSwitch\x12\x1d\n\x19MAP_ENGINE_SWITCH_NOT_SET\x10\x00\x12\x1d\n\x19MAP_ENGINE_SWITCH_DEFAULT\x10\x01\x12\x18\n\x14MAP_ENGINE_SWITCH_ON\x10\x02\x12\x19\n\x15MAP_ENGINE_SWITCH_OFF\x10\x03*T\n\x13MapEngineSwitchCode\x12\x1d\n\x19MAP_ENGINE_SWITCH_SUCCESS\x10\x00\x12\x1e\n\x1aMAP_ENGINE_SWITCH_INTERNAL\x10\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'map.map_engine_setting_cmd_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MAPENGINESWITCH']._serialized_start=372
  _globals['_MAPENGINESWITCH']._serialized_end=504
  _globals['_MAPENGINESWITCHCODE']._serialized_start=506
  _globals['_MAPENGINESWITCHCODE']._serialized_end=590
  _globals['_MAPENGINESETTINGCOMMANDREQUEST']._serialized_start=51
  _globals['_MAPENGINESETTINGCOMMANDREQUEST']._serialized_end=165
  _globals['_MAPENGINESETTINGCOMMANDRESPONSE']._serialized_start=168
  _globals['_MAPENGINESETTINGCOMMANDRESPONSE']._serialized_end=369
  _globals['_MAPENGINESETTINGCOMMANDRESPONSE_STATUS']._serialized_start=294
  _globals['_MAPENGINESETTINGCOMMANDRESPONSE_STATUS']._serialized_end=369
# @@protoc_insertion_point(module_scope)
