// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: drapi/base.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_drapi_2fbase_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_drapi_2fbase_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3013000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3013000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_drapi_2fbase_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_drapi_2fbase_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[9]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_drapi_2fbase_2eproto;
namespace dr {
namespace base {
class ParkingSpace;
class ParkingSpaceDefaultTypeInternal;
extern ParkingSpaceDefaultTypeInternal _ParkingSpace_default_instance_;
class Point2D;
class Point2DDefaultTypeInternal;
extern Point2DDefaultTypeInternal _Point2D_default_instance_;
class Point2DWithHeading;
class Point2DWithHeadingDefaultTypeInternal;
extern Point2DWithHeadingDefaultTypeInternal _Point2DWithHeading_default_instance_;
class Point3D;
class Point3DDefaultTypeInternal;
extern Point3DDefaultTypeInternal _Point3D_default_instance_;
class Point3DWithHeading;
class Point3DWithHeadingDefaultTypeInternal;
extern Point3DWithHeadingDefaultTypeInternal _Point3DWithHeading_default_instance_;
class PointLLH;
class PointLLHDefaultTypeInternal;
extern PointLLHDefaultTypeInternal _PointLLH_default_instance_;
class Polygon;
class PolygonDefaultTypeInternal;
extern PolygonDefaultTypeInternal _Polygon_default_instance_;
class Polyline;
class PolylineDefaultTypeInternal;
extern PolylineDefaultTypeInternal _Polyline_default_instance_;
class RotatedRect;
class RotatedRectDefaultTypeInternal;
extern RotatedRectDefaultTypeInternal _RotatedRect_default_instance_;
}  // namespace base
}  // namespace dr
PROTOBUF_NAMESPACE_OPEN
template<> ::dr::base::ParkingSpace* Arena::CreateMaybeMessage<::dr::base::ParkingSpace>(Arena*);
template<> ::dr::base::Point2D* Arena::CreateMaybeMessage<::dr::base::Point2D>(Arena*);
template<> ::dr::base::Point2DWithHeading* Arena::CreateMaybeMessage<::dr::base::Point2DWithHeading>(Arena*);
template<> ::dr::base::Point3D* Arena::CreateMaybeMessage<::dr::base::Point3D>(Arena*);
template<> ::dr::base::Point3DWithHeading* Arena::CreateMaybeMessage<::dr::base::Point3DWithHeading>(Arena*);
template<> ::dr::base::PointLLH* Arena::CreateMaybeMessage<::dr::base::PointLLH>(Arena*);
template<> ::dr::base::Polygon* Arena::CreateMaybeMessage<::dr::base::Polygon>(Arena*);
template<> ::dr::base::Polyline* Arena::CreateMaybeMessage<::dr::base::Polyline>(Arena*);
template<> ::dr::base::RotatedRect* Arena::CreateMaybeMessage<::dr::base::RotatedRect>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace dr {
namespace base {

enum ParkingSpace_ParkingSpaceType : int {
  ParkingSpace_ParkingSpaceType_UNKNOWN = 0,
  ParkingSpace_ParkingSpaceType_VERTICAL = 1,
  ParkingSpace_ParkingSpaceType_PARALLEL = 2,
  ParkingSpace_ParkingSpaceType_SLANTED = 3,
  ParkingSpace_ParkingSpaceType_ParkingSpace_ParkingSpaceType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  ParkingSpace_ParkingSpaceType_ParkingSpace_ParkingSpaceType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool ParkingSpace_ParkingSpaceType_IsValid(int value);
constexpr ParkingSpace_ParkingSpaceType ParkingSpace_ParkingSpaceType_ParkingSpaceType_MIN = ParkingSpace_ParkingSpaceType_UNKNOWN;
constexpr ParkingSpace_ParkingSpaceType ParkingSpace_ParkingSpaceType_ParkingSpaceType_MAX = ParkingSpace_ParkingSpaceType_SLANTED;
constexpr int ParkingSpace_ParkingSpaceType_ParkingSpaceType_ARRAYSIZE = ParkingSpace_ParkingSpaceType_ParkingSpaceType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ParkingSpace_ParkingSpaceType_descriptor();
template<typename T>
inline const std::string& ParkingSpace_ParkingSpaceType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ParkingSpace_ParkingSpaceType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ParkingSpace_ParkingSpaceType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ParkingSpace_ParkingSpaceType_descriptor(), enum_t_value);
}
inline bool ParkingSpace_ParkingSpaceType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ParkingSpace_ParkingSpaceType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ParkingSpace_ParkingSpaceType>(
    ParkingSpace_ParkingSpaceType_descriptor(), name, value);
}
enum ErrorCode : int {
  SUCCESS = 0,
  UNKNOWN_ERROR = 1,
  NOT_READY = 2,
  REPEATED_REQUEST = 3,
  LOCATION_ERROR = 4,
  PARAMETER_ERROR = 5,
  REQUEST_TIMEOUT = 6,
  PLANNING_FAILURE = 7,
  DSM_FAILURE = 8,
  AD_ACTIVED = 9,
  ErrorCode_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  ErrorCode_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool ErrorCode_IsValid(int value);
constexpr ErrorCode ErrorCode_MIN = SUCCESS;
constexpr ErrorCode ErrorCode_MAX = AD_ACTIVED;
constexpr int ErrorCode_ARRAYSIZE = ErrorCode_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ErrorCode_descriptor();
template<typename T>
inline const std::string& ErrorCode_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ErrorCode>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ErrorCode_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ErrorCode_descriptor(), enum_t_value);
}
inline bool ErrorCode_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ErrorCode* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ErrorCode>(
    ErrorCode_descriptor(), name, value);
}
enum CoorSys : int {
  COORSYS_UNKNOWN = 0,
  COORSYS_GCJ02 = 1,
  COORSYS_WGS84 = 2,
  COORSYS_HD = 3,
  CoorSys_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  CoorSys_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool CoorSys_IsValid(int value);
constexpr CoorSys CoorSys_MIN = COORSYS_UNKNOWN;
constexpr CoorSys CoorSys_MAX = COORSYS_HD;
constexpr int CoorSys_ARRAYSIZE = CoorSys_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* CoorSys_descriptor();
template<typename T>
inline const std::string& CoorSys_Name(T enum_t_value) {
  static_assert(::std::is_same<T, CoorSys>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function CoorSys_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    CoorSys_descriptor(), enum_t_value);
}
inline bool CoorSys_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, CoorSys* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<CoorSys>(
    CoorSys_descriptor(), name, value);
}
enum GearPosition : int {
  INVALID = 0,
  PARK = 1,
  REVERSE = 2,
  NEUTRAL = 3,
  DRIVE = 4,
  LOW = 5,
  UNSPECIFIED = 6,
  GearPosition_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  GearPosition_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool GearPosition_IsValid(int value);
constexpr GearPosition GearPosition_MIN = INVALID;
constexpr GearPosition GearPosition_MAX = UNSPECIFIED;
constexpr int GearPosition_ARRAYSIZE = GearPosition_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* GearPosition_descriptor();
template<typename T>
inline const std::string& GearPosition_Name(T enum_t_value) {
  static_assert(::std::is_same<T, GearPosition>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function GearPosition_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    GearPosition_descriptor(), enum_t_value);
}
inline bool GearPosition_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, GearPosition* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<GearPosition>(
    GearPosition_descriptor(), name, value);
}
enum Color : int {
  UNKNOWN = 0,
  RED = 1,
  YELLOW = 2,
  GREEN = 3,
  BLACK = 4,
  Color_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  Color_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool Color_IsValid(int value);
constexpr Color Color_MIN = UNKNOWN;
constexpr Color Color_MAX = BLACK;
constexpr int Color_ARRAYSIZE = Color_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Color_descriptor();
template<typename T>
inline const std::string& Color_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Color>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Color_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Color_descriptor(), enum_t_value);
}
inline bool Color_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, Color* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Color>(
    Color_descriptor(), name, value);
}
enum Direction : int {
  DIRECTION_UNKNOWN = 0,
  LEFT = 1,
  RIGHT = 2,
  Direction_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  Direction_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool Direction_IsValid(int value);
constexpr Direction Direction_MIN = DIRECTION_UNKNOWN;
constexpr Direction Direction_MAX = RIGHT;
constexpr int Direction_ARRAYSIZE = Direction_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Direction_descriptor();
template<typename T>
inline const std::string& Direction_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Direction>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Direction_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Direction_descriptor(), enum_t_value);
}
inline bool Direction_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, Direction* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Direction>(
    Direction_descriptor(), name, value);
}
// ===================================================================

class PointLLH PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:dr.base.PointLLH) */ {
 public:
  inline PointLLH() : PointLLH(nullptr) {}
  virtual ~PointLLH();

  PointLLH(const PointLLH& from);
  PointLLH(PointLLH&& from) noexcept
    : PointLLH() {
    *this = ::std::move(from);
  }

  inline PointLLH& operator=(const PointLLH& from) {
    CopyFrom(from);
    return *this;
  }
  inline PointLLH& operator=(PointLLH&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const PointLLH& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PointLLH* internal_default_instance() {
    return reinterpret_cast<const PointLLH*>(
               &_PointLLH_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(PointLLH& a, PointLLH& b) {
    a.Swap(&b);
  }
  inline void Swap(PointLLH* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PointLLH* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PointLLH* New() const final {
    return CreateMaybeMessage<PointLLH>(nullptr);
  }

  PointLLH* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PointLLH>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const PointLLH& from);
  void MergeFrom(const PointLLH& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PointLLH* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "dr.base.PointLLH";
  }
  protected:
  explicit PointLLH(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_drapi_2fbase_2eproto);
    return ::descriptor_table_drapi_2fbase_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLonFieldNumber = 1,
    kLatFieldNumber = 2,
    kHeightFieldNumber = 3,
  };
  // double lon = 1;
  void clear_lon();
  double lon() const;
  void set_lon(double value);
  private:
  double _internal_lon() const;
  void _internal_set_lon(double value);
  public:

  // double lat = 2;
  void clear_lat();
  double lat() const;
  void set_lat(double value);
  private:
  double _internal_lat() const;
  void _internal_set_lat(double value);
  public:

  // double height = 3;
  void clear_height();
  double height() const;
  void set_height(double value);
  private:
  double _internal_height() const;
  void _internal_set_height(double value);
  public:

  // @@protoc_insertion_point(class_scope:dr.base.PointLLH)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  double lon_;
  double lat_;
  double height_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_drapi_2fbase_2eproto;
};
// -------------------------------------------------------------------

class Point2D PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:dr.base.Point2D) */ {
 public:
  inline Point2D() : Point2D(nullptr) {}
  virtual ~Point2D();

  Point2D(const Point2D& from);
  Point2D(Point2D&& from) noexcept
    : Point2D() {
    *this = ::std::move(from);
  }

  inline Point2D& operator=(const Point2D& from) {
    CopyFrom(from);
    return *this;
  }
  inline Point2D& operator=(Point2D&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Point2D& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Point2D* internal_default_instance() {
    return reinterpret_cast<const Point2D*>(
               &_Point2D_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Point2D& a, Point2D& b) {
    a.Swap(&b);
  }
  inline void Swap(Point2D* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Point2D* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Point2D* New() const final {
    return CreateMaybeMessage<Point2D>(nullptr);
  }

  Point2D* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Point2D>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Point2D& from);
  void MergeFrom(const Point2D& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Point2D* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "dr.base.Point2D";
  }
  protected:
  explicit Point2D(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_drapi_2fbase_2eproto);
    return ::descriptor_table_drapi_2fbase_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
  };
  // double x = 1;
  void clear_x();
  double x() const;
  void set_x(double value);
  private:
  double _internal_x() const;
  void _internal_set_x(double value);
  public:

  // double y = 2;
  void clear_y();
  double y() const;
  void set_y(double value);
  private:
  double _internal_y() const;
  void _internal_set_y(double value);
  public:

  // @@protoc_insertion_point(class_scope:dr.base.Point2D)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  double x_;
  double y_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_drapi_2fbase_2eproto;
};
// -------------------------------------------------------------------

class Point2DWithHeading PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:dr.base.Point2DWithHeading) */ {
 public:
  inline Point2DWithHeading() : Point2DWithHeading(nullptr) {}
  virtual ~Point2DWithHeading();

  Point2DWithHeading(const Point2DWithHeading& from);
  Point2DWithHeading(Point2DWithHeading&& from) noexcept
    : Point2DWithHeading() {
    *this = ::std::move(from);
  }

  inline Point2DWithHeading& operator=(const Point2DWithHeading& from) {
    CopyFrom(from);
    return *this;
  }
  inline Point2DWithHeading& operator=(Point2DWithHeading&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Point2DWithHeading& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Point2DWithHeading* internal_default_instance() {
    return reinterpret_cast<const Point2DWithHeading*>(
               &_Point2DWithHeading_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Point2DWithHeading& a, Point2DWithHeading& b) {
    a.Swap(&b);
  }
  inline void Swap(Point2DWithHeading* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Point2DWithHeading* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Point2DWithHeading* New() const final {
    return CreateMaybeMessage<Point2DWithHeading>(nullptr);
  }

  Point2DWithHeading* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Point2DWithHeading>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Point2DWithHeading& from);
  void MergeFrom(const Point2DWithHeading& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Point2DWithHeading* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "dr.base.Point2DWithHeading";
  }
  protected:
  explicit Point2DWithHeading(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_drapi_2fbase_2eproto);
    return ::descriptor_table_drapi_2fbase_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPointFieldNumber = 1,
    kHeadingFieldNumber = 2,
  };
  // .dr.base.Point2D point = 1;
  bool has_point() const;
  private:
  bool _internal_has_point() const;
  public:
  void clear_point();
  const ::dr::base::Point2D& point() const;
  ::dr::base::Point2D* release_point();
  ::dr::base::Point2D* mutable_point();
  void set_allocated_point(::dr::base::Point2D* point);
  private:
  const ::dr::base::Point2D& _internal_point() const;
  ::dr::base::Point2D* _internal_mutable_point();
  public:
  void unsafe_arena_set_allocated_point(
      ::dr::base::Point2D* point);
  ::dr::base::Point2D* unsafe_arena_release_point();

  // double heading = 2;
  void clear_heading();
  double heading() const;
  void set_heading(double value);
  private:
  double _internal_heading() const;
  void _internal_set_heading(double value);
  public:

  // @@protoc_insertion_point(class_scope:dr.base.Point2DWithHeading)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::dr::base::Point2D* point_;
  double heading_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_drapi_2fbase_2eproto;
};
// -------------------------------------------------------------------

class Point3D PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:dr.base.Point3D) */ {
 public:
  inline Point3D() : Point3D(nullptr) {}
  virtual ~Point3D();

  Point3D(const Point3D& from);
  Point3D(Point3D&& from) noexcept
    : Point3D() {
    *this = ::std::move(from);
  }

  inline Point3D& operator=(const Point3D& from) {
    CopyFrom(from);
    return *this;
  }
  inline Point3D& operator=(Point3D&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Point3D& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Point3D* internal_default_instance() {
    return reinterpret_cast<const Point3D*>(
               &_Point3D_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(Point3D& a, Point3D& b) {
    a.Swap(&b);
  }
  inline void Swap(Point3D* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Point3D* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Point3D* New() const final {
    return CreateMaybeMessage<Point3D>(nullptr);
  }

  Point3D* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Point3D>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Point3D& from);
  void MergeFrom(const Point3D& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Point3D* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "dr.base.Point3D";
  }
  protected:
  explicit Point3D(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_drapi_2fbase_2eproto);
    return ::descriptor_table_drapi_2fbase_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kZFieldNumber = 3,
  };
  // double x = 1;
  void clear_x();
  double x() const;
  void set_x(double value);
  private:
  double _internal_x() const;
  void _internal_set_x(double value);
  public:

  // double y = 2;
  void clear_y();
  double y() const;
  void set_y(double value);
  private:
  double _internal_y() const;
  void _internal_set_y(double value);
  public:

  // double z = 3;
  void clear_z();
  double z() const;
  void set_z(double value);
  private:
  double _internal_z() const;
  void _internal_set_z(double value);
  public:

  // @@protoc_insertion_point(class_scope:dr.base.Point3D)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  double x_;
  double y_;
  double z_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_drapi_2fbase_2eproto;
};
// -------------------------------------------------------------------

class Point3DWithHeading PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:dr.base.Point3DWithHeading) */ {
 public:
  inline Point3DWithHeading() : Point3DWithHeading(nullptr) {}
  virtual ~Point3DWithHeading();

  Point3DWithHeading(const Point3DWithHeading& from);
  Point3DWithHeading(Point3DWithHeading&& from) noexcept
    : Point3DWithHeading() {
    *this = ::std::move(from);
  }

  inline Point3DWithHeading& operator=(const Point3DWithHeading& from) {
    CopyFrom(from);
    return *this;
  }
  inline Point3DWithHeading& operator=(Point3DWithHeading&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Point3DWithHeading& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Point3DWithHeading* internal_default_instance() {
    return reinterpret_cast<const Point3DWithHeading*>(
               &_Point3DWithHeading_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(Point3DWithHeading& a, Point3DWithHeading& b) {
    a.Swap(&b);
  }
  inline void Swap(Point3DWithHeading* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Point3DWithHeading* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Point3DWithHeading* New() const final {
    return CreateMaybeMessage<Point3DWithHeading>(nullptr);
  }

  Point3DWithHeading* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Point3DWithHeading>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Point3DWithHeading& from);
  void MergeFrom(const Point3DWithHeading& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Point3DWithHeading* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "dr.base.Point3DWithHeading";
  }
  protected:
  explicit Point3DWithHeading(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_drapi_2fbase_2eproto);
    return ::descriptor_table_drapi_2fbase_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPointFieldNumber = 1,
    kHeadingFieldNumber = 2,
  };
  // .dr.base.Point3D point = 1;
  bool has_point() const;
  private:
  bool _internal_has_point() const;
  public:
  void clear_point();
  const ::dr::base::Point3D& point() const;
  ::dr::base::Point3D* release_point();
  ::dr::base::Point3D* mutable_point();
  void set_allocated_point(::dr::base::Point3D* point);
  private:
  const ::dr::base::Point3D& _internal_point() const;
  ::dr::base::Point3D* _internal_mutable_point();
  public:
  void unsafe_arena_set_allocated_point(
      ::dr::base::Point3D* point);
  ::dr::base::Point3D* unsafe_arena_release_point();

  // .dr.base.Point3D heading = 2;
  bool has_heading() const;
  private:
  bool _internal_has_heading() const;
  public:
  void clear_heading();
  const ::dr::base::Point3D& heading() const;
  ::dr::base::Point3D* release_heading();
  ::dr::base::Point3D* mutable_heading();
  void set_allocated_heading(::dr::base::Point3D* heading);
  private:
  const ::dr::base::Point3D& _internal_heading() const;
  ::dr::base::Point3D* _internal_mutable_heading();
  public:
  void unsafe_arena_set_allocated_heading(
      ::dr::base::Point3D* heading);
  ::dr::base::Point3D* unsafe_arena_release_heading();

  // @@protoc_insertion_point(class_scope:dr.base.Point3DWithHeading)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::dr::base::Point3D* point_;
  ::dr::base::Point3D* heading_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_drapi_2fbase_2eproto;
};
// -------------------------------------------------------------------

class Polygon PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:dr.base.Polygon) */ {
 public:
  inline Polygon() : Polygon(nullptr) {}
  virtual ~Polygon();

  Polygon(const Polygon& from);
  Polygon(Polygon&& from) noexcept
    : Polygon() {
    *this = ::std::move(from);
  }

  inline Polygon& operator=(const Polygon& from) {
    CopyFrom(from);
    return *this;
  }
  inline Polygon& operator=(Polygon&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Polygon& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Polygon* internal_default_instance() {
    return reinterpret_cast<const Polygon*>(
               &_Polygon_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(Polygon& a, Polygon& b) {
    a.Swap(&b);
  }
  inline void Swap(Polygon* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Polygon* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Polygon* New() const final {
    return CreateMaybeMessage<Polygon>(nullptr);
  }

  Polygon* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Polygon>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Polygon& from);
  void MergeFrom(const Polygon& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Polygon* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "dr.base.Polygon";
  }
  protected:
  explicit Polygon(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_drapi_2fbase_2eproto);
    return ::descriptor_table_drapi_2fbase_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPointFieldNumber = 1,
  };
  // repeated .dr.base.Point3D point = 1;
  int point_size() const;
  private:
  int _internal_point_size() const;
  public:
  void clear_point();
  ::dr::base::Point3D* mutable_point(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::dr::base::Point3D >*
      mutable_point();
  private:
  const ::dr::base::Point3D& _internal_point(int index) const;
  ::dr::base::Point3D* _internal_add_point();
  public:
  const ::dr::base::Point3D& point(int index) const;
  ::dr::base::Point3D* add_point();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::dr::base::Point3D >&
      point() const;

  // @@protoc_insertion_point(class_scope:dr.base.Polygon)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::dr::base::Point3D > point_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_drapi_2fbase_2eproto;
};
// -------------------------------------------------------------------

class Polyline PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:dr.base.Polyline) */ {
 public:
  inline Polyline() : Polyline(nullptr) {}
  virtual ~Polyline();

  Polyline(const Polyline& from);
  Polyline(Polyline&& from) noexcept
    : Polyline() {
    *this = ::std::move(from);
  }

  inline Polyline& operator=(const Polyline& from) {
    CopyFrom(from);
    return *this;
  }
  inline Polyline& operator=(Polyline&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Polyline& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Polyline* internal_default_instance() {
    return reinterpret_cast<const Polyline*>(
               &_Polyline_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(Polyline& a, Polyline& b) {
    a.Swap(&b);
  }
  inline void Swap(Polyline* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Polyline* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Polyline* New() const final {
    return CreateMaybeMessage<Polyline>(nullptr);
  }

  Polyline* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Polyline>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Polyline& from);
  void MergeFrom(const Polyline& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Polyline* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "dr.base.Polyline";
  }
  protected:
  explicit Polyline(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_drapi_2fbase_2eproto);
    return ::descriptor_table_drapi_2fbase_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPointFieldNumber = 1,
  };
  // repeated .dr.base.Point3D point = 1;
  int point_size() const;
  private:
  int _internal_point_size() const;
  public:
  void clear_point();
  ::dr::base::Point3D* mutable_point(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::dr::base::Point3D >*
      mutable_point();
  private:
  const ::dr::base::Point3D& _internal_point(int index) const;
  ::dr::base::Point3D* _internal_add_point();
  public:
  const ::dr::base::Point3D& point(int index) const;
  ::dr::base::Point3D* add_point();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::dr::base::Point3D >&
      point() const;

  // @@protoc_insertion_point(class_scope:dr.base.Polyline)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::dr::base::Point3D > point_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_drapi_2fbase_2eproto;
};
// -------------------------------------------------------------------

class ParkingSpace PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:dr.base.ParkingSpace) */ {
 public:
  inline ParkingSpace() : ParkingSpace(nullptr) {}
  virtual ~ParkingSpace();

  ParkingSpace(const ParkingSpace& from);
  ParkingSpace(ParkingSpace&& from) noexcept
    : ParkingSpace() {
    *this = ::std::move(from);
  }

  inline ParkingSpace& operator=(const ParkingSpace& from) {
    CopyFrom(from);
    return *this;
  }
  inline ParkingSpace& operator=(ParkingSpace&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ParkingSpace& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ParkingSpace* internal_default_instance() {
    return reinterpret_cast<const ParkingSpace*>(
               &_ParkingSpace_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  friend void swap(ParkingSpace& a, ParkingSpace& b) {
    a.Swap(&b);
  }
  inline void Swap(ParkingSpace* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ParkingSpace* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ParkingSpace* New() const final {
    return CreateMaybeMessage<ParkingSpace>(nullptr);
  }

  ParkingSpace* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ParkingSpace>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ParkingSpace& from);
  void MergeFrom(const ParkingSpace& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ParkingSpace* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "dr.base.ParkingSpace";
  }
  protected:
  explicit ParkingSpace(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_drapi_2fbase_2eproto);
    return ::descriptor_table_drapi_2fbase_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef ParkingSpace_ParkingSpaceType ParkingSpaceType;
  static constexpr ParkingSpaceType UNKNOWN =
    ParkingSpace_ParkingSpaceType_UNKNOWN;
  static constexpr ParkingSpaceType VERTICAL =
    ParkingSpace_ParkingSpaceType_VERTICAL;
  static constexpr ParkingSpaceType PARALLEL =
    ParkingSpace_ParkingSpaceType_PARALLEL;
  static constexpr ParkingSpaceType SLANTED =
    ParkingSpace_ParkingSpaceType_SLANTED;
  static inline bool ParkingSpaceType_IsValid(int value) {
    return ParkingSpace_ParkingSpaceType_IsValid(value);
  }
  static constexpr ParkingSpaceType ParkingSpaceType_MIN =
    ParkingSpace_ParkingSpaceType_ParkingSpaceType_MIN;
  static constexpr ParkingSpaceType ParkingSpaceType_MAX =
    ParkingSpace_ParkingSpaceType_ParkingSpaceType_MAX;
  static constexpr int ParkingSpaceType_ARRAYSIZE =
    ParkingSpace_ParkingSpaceType_ParkingSpaceType_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  ParkingSpaceType_descriptor() {
    return ParkingSpace_ParkingSpaceType_descriptor();
  }
  template<typename T>
  static inline const std::string& ParkingSpaceType_Name(T enum_t_value) {
    static_assert(::std::is_same<T, ParkingSpaceType>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function ParkingSpaceType_Name.");
    return ParkingSpace_ParkingSpaceType_Name(enum_t_value);
  }
  static inline bool ParkingSpaceType_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      ParkingSpaceType* value) {
    return ParkingSpace_ParkingSpaceType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kPolygonFieldNumber = 2,
    kCenterPointFieldNumber = 3,
    kIdFieldNumber = 1,
    kIsEmptyFieldNumber = 5,
    kHeadingFieldNumber = 4,
    kLayerFieldNumber = 6,
    kParkingSpaceTypeFieldNumber = 7,
  };
  // .dr.base.Polygon polygon = 2;
  bool has_polygon() const;
  private:
  bool _internal_has_polygon() const;
  public:
  void clear_polygon();
  const ::dr::base::Polygon& polygon() const;
  ::dr::base::Polygon* release_polygon();
  ::dr::base::Polygon* mutable_polygon();
  void set_allocated_polygon(::dr::base::Polygon* polygon);
  private:
  const ::dr::base::Polygon& _internal_polygon() const;
  ::dr::base::Polygon* _internal_mutable_polygon();
  public:
  void unsafe_arena_set_allocated_polygon(
      ::dr::base::Polygon* polygon);
  ::dr::base::Polygon* unsafe_arena_release_polygon();

  // .dr.base.Point3D center_point = 3;
  bool has_center_point() const;
  private:
  bool _internal_has_center_point() const;
  public:
  void clear_center_point();
  const ::dr::base::Point3D& center_point() const;
  ::dr::base::Point3D* release_center_point();
  ::dr::base::Point3D* mutable_center_point();
  void set_allocated_center_point(::dr::base::Point3D* center_point);
  private:
  const ::dr::base::Point3D& _internal_center_point() const;
  ::dr::base::Point3D* _internal_mutable_center_point();
  public:
  void unsafe_arena_set_allocated_center_point(
      ::dr::base::Point3D* center_point);
  ::dr::base::Point3D* unsafe_arena_release_center_point();

  // int32 id = 1;
  void clear_id();
  ::PROTOBUF_NAMESPACE_ID::int32 id() const;
  void set_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_id() const;
  void _internal_set_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // bool is_empty = 5;
  void clear_is_empty();
  bool is_empty() const;
  void set_is_empty(bool value);
  private:
  bool _internal_is_empty() const;
  void _internal_set_is_empty(bool value);
  public:

  // double heading = 4;
  void clear_heading();
  double heading() const;
  void set_heading(double value);
  private:
  double _internal_heading() const;
  void _internal_set_heading(double value);
  public:

  // int32 layer = 6;
  void clear_layer();
  ::PROTOBUF_NAMESPACE_ID::int32 layer() const;
  void set_layer(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_layer() const;
  void _internal_set_layer(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // .dr.base.ParkingSpace.ParkingSpaceType parking_space_type = 7;
  void clear_parking_space_type();
  ::dr::base::ParkingSpace_ParkingSpaceType parking_space_type() const;
  void set_parking_space_type(::dr::base::ParkingSpace_ParkingSpaceType value);
  private:
  ::dr::base::ParkingSpace_ParkingSpaceType _internal_parking_space_type() const;
  void _internal_set_parking_space_type(::dr::base::ParkingSpace_ParkingSpaceType value);
  public:

  // @@protoc_insertion_point(class_scope:dr.base.ParkingSpace)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::dr::base::Polygon* polygon_;
  ::dr::base::Point3D* center_point_;
  ::PROTOBUF_NAMESPACE_ID::int32 id_;
  bool is_empty_;
  double heading_;
  ::PROTOBUF_NAMESPACE_ID::int32 layer_;
  int parking_space_type_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_drapi_2fbase_2eproto;
};
// -------------------------------------------------------------------

class RotatedRect PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:dr.base.RotatedRect) */ {
 public:
  inline RotatedRect() : RotatedRect(nullptr) {}
  virtual ~RotatedRect();

  RotatedRect(const RotatedRect& from);
  RotatedRect(RotatedRect&& from) noexcept
    : RotatedRect() {
    *this = ::std::move(from);
  }

  inline RotatedRect& operator=(const RotatedRect& from) {
    CopyFrom(from);
    return *this;
  }
  inline RotatedRect& operator=(RotatedRect&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const RotatedRect& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RotatedRect* internal_default_instance() {
    return reinterpret_cast<const RotatedRect*>(
               &_RotatedRect_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    8;

  friend void swap(RotatedRect& a, RotatedRect& b) {
    a.Swap(&b);
  }
  inline void Swap(RotatedRect* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RotatedRect* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline RotatedRect* New() const final {
    return CreateMaybeMessage<RotatedRect>(nullptr);
  }

  RotatedRect* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<RotatedRect>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const RotatedRect& from);
  void MergeFrom(const RotatedRect& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RotatedRect* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "dr.base.RotatedRect";
  }
  protected:
  explicit RotatedRect(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_drapi_2fbase_2eproto);
    return ::descriptor_table_drapi_2fbase_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCenterFieldNumber = 1,
    kSizeFieldNumber = 2,
    kAngleFieldNumber = 3,
  };
  // .dr.base.Point2D center = 1;
  bool has_center() const;
  private:
  bool _internal_has_center() const;
  public:
  void clear_center();
  const ::dr::base::Point2D& center() const;
  ::dr::base::Point2D* release_center();
  ::dr::base::Point2D* mutable_center();
  void set_allocated_center(::dr::base::Point2D* center);
  private:
  const ::dr::base::Point2D& _internal_center() const;
  ::dr::base::Point2D* _internal_mutable_center();
  public:
  void unsafe_arena_set_allocated_center(
      ::dr::base::Point2D* center);
  ::dr::base::Point2D* unsafe_arena_release_center();

  // .dr.base.Point2D size = 2;
  bool has_size() const;
  private:
  bool _internal_has_size() const;
  public:
  void clear_size();
  const ::dr::base::Point2D& size() const;
  ::dr::base::Point2D* release_size();
  ::dr::base::Point2D* mutable_size();
  void set_allocated_size(::dr::base::Point2D* size);
  private:
  const ::dr::base::Point2D& _internal_size() const;
  ::dr::base::Point2D* _internal_mutable_size();
  public:
  void unsafe_arena_set_allocated_size(
      ::dr::base::Point2D* size);
  ::dr::base::Point2D* unsafe_arena_release_size();

  // float angle = 3;
  void clear_angle();
  float angle() const;
  void set_angle(float value);
  private:
  float _internal_angle() const;
  void _internal_set_angle(float value);
  public:

  // @@protoc_insertion_point(class_scope:dr.base.RotatedRect)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::dr::base::Point2D* center_;
  ::dr::base::Point2D* size_;
  float angle_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_drapi_2fbase_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PointLLH

// double lon = 1;
inline void PointLLH::clear_lon() {
  lon_ = 0;
}
inline double PointLLH::_internal_lon() const {
  return lon_;
}
inline double PointLLH::lon() const {
  // @@protoc_insertion_point(field_get:dr.base.PointLLH.lon)
  return _internal_lon();
}
inline void PointLLH::_internal_set_lon(double value) {
  
  lon_ = value;
}
inline void PointLLH::set_lon(double value) {
  _internal_set_lon(value);
  // @@protoc_insertion_point(field_set:dr.base.PointLLH.lon)
}

// double lat = 2;
inline void PointLLH::clear_lat() {
  lat_ = 0;
}
inline double PointLLH::_internal_lat() const {
  return lat_;
}
inline double PointLLH::lat() const {
  // @@protoc_insertion_point(field_get:dr.base.PointLLH.lat)
  return _internal_lat();
}
inline void PointLLH::_internal_set_lat(double value) {
  
  lat_ = value;
}
inline void PointLLH::set_lat(double value) {
  _internal_set_lat(value);
  // @@protoc_insertion_point(field_set:dr.base.PointLLH.lat)
}

// double height = 3;
inline void PointLLH::clear_height() {
  height_ = 0;
}
inline double PointLLH::_internal_height() const {
  return height_;
}
inline double PointLLH::height() const {
  // @@protoc_insertion_point(field_get:dr.base.PointLLH.height)
  return _internal_height();
}
inline void PointLLH::_internal_set_height(double value) {
  
  height_ = value;
}
inline void PointLLH::set_height(double value) {
  _internal_set_height(value);
  // @@protoc_insertion_point(field_set:dr.base.PointLLH.height)
}

// -------------------------------------------------------------------

// Point2D

// double x = 1;
inline void Point2D::clear_x() {
  x_ = 0;
}
inline double Point2D::_internal_x() const {
  return x_;
}
inline double Point2D::x() const {
  // @@protoc_insertion_point(field_get:dr.base.Point2D.x)
  return _internal_x();
}
inline void Point2D::_internal_set_x(double value) {
  
  x_ = value;
}
inline void Point2D::set_x(double value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:dr.base.Point2D.x)
}

// double y = 2;
inline void Point2D::clear_y() {
  y_ = 0;
}
inline double Point2D::_internal_y() const {
  return y_;
}
inline double Point2D::y() const {
  // @@protoc_insertion_point(field_get:dr.base.Point2D.y)
  return _internal_y();
}
inline void Point2D::_internal_set_y(double value) {
  
  y_ = value;
}
inline void Point2D::set_y(double value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:dr.base.Point2D.y)
}

// -------------------------------------------------------------------

// Point2DWithHeading

// .dr.base.Point2D point = 1;
inline bool Point2DWithHeading::_internal_has_point() const {
  return this != internal_default_instance() && point_ != nullptr;
}
inline bool Point2DWithHeading::has_point() const {
  return _internal_has_point();
}
inline void Point2DWithHeading::clear_point() {
  if (GetArena() == nullptr && point_ != nullptr) {
    delete point_;
  }
  point_ = nullptr;
}
inline const ::dr::base::Point2D& Point2DWithHeading::_internal_point() const {
  const ::dr::base::Point2D* p = point_;
  return p != nullptr ? *p : *reinterpret_cast<const ::dr::base::Point2D*>(
      &::dr::base::_Point2D_default_instance_);
}
inline const ::dr::base::Point2D& Point2DWithHeading::point() const {
  // @@protoc_insertion_point(field_get:dr.base.Point2DWithHeading.point)
  return _internal_point();
}
inline void Point2DWithHeading::unsafe_arena_set_allocated_point(
    ::dr::base::Point2D* point) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(point_);
  }
  point_ = point;
  if (point) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:dr.base.Point2DWithHeading.point)
}
inline ::dr::base::Point2D* Point2DWithHeading::release_point() {
  
  ::dr::base::Point2D* temp = point_;
  point_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::dr::base::Point2D* Point2DWithHeading::unsafe_arena_release_point() {
  // @@protoc_insertion_point(field_release:dr.base.Point2DWithHeading.point)
  
  ::dr::base::Point2D* temp = point_;
  point_ = nullptr;
  return temp;
}
inline ::dr::base::Point2D* Point2DWithHeading::_internal_mutable_point() {
  
  if (point_ == nullptr) {
    auto* p = CreateMaybeMessage<::dr::base::Point2D>(GetArena());
    point_ = p;
  }
  return point_;
}
inline ::dr::base::Point2D* Point2DWithHeading::mutable_point() {
  // @@protoc_insertion_point(field_mutable:dr.base.Point2DWithHeading.point)
  return _internal_mutable_point();
}
inline void Point2DWithHeading::set_allocated_point(::dr::base::Point2D* point) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete point_;
  }
  if (point) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(point);
    if (message_arena != submessage_arena) {
      point = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, point, submessage_arena);
    }
    
  } else {
    
  }
  point_ = point;
  // @@protoc_insertion_point(field_set_allocated:dr.base.Point2DWithHeading.point)
}

// double heading = 2;
inline void Point2DWithHeading::clear_heading() {
  heading_ = 0;
}
inline double Point2DWithHeading::_internal_heading() const {
  return heading_;
}
inline double Point2DWithHeading::heading() const {
  // @@protoc_insertion_point(field_get:dr.base.Point2DWithHeading.heading)
  return _internal_heading();
}
inline void Point2DWithHeading::_internal_set_heading(double value) {
  
  heading_ = value;
}
inline void Point2DWithHeading::set_heading(double value) {
  _internal_set_heading(value);
  // @@protoc_insertion_point(field_set:dr.base.Point2DWithHeading.heading)
}

// -------------------------------------------------------------------

// Point3D

// double x = 1;
inline void Point3D::clear_x() {
  x_ = 0;
}
inline double Point3D::_internal_x() const {
  return x_;
}
inline double Point3D::x() const {
  // @@protoc_insertion_point(field_get:dr.base.Point3D.x)
  return _internal_x();
}
inline void Point3D::_internal_set_x(double value) {
  
  x_ = value;
}
inline void Point3D::set_x(double value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:dr.base.Point3D.x)
}

// double y = 2;
inline void Point3D::clear_y() {
  y_ = 0;
}
inline double Point3D::_internal_y() const {
  return y_;
}
inline double Point3D::y() const {
  // @@protoc_insertion_point(field_get:dr.base.Point3D.y)
  return _internal_y();
}
inline void Point3D::_internal_set_y(double value) {
  
  y_ = value;
}
inline void Point3D::set_y(double value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:dr.base.Point3D.y)
}

// double z = 3;
inline void Point3D::clear_z() {
  z_ = 0;
}
inline double Point3D::_internal_z() const {
  return z_;
}
inline double Point3D::z() const {
  // @@protoc_insertion_point(field_get:dr.base.Point3D.z)
  return _internal_z();
}
inline void Point3D::_internal_set_z(double value) {
  
  z_ = value;
}
inline void Point3D::set_z(double value) {
  _internal_set_z(value);
  // @@protoc_insertion_point(field_set:dr.base.Point3D.z)
}

// -------------------------------------------------------------------

// Point3DWithHeading

// .dr.base.Point3D point = 1;
inline bool Point3DWithHeading::_internal_has_point() const {
  return this != internal_default_instance() && point_ != nullptr;
}
inline bool Point3DWithHeading::has_point() const {
  return _internal_has_point();
}
inline void Point3DWithHeading::clear_point() {
  if (GetArena() == nullptr && point_ != nullptr) {
    delete point_;
  }
  point_ = nullptr;
}
inline const ::dr::base::Point3D& Point3DWithHeading::_internal_point() const {
  const ::dr::base::Point3D* p = point_;
  return p != nullptr ? *p : *reinterpret_cast<const ::dr::base::Point3D*>(
      &::dr::base::_Point3D_default_instance_);
}
inline const ::dr::base::Point3D& Point3DWithHeading::point() const {
  // @@protoc_insertion_point(field_get:dr.base.Point3DWithHeading.point)
  return _internal_point();
}
inline void Point3DWithHeading::unsafe_arena_set_allocated_point(
    ::dr::base::Point3D* point) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(point_);
  }
  point_ = point;
  if (point) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:dr.base.Point3DWithHeading.point)
}
inline ::dr::base::Point3D* Point3DWithHeading::release_point() {
  
  ::dr::base::Point3D* temp = point_;
  point_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::dr::base::Point3D* Point3DWithHeading::unsafe_arena_release_point() {
  // @@protoc_insertion_point(field_release:dr.base.Point3DWithHeading.point)
  
  ::dr::base::Point3D* temp = point_;
  point_ = nullptr;
  return temp;
}
inline ::dr::base::Point3D* Point3DWithHeading::_internal_mutable_point() {
  
  if (point_ == nullptr) {
    auto* p = CreateMaybeMessage<::dr::base::Point3D>(GetArena());
    point_ = p;
  }
  return point_;
}
inline ::dr::base::Point3D* Point3DWithHeading::mutable_point() {
  // @@protoc_insertion_point(field_mutable:dr.base.Point3DWithHeading.point)
  return _internal_mutable_point();
}
inline void Point3DWithHeading::set_allocated_point(::dr::base::Point3D* point) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete point_;
  }
  if (point) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(point);
    if (message_arena != submessage_arena) {
      point = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, point, submessage_arena);
    }
    
  } else {
    
  }
  point_ = point;
  // @@protoc_insertion_point(field_set_allocated:dr.base.Point3DWithHeading.point)
}

// .dr.base.Point3D heading = 2;
inline bool Point3DWithHeading::_internal_has_heading() const {
  return this != internal_default_instance() && heading_ != nullptr;
}
inline bool Point3DWithHeading::has_heading() const {
  return _internal_has_heading();
}
inline void Point3DWithHeading::clear_heading() {
  if (GetArena() == nullptr && heading_ != nullptr) {
    delete heading_;
  }
  heading_ = nullptr;
}
inline const ::dr::base::Point3D& Point3DWithHeading::_internal_heading() const {
  const ::dr::base::Point3D* p = heading_;
  return p != nullptr ? *p : *reinterpret_cast<const ::dr::base::Point3D*>(
      &::dr::base::_Point3D_default_instance_);
}
inline const ::dr::base::Point3D& Point3DWithHeading::heading() const {
  // @@protoc_insertion_point(field_get:dr.base.Point3DWithHeading.heading)
  return _internal_heading();
}
inline void Point3DWithHeading::unsafe_arena_set_allocated_heading(
    ::dr::base::Point3D* heading) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(heading_);
  }
  heading_ = heading;
  if (heading) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:dr.base.Point3DWithHeading.heading)
}
inline ::dr::base::Point3D* Point3DWithHeading::release_heading() {
  
  ::dr::base::Point3D* temp = heading_;
  heading_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::dr::base::Point3D* Point3DWithHeading::unsafe_arena_release_heading() {
  // @@protoc_insertion_point(field_release:dr.base.Point3DWithHeading.heading)
  
  ::dr::base::Point3D* temp = heading_;
  heading_ = nullptr;
  return temp;
}
inline ::dr::base::Point3D* Point3DWithHeading::_internal_mutable_heading() {
  
  if (heading_ == nullptr) {
    auto* p = CreateMaybeMessage<::dr::base::Point3D>(GetArena());
    heading_ = p;
  }
  return heading_;
}
inline ::dr::base::Point3D* Point3DWithHeading::mutable_heading() {
  // @@protoc_insertion_point(field_mutable:dr.base.Point3DWithHeading.heading)
  return _internal_mutable_heading();
}
inline void Point3DWithHeading::set_allocated_heading(::dr::base::Point3D* heading) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete heading_;
  }
  if (heading) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(heading);
    if (message_arena != submessage_arena) {
      heading = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, heading, submessage_arena);
    }
    
  } else {
    
  }
  heading_ = heading;
  // @@protoc_insertion_point(field_set_allocated:dr.base.Point3DWithHeading.heading)
}

// -------------------------------------------------------------------

// Polygon

// repeated .dr.base.Point3D point = 1;
inline int Polygon::_internal_point_size() const {
  return point_.size();
}
inline int Polygon::point_size() const {
  return _internal_point_size();
}
inline void Polygon::clear_point() {
  point_.Clear();
}
inline ::dr::base::Point3D* Polygon::mutable_point(int index) {
  // @@protoc_insertion_point(field_mutable:dr.base.Polygon.point)
  return point_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::dr::base::Point3D >*
Polygon::mutable_point() {
  // @@protoc_insertion_point(field_mutable_list:dr.base.Polygon.point)
  return &point_;
}
inline const ::dr::base::Point3D& Polygon::_internal_point(int index) const {
  return point_.Get(index);
}
inline const ::dr::base::Point3D& Polygon::point(int index) const {
  // @@protoc_insertion_point(field_get:dr.base.Polygon.point)
  return _internal_point(index);
}
inline ::dr::base::Point3D* Polygon::_internal_add_point() {
  return point_.Add();
}
inline ::dr::base::Point3D* Polygon::add_point() {
  // @@protoc_insertion_point(field_add:dr.base.Polygon.point)
  return _internal_add_point();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::dr::base::Point3D >&
Polygon::point() const {
  // @@protoc_insertion_point(field_list:dr.base.Polygon.point)
  return point_;
}

// -------------------------------------------------------------------

// Polyline

// repeated .dr.base.Point3D point = 1;
inline int Polyline::_internal_point_size() const {
  return point_.size();
}
inline int Polyline::point_size() const {
  return _internal_point_size();
}
inline void Polyline::clear_point() {
  point_.Clear();
}
inline ::dr::base::Point3D* Polyline::mutable_point(int index) {
  // @@protoc_insertion_point(field_mutable:dr.base.Polyline.point)
  return point_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::dr::base::Point3D >*
Polyline::mutable_point() {
  // @@protoc_insertion_point(field_mutable_list:dr.base.Polyline.point)
  return &point_;
}
inline const ::dr::base::Point3D& Polyline::_internal_point(int index) const {
  return point_.Get(index);
}
inline const ::dr::base::Point3D& Polyline::point(int index) const {
  // @@protoc_insertion_point(field_get:dr.base.Polyline.point)
  return _internal_point(index);
}
inline ::dr::base::Point3D* Polyline::_internal_add_point() {
  return point_.Add();
}
inline ::dr::base::Point3D* Polyline::add_point() {
  // @@protoc_insertion_point(field_add:dr.base.Polyline.point)
  return _internal_add_point();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::dr::base::Point3D >&
Polyline::point() const {
  // @@protoc_insertion_point(field_list:dr.base.Polyline.point)
  return point_;
}

// -------------------------------------------------------------------

// ParkingSpace

// int32 id = 1;
inline void ParkingSpace::clear_id() {
  id_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ParkingSpace::_internal_id() const {
  return id_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ParkingSpace::id() const {
  // @@protoc_insertion_point(field_get:dr.base.ParkingSpace.id)
  return _internal_id();
}
inline void ParkingSpace::_internal_set_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  id_ = value;
}
inline void ParkingSpace::set_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:dr.base.ParkingSpace.id)
}

// .dr.base.Polygon polygon = 2;
inline bool ParkingSpace::_internal_has_polygon() const {
  return this != internal_default_instance() && polygon_ != nullptr;
}
inline bool ParkingSpace::has_polygon() const {
  return _internal_has_polygon();
}
inline void ParkingSpace::clear_polygon() {
  if (GetArena() == nullptr && polygon_ != nullptr) {
    delete polygon_;
  }
  polygon_ = nullptr;
}
inline const ::dr::base::Polygon& ParkingSpace::_internal_polygon() const {
  const ::dr::base::Polygon* p = polygon_;
  return p != nullptr ? *p : *reinterpret_cast<const ::dr::base::Polygon*>(
      &::dr::base::_Polygon_default_instance_);
}
inline const ::dr::base::Polygon& ParkingSpace::polygon() const {
  // @@protoc_insertion_point(field_get:dr.base.ParkingSpace.polygon)
  return _internal_polygon();
}
inline void ParkingSpace::unsafe_arena_set_allocated_polygon(
    ::dr::base::Polygon* polygon) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(polygon_);
  }
  polygon_ = polygon;
  if (polygon) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:dr.base.ParkingSpace.polygon)
}
inline ::dr::base::Polygon* ParkingSpace::release_polygon() {
  
  ::dr::base::Polygon* temp = polygon_;
  polygon_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::dr::base::Polygon* ParkingSpace::unsafe_arena_release_polygon() {
  // @@protoc_insertion_point(field_release:dr.base.ParkingSpace.polygon)
  
  ::dr::base::Polygon* temp = polygon_;
  polygon_ = nullptr;
  return temp;
}
inline ::dr::base::Polygon* ParkingSpace::_internal_mutable_polygon() {
  
  if (polygon_ == nullptr) {
    auto* p = CreateMaybeMessage<::dr::base::Polygon>(GetArena());
    polygon_ = p;
  }
  return polygon_;
}
inline ::dr::base::Polygon* ParkingSpace::mutable_polygon() {
  // @@protoc_insertion_point(field_mutable:dr.base.ParkingSpace.polygon)
  return _internal_mutable_polygon();
}
inline void ParkingSpace::set_allocated_polygon(::dr::base::Polygon* polygon) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete polygon_;
  }
  if (polygon) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(polygon);
    if (message_arena != submessage_arena) {
      polygon = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, polygon, submessage_arena);
    }
    
  } else {
    
  }
  polygon_ = polygon;
  // @@protoc_insertion_point(field_set_allocated:dr.base.ParkingSpace.polygon)
}

// .dr.base.Point3D center_point = 3;
inline bool ParkingSpace::_internal_has_center_point() const {
  return this != internal_default_instance() && center_point_ != nullptr;
}
inline bool ParkingSpace::has_center_point() const {
  return _internal_has_center_point();
}
inline void ParkingSpace::clear_center_point() {
  if (GetArena() == nullptr && center_point_ != nullptr) {
    delete center_point_;
  }
  center_point_ = nullptr;
}
inline const ::dr::base::Point3D& ParkingSpace::_internal_center_point() const {
  const ::dr::base::Point3D* p = center_point_;
  return p != nullptr ? *p : *reinterpret_cast<const ::dr::base::Point3D*>(
      &::dr::base::_Point3D_default_instance_);
}
inline const ::dr::base::Point3D& ParkingSpace::center_point() const {
  // @@protoc_insertion_point(field_get:dr.base.ParkingSpace.center_point)
  return _internal_center_point();
}
inline void ParkingSpace::unsafe_arena_set_allocated_center_point(
    ::dr::base::Point3D* center_point) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(center_point_);
  }
  center_point_ = center_point;
  if (center_point) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:dr.base.ParkingSpace.center_point)
}
inline ::dr::base::Point3D* ParkingSpace::release_center_point() {
  
  ::dr::base::Point3D* temp = center_point_;
  center_point_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::dr::base::Point3D* ParkingSpace::unsafe_arena_release_center_point() {
  // @@protoc_insertion_point(field_release:dr.base.ParkingSpace.center_point)
  
  ::dr::base::Point3D* temp = center_point_;
  center_point_ = nullptr;
  return temp;
}
inline ::dr::base::Point3D* ParkingSpace::_internal_mutable_center_point() {
  
  if (center_point_ == nullptr) {
    auto* p = CreateMaybeMessage<::dr::base::Point3D>(GetArena());
    center_point_ = p;
  }
  return center_point_;
}
inline ::dr::base::Point3D* ParkingSpace::mutable_center_point() {
  // @@protoc_insertion_point(field_mutable:dr.base.ParkingSpace.center_point)
  return _internal_mutable_center_point();
}
inline void ParkingSpace::set_allocated_center_point(::dr::base::Point3D* center_point) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete center_point_;
  }
  if (center_point) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(center_point);
    if (message_arena != submessage_arena) {
      center_point = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, center_point, submessage_arena);
    }
    
  } else {
    
  }
  center_point_ = center_point;
  // @@protoc_insertion_point(field_set_allocated:dr.base.ParkingSpace.center_point)
}

// double heading = 4;
inline void ParkingSpace::clear_heading() {
  heading_ = 0;
}
inline double ParkingSpace::_internal_heading() const {
  return heading_;
}
inline double ParkingSpace::heading() const {
  // @@protoc_insertion_point(field_get:dr.base.ParkingSpace.heading)
  return _internal_heading();
}
inline void ParkingSpace::_internal_set_heading(double value) {
  
  heading_ = value;
}
inline void ParkingSpace::set_heading(double value) {
  _internal_set_heading(value);
  // @@protoc_insertion_point(field_set:dr.base.ParkingSpace.heading)
}

// bool is_empty = 5;
inline void ParkingSpace::clear_is_empty() {
  is_empty_ = false;
}
inline bool ParkingSpace::_internal_is_empty() const {
  return is_empty_;
}
inline bool ParkingSpace::is_empty() const {
  // @@protoc_insertion_point(field_get:dr.base.ParkingSpace.is_empty)
  return _internal_is_empty();
}
inline void ParkingSpace::_internal_set_is_empty(bool value) {
  
  is_empty_ = value;
}
inline void ParkingSpace::set_is_empty(bool value) {
  _internal_set_is_empty(value);
  // @@protoc_insertion_point(field_set:dr.base.ParkingSpace.is_empty)
}

// int32 layer = 6;
inline void ParkingSpace::clear_layer() {
  layer_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ParkingSpace::_internal_layer() const {
  return layer_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ParkingSpace::layer() const {
  // @@protoc_insertion_point(field_get:dr.base.ParkingSpace.layer)
  return _internal_layer();
}
inline void ParkingSpace::_internal_set_layer(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  layer_ = value;
}
inline void ParkingSpace::set_layer(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_layer(value);
  // @@protoc_insertion_point(field_set:dr.base.ParkingSpace.layer)
}

// .dr.base.ParkingSpace.ParkingSpaceType parking_space_type = 7;
inline void ParkingSpace::clear_parking_space_type() {
  parking_space_type_ = 0;
}
inline ::dr::base::ParkingSpace_ParkingSpaceType ParkingSpace::_internal_parking_space_type() const {
  return static_cast< ::dr::base::ParkingSpace_ParkingSpaceType >(parking_space_type_);
}
inline ::dr::base::ParkingSpace_ParkingSpaceType ParkingSpace::parking_space_type() const {
  // @@protoc_insertion_point(field_get:dr.base.ParkingSpace.parking_space_type)
  return _internal_parking_space_type();
}
inline void ParkingSpace::_internal_set_parking_space_type(::dr::base::ParkingSpace_ParkingSpaceType value) {
  
  parking_space_type_ = value;
}
inline void ParkingSpace::set_parking_space_type(::dr::base::ParkingSpace_ParkingSpaceType value) {
  _internal_set_parking_space_type(value);
  // @@protoc_insertion_point(field_set:dr.base.ParkingSpace.parking_space_type)
}

// -------------------------------------------------------------------

// RotatedRect

// .dr.base.Point2D center = 1;
inline bool RotatedRect::_internal_has_center() const {
  return this != internal_default_instance() && center_ != nullptr;
}
inline bool RotatedRect::has_center() const {
  return _internal_has_center();
}
inline void RotatedRect::clear_center() {
  if (GetArena() == nullptr && center_ != nullptr) {
    delete center_;
  }
  center_ = nullptr;
}
inline const ::dr::base::Point2D& RotatedRect::_internal_center() const {
  const ::dr::base::Point2D* p = center_;
  return p != nullptr ? *p : *reinterpret_cast<const ::dr::base::Point2D*>(
      &::dr::base::_Point2D_default_instance_);
}
inline const ::dr::base::Point2D& RotatedRect::center() const {
  // @@protoc_insertion_point(field_get:dr.base.RotatedRect.center)
  return _internal_center();
}
inline void RotatedRect::unsafe_arena_set_allocated_center(
    ::dr::base::Point2D* center) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(center_);
  }
  center_ = center;
  if (center) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:dr.base.RotatedRect.center)
}
inline ::dr::base::Point2D* RotatedRect::release_center() {
  
  ::dr::base::Point2D* temp = center_;
  center_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::dr::base::Point2D* RotatedRect::unsafe_arena_release_center() {
  // @@protoc_insertion_point(field_release:dr.base.RotatedRect.center)
  
  ::dr::base::Point2D* temp = center_;
  center_ = nullptr;
  return temp;
}
inline ::dr::base::Point2D* RotatedRect::_internal_mutable_center() {
  
  if (center_ == nullptr) {
    auto* p = CreateMaybeMessage<::dr::base::Point2D>(GetArena());
    center_ = p;
  }
  return center_;
}
inline ::dr::base::Point2D* RotatedRect::mutable_center() {
  // @@protoc_insertion_point(field_mutable:dr.base.RotatedRect.center)
  return _internal_mutable_center();
}
inline void RotatedRect::set_allocated_center(::dr::base::Point2D* center) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete center_;
  }
  if (center) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(center);
    if (message_arena != submessage_arena) {
      center = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, center, submessage_arena);
    }
    
  } else {
    
  }
  center_ = center;
  // @@protoc_insertion_point(field_set_allocated:dr.base.RotatedRect.center)
}

// .dr.base.Point2D size = 2;
inline bool RotatedRect::_internal_has_size() const {
  return this != internal_default_instance() && size_ != nullptr;
}
inline bool RotatedRect::has_size() const {
  return _internal_has_size();
}
inline void RotatedRect::clear_size() {
  if (GetArena() == nullptr && size_ != nullptr) {
    delete size_;
  }
  size_ = nullptr;
}
inline const ::dr::base::Point2D& RotatedRect::_internal_size() const {
  const ::dr::base::Point2D* p = size_;
  return p != nullptr ? *p : *reinterpret_cast<const ::dr::base::Point2D*>(
      &::dr::base::_Point2D_default_instance_);
}
inline const ::dr::base::Point2D& RotatedRect::size() const {
  // @@protoc_insertion_point(field_get:dr.base.RotatedRect.size)
  return _internal_size();
}
inline void RotatedRect::unsafe_arena_set_allocated_size(
    ::dr::base::Point2D* size) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(size_);
  }
  size_ = size;
  if (size) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:dr.base.RotatedRect.size)
}
inline ::dr::base::Point2D* RotatedRect::release_size() {
  
  ::dr::base::Point2D* temp = size_;
  size_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::dr::base::Point2D* RotatedRect::unsafe_arena_release_size() {
  // @@protoc_insertion_point(field_release:dr.base.RotatedRect.size)
  
  ::dr::base::Point2D* temp = size_;
  size_ = nullptr;
  return temp;
}
inline ::dr::base::Point2D* RotatedRect::_internal_mutable_size() {
  
  if (size_ == nullptr) {
    auto* p = CreateMaybeMessage<::dr::base::Point2D>(GetArena());
    size_ = p;
  }
  return size_;
}
inline ::dr::base::Point2D* RotatedRect::mutable_size() {
  // @@protoc_insertion_point(field_mutable:dr.base.RotatedRect.size)
  return _internal_mutable_size();
}
inline void RotatedRect::set_allocated_size(::dr::base::Point2D* size) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete size_;
  }
  if (size) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(size);
    if (message_arena != submessage_arena) {
      size = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, size, submessage_arena);
    }
    
  } else {
    
  }
  size_ = size;
  // @@protoc_insertion_point(field_set_allocated:dr.base.RotatedRect.size)
}

// float angle = 3;
inline void RotatedRect::clear_angle() {
  angle_ = 0;
}
inline float RotatedRect::_internal_angle() const {
  return angle_;
}
inline float RotatedRect::angle() const {
  // @@protoc_insertion_point(field_get:dr.base.RotatedRect.angle)
  return _internal_angle();
}
inline void RotatedRect::_internal_set_angle(float value) {
  
  angle_ = value;
}
inline void RotatedRect::set_angle(float value) {
  _internal_set_angle(value);
  // @@protoc_insertion_point(field_set:dr.base.RotatedRect.angle)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace base
}  // namespace dr

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::dr::base::ParkingSpace_ParkingSpaceType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::dr::base::ParkingSpace_ParkingSpaceType>() {
  return ::dr::base::ParkingSpace_ParkingSpaceType_descriptor();
}
template <> struct is_proto_enum< ::dr::base::ErrorCode> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::dr::base::ErrorCode>() {
  return ::dr::base::ErrorCode_descriptor();
}
template <> struct is_proto_enum< ::dr::base::CoorSys> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::dr::base::CoorSys>() {
  return ::dr::base::CoorSys_descriptor();
}
template <> struct is_proto_enum< ::dr::base::GearPosition> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::dr::base::GearPosition>() {
  return ::dr::base::GearPosition_descriptor();
}
template <> struct is_proto_enum< ::dr::base::Color> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::dr::base::Color>() {
  return ::dr::base::Color_descriptor();
}
template <> struct is_proto_enum< ::dr::base::Direction> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::dr::base::Direction>() {
  return ::dr::base::Direction_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_drapi_2fbase_2eproto
