# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: drapi/gl/gl_canfd.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'drapi/gl/gl_canfd.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from canbus import gl_p177_chassis_detail_pb2 as canbus_dot_gl__p177__chassis__detail__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x64rapi/gl/gl_canfd.proto\x12\x08gl.canfd\x1a#canbus/gl_p177_chassis_detail.proto\"\xc6\x03\n\x0b\x44taToCanbus\x12H\n\radcu_fr10_1b5\x18\x01 \x01(\x0b\x32\x31.deeproute.canbus.gl.p177.ADCU_ZCUCANFD1_FR10_1B5\x12H\n\radcu_fr04_1a0\x18\x02 \x01(\x0b\x32\x31.deeproute.canbus.gl.p177.ADCU_ZCUCANFD1_FR04_1A0\x12H\n\radcu_fr02_1f0\x18\x03 \x01(\x0b\x32\x31.deeproute.canbus.gl.p177.ADCU_ZCUCANFD1_FR02_1F0\x12H\n\radcu_fr06_1ff\x18\x04 \x01(\x0b\x32\x31.deeproute.canbus.gl.p177.ADCU_ZCUCANFD1_FR06_1FF\x12H\n\radcu_fr11_1e0\x18\x05 \x01(\x0b\x32\x31.deeproute.canbus.gl.p177.ADCU_ZCUCANFD1_FR11_1E0\x12\x45\n\x0cpas_fr15_24b\x18\x06 \x01(\x0b\x32/.deeproute.canbus.gl.p177.PASZCUCANFD1_FR15_24B')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'drapi.gl.gl_canfd_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DTATOCANBUS']._serialized_start=75
  _globals['_DTATOCANBUS']._serialized_end=529
# @@protoc_insertion_point(module_scope)
