# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: semantic_map/map_road_mask.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common import geometry_pb2 as common_dot_geometry__pb2
from semantic_map import map_overlap_pb2 as semantic__map_dot_map__overlap__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='semantic_map/map_road_mask.proto',
  package='deeproute.hdmap',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n semantic_map/map_road_mask.proto\x12\x0f\x64\x65\x65proute.hdmap\x1a\x15\x63ommon/geometry.proto\x1a\x1esemantic_map/map_overlap.proto\"}\n\x08RoadMask\x12\n\n\x02id\x18\x01 \x01(\x05\x12*\n\x07polygon\x18\x02 \x01(\x0b\x32\x19.deeproute.common.Polygon\x12\r\n\x05layer\x18\x03 \x01(\x05\x12*\n\x08overlaps\x18\x04 \x03(\x0b\x32\x18.deeproute.hdmap.Overlap')
  ,
  dependencies=[common_dot_geometry__pb2.DESCRIPTOR,semantic__map_dot_map__overlap__pb2.DESCRIPTOR,])




_ROADMASK = _descriptor.Descriptor(
  name='RoadMask',
  full_name='deeproute.hdmap.RoadMask',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='deeproute.hdmap.RoadMask.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='polygon', full_name='deeproute.hdmap.RoadMask.polygon', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='layer', full_name='deeproute.hdmap.RoadMask.layer', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='overlaps', full_name='deeproute.hdmap.RoadMask.overlaps', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=233,
)

_ROADMASK.fields_by_name['polygon'].message_type = common_dot_geometry__pb2._POLYGON
_ROADMASK.fields_by_name['overlaps'].message_type = semantic__map_dot_map__overlap__pb2._OVERLAP
DESCRIPTOR.message_types_by_name['RoadMask'] = _ROADMASK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RoadMask = _reflection.GeneratedProtocolMessageType('RoadMask', (_message.Message,), dict(
  DESCRIPTOR = _ROADMASK,
  __module__ = 'semantic_map.map_road_mask_pb2'
  # @@protoc_insertion_point(class_scope:deeproute.hdmap.RoadMask)
  ))
_sym_db.RegisterMessage(RoadMask)


# @@protoc_insertion_point(module_scope)
