// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: canbus/byd_tang_detail.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_canbus_2fbyd_5ftang_5fdetail_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_canbus_2fbyd_5ftang_5fdetail_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3013000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3013000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "canbus/byd_tang_adas_detail.pb.h"
#include "canbus/byd_tang_chassis_detail.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_canbus_2fbyd_5ftang_5fdetail_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_canbus_2fbyd_5ftang_5fdetail_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_canbus_2fbyd_5ftang_5fdetail_2eproto;
namespace deeproute {
namespace canbus {
class BydTangDetail;
class BydTangDetailDefaultTypeInternal;
extern BydTangDetailDefaultTypeInternal _BydTangDetail_default_instance_;
}  // namespace canbus
}  // namespace deeproute
PROTOBUF_NAMESPACE_OPEN
template<> ::deeproute::canbus::BydTangDetail* Arena::CreateMaybeMessage<::deeproute::canbus::BydTangDetail>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace deeproute {
namespace canbus {

// ===================================================================

class BydTangDetail PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:deeproute.canbus.BydTangDetail) */ {
 public:
  inline BydTangDetail() : BydTangDetail(nullptr) {}
  virtual ~BydTangDetail();

  BydTangDetail(const BydTangDetail& from);
  BydTangDetail(BydTangDetail&& from) noexcept
    : BydTangDetail() {
    *this = ::std::move(from);
  }

  inline BydTangDetail& operator=(const BydTangDetail& from) {
    CopyFrom(from);
    return *this;
  }
  inline BydTangDetail& operator=(BydTangDetail&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const BydTangDetail& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const BydTangDetail* internal_default_instance() {
    return reinterpret_cast<const BydTangDetail*>(
               &_BydTangDetail_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(BydTangDetail& a, BydTangDetail& b) {
    a.Swap(&b);
  }
  inline void Swap(BydTangDetail* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BydTangDetail* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline BydTangDetail* New() const final {
    return CreateMaybeMessage<BydTangDetail>(nullptr);
  }

  BydTangDetail* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<BydTangDetail>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const BydTangDetail& from);
  void MergeFrom(const BydTangDetail& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BydTangDetail* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "deeproute.canbus.BydTangDetail";
  }
  protected:
  explicit BydTangDetail(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_canbus_2fbyd_5ftang_5fdetail_2eproto);
    return ::descriptor_table_canbus_2fbyd_5ftang_5fdetail_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAdasFieldNumber = 1,
    kChassisFieldNumber = 2,
  };
  // optional .deeproute.canbus.BydTangAdasDetail adas = 1;
  bool has_adas() const;
  private:
  bool _internal_has_adas() const;
  public:
  void clear_adas();
  const ::deeproute::canbus::BydTangAdasDetail& adas() const;
  ::deeproute::canbus::BydTangAdasDetail* release_adas();
  ::deeproute::canbus::BydTangAdasDetail* mutable_adas();
  void set_allocated_adas(::deeproute::canbus::BydTangAdasDetail* adas);
  private:
  const ::deeproute::canbus::BydTangAdasDetail& _internal_adas() const;
  ::deeproute::canbus::BydTangAdasDetail* _internal_mutable_adas();
  public:
  void unsafe_arena_set_allocated_adas(
      ::deeproute::canbus::BydTangAdasDetail* adas);
  ::deeproute::canbus::BydTangAdasDetail* unsafe_arena_release_adas();

  // optional .deeproute.canbus.BydTangChassisDetail chassis = 2;
  bool has_chassis() const;
  private:
  bool _internal_has_chassis() const;
  public:
  void clear_chassis();
  const ::deeproute::canbus::BydTangChassisDetail& chassis() const;
  ::deeproute::canbus::BydTangChassisDetail* release_chassis();
  ::deeproute::canbus::BydTangChassisDetail* mutable_chassis();
  void set_allocated_chassis(::deeproute::canbus::BydTangChassisDetail* chassis);
  private:
  const ::deeproute::canbus::BydTangChassisDetail& _internal_chassis() const;
  ::deeproute::canbus::BydTangChassisDetail* _internal_mutable_chassis();
  public:
  void unsafe_arena_set_allocated_chassis(
      ::deeproute::canbus::BydTangChassisDetail* chassis);
  ::deeproute::canbus::BydTangChassisDetail* unsafe_arena_release_chassis();

  // @@protoc_insertion_point(class_scope:deeproute.canbus.BydTangDetail)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::deeproute::canbus::BydTangAdasDetail* adas_;
  ::deeproute::canbus::BydTangChassisDetail* chassis_;
  friend struct ::TableStruct_canbus_2fbyd_5ftang_5fdetail_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// BydTangDetail

// optional .deeproute.canbus.BydTangAdasDetail adas = 1;
inline bool BydTangDetail::_internal_has_adas() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || adas_ != nullptr);
  return value;
}
inline bool BydTangDetail::has_adas() const {
  return _internal_has_adas();
}
inline const ::deeproute::canbus::BydTangAdasDetail& BydTangDetail::_internal_adas() const {
  const ::deeproute::canbus::BydTangAdasDetail* p = adas_;
  return p != nullptr ? *p : *reinterpret_cast<const ::deeproute::canbus::BydTangAdasDetail*>(
      &::deeproute::canbus::_BydTangAdasDetail_default_instance_);
}
inline const ::deeproute::canbus::BydTangAdasDetail& BydTangDetail::adas() const {
  // @@protoc_insertion_point(field_get:deeproute.canbus.BydTangDetail.adas)
  return _internal_adas();
}
inline void BydTangDetail::unsafe_arena_set_allocated_adas(
    ::deeproute::canbus::BydTangAdasDetail* adas) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(adas_);
  }
  adas_ = adas;
  if (adas) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:deeproute.canbus.BydTangDetail.adas)
}
inline ::deeproute::canbus::BydTangAdasDetail* BydTangDetail::release_adas() {
  _has_bits_[0] &= ~0x00000001u;
  ::deeproute::canbus::BydTangAdasDetail* temp = adas_;
  adas_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::deeproute::canbus::BydTangAdasDetail* BydTangDetail::unsafe_arena_release_adas() {
  // @@protoc_insertion_point(field_release:deeproute.canbus.BydTangDetail.adas)
  _has_bits_[0] &= ~0x00000001u;
  ::deeproute::canbus::BydTangAdasDetail* temp = adas_;
  adas_ = nullptr;
  return temp;
}
inline ::deeproute::canbus::BydTangAdasDetail* BydTangDetail::_internal_mutable_adas() {
  _has_bits_[0] |= 0x00000001u;
  if (adas_ == nullptr) {
    auto* p = CreateMaybeMessage<::deeproute::canbus::BydTangAdasDetail>(GetArena());
    adas_ = p;
  }
  return adas_;
}
inline ::deeproute::canbus::BydTangAdasDetail* BydTangDetail::mutable_adas() {
  // @@protoc_insertion_point(field_mutable:deeproute.canbus.BydTangDetail.adas)
  return _internal_mutable_adas();
}
inline void BydTangDetail::set_allocated_adas(::deeproute::canbus::BydTangAdasDetail* adas) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(adas_);
  }
  if (adas) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(adas)->GetArena();
    if (message_arena != submessage_arena) {
      adas = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, adas, submessage_arena);
    }
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  adas_ = adas;
  // @@protoc_insertion_point(field_set_allocated:deeproute.canbus.BydTangDetail.adas)
}

// optional .deeproute.canbus.BydTangChassisDetail chassis = 2;
inline bool BydTangDetail::_internal_has_chassis() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || chassis_ != nullptr);
  return value;
}
inline bool BydTangDetail::has_chassis() const {
  return _internal_has_chassis();
}
inline const ::deeproute::canbus::BydTangChassisDetail& BydTangDetail::_internal_chassis() const {
  const ::deeproute::canbus::BydTangChassisDetail* p = chassis_;
  return p != nullptr ? *p : *reinterpret_cast<const ::deeproute::canbus::BydTangChassisDetail*>(
      &::deeproute::canbus::_BydTangChassisDetail_default_instance_);
}
inline const ::deeproute::canbus::BydTangChassisDetail& BydTangDetail::chassis() const {
  // @@protoc_insertion_point(field_get:deeproute.canbus.BydTangDetail.chassis)
  return _internal_chassis();
}
inline void BydTangDetail::unsafe_arena_set_allocated_chassis(
    ::deeproute::canbus::BydTangChassisDetail* chassis) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(chassis_);
  }
  chassis_ = chassis;
  if (chassis) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:deeproute.canbus.BydTangDetail.chassis)
}
inline ::deeproute::canbus::BydTangChassisDetail* BydTangDetail::release_chassis() {
  _has_bits_[0] &= ~0x00000002u;
  ::deeproute::canbus::BydTangChassisDetail* temp = chassis_;
  chassis_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::deeproute::canbus::BydTangChassisDetail* BydTangDetail::unsafe_arena_release_chassis() {
  // @@protoc_insertion_point(field_release:deeproute.canbus.BydTangDetail.chassis)
  _has_bits_[0] &= ~0x00000002u;
  ::deeproute::canbus::BydTangChassisDetail* temp = chassis_;
  chassis_ = nullptr;
  return temp;
}
inline ::deeproute::canbus::BydTangChassisDetail* BydTangDetail::_internal_mutable_chassis() {
  _has_bits_[0] |= 0x00000002u;
  if (chassis_ == nullptr) {
    auto* p = CreateMaybeMessage<::deeproute::canbus::BydTangChassisDetail>(GetArena());
    chassis_ = p;
  }
  return chassis_;
}
inline ::deeproute::canbus::BydTangChassisDetail* BydTangDetail::mutable_chassis() {
  // @@protoc_insertion_point(field_mutable:deeproute.canbus.BydTangDetail.chassis)
  return _internal_mutable_chassis();
}
inline void BydTangDetail::set_allocated_chassis(::deeproute::canbus::BydTangChassisDetail* chassis) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(chassis_);
  }
  if (chassis) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(chassis)->GetArena();
    if (message_arena != submessage_arena) {
      chassis = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, chassis, submessage_arena);
    }
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  chassis_ = chassis;
  // @@protoc_insertion_point(field_set_allocated:deeproute.canbus.BydTangDetail.chassis)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace canbus
}  // namespace deeproute

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_canbus_2fbyd_5ftang_5fdetail_2eproto
