# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: drapi/gwm/gwm_second_start.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'drapi/gwm/gwm_second_start.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n drapi/gwm/gwm_second_start.proto\x12\x03gwm\"\xd8\x01\n\x10SecondStartPopup\x12\x46\n\x12second_start_popup\x18\x01 \x01(\x0e\x32*.gwm.SecondStartPopup.SecondStartPopupEnum\"|\n\x14SecondStartPopupEnum\x12!\n\x1dSECOND_START_POPUP_NO_DISPLAY\x10\x00\x12#\n\x1fSECOND_START_POPUP_SECOND_START\x10\x01\x12\x1c\n\x18SECOND_START_POPUP_CLOSE\x10\x02\"\xa0\x01\n\x0eSecondStartReq\x12@\n\x10second_start_req\x18\x01 \x01(\x0e\x32&.gwm.SecondStartReq.SecondStartReqEnum\"L\n\x12SecondStartReqEnum\x12\x1a\n\x16SECOND_START_REQ_START\x10\x00\x12\x1a\n\x16SECOND_START_REQ_CLOSE\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'drapi.gwm.gwm_second_start_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SECONDSTARTPOPUP']._serialized_start=42
  _globals['_SECONDSTARTPOPUP']._serialized_end=258
  _globals['_SECONDSTARTPOPUP_SECONDSTARTPOPUPENUM']._serialized_start=134
  _globals['_SECONDSTARTPOPUP_SECONDSTARTPOPUPENUM']._serialized_end=258
  _globals['_SECONDSTARTREQ']._serialized_start=261
  _globals['_SECONDSTARTREQ']._serialized_end=421
  _globals['_SECONDSTARTREQ_SECONDSTARTREQENUM']._serialized_start=345
  _globals['_SECONDSTARTREQ_SECONDSTARTREQENUM']._serialized_end=421
# @@protoc_insertion_point(module_scope)
