# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: compliance/compliance.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='compliance/compliance.proto',
  package='deeproute.compliance',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x1b\x63ompliance/compliance.proto\x12\x14\x64\x65\x65proute.compliance\"\"\n\nCompliance\x12\x14\n\x0cis_sensitive\x18\x01 \x01(\x08')
)




_COMPLIANCE = _descriptor.Descriptor(
  name='Compliance',
  full_name='deeproute.compliance.Compliance',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_sensitive', full_name='deeproute.compliance.Compliance.is_sensitive', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=87,
)

DESCRIPTOR.message_types_by_name['Compliance'] = _COMPLIANCE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Compliance = _reflection.GeneratedProtocolMessageType('Compliance', (_message.Message,), dict(
  DESCRIPTOR = _COMPLIANCE,
  __module__ = 'compliance.compliance_pb2'
  # @@protoc_insertion_point(class_scope:deeproute.compliance.Compliance)
  ))
_sym_db.RegisterMessage(Compliance)


# @@protoc_insertion_point(module_scope)
